import VersoBlog
open Verso Genre Blog
open Verso.Output Verso.Output.Html

/-- The two "lines of code by date" charts. The SVGs are regenerated at each site
deploy (and daily) into `static_files/` by the `pages` workflow, so this page never
needs touching as the project grows. They are embedded as a raw HTML blob: each
`<img>` simply points at the static asset. -/
def locGraphs : Html := {{
  <div class="loc-graphs">
    <figure class="loc-figure">
      <img class="loc-graph" src="static/loc-tauceti.svg"
           alt="Tau Ceti: lines of Lean by date"/>
      <figcaption>"The Lean library under " <code>"TauCeti/"</code> ", total lines by date."</figcaption>
    </figure>
    <figure class="loc-figure">
      <img class="loc-graph" src="static/loc-roadmap.svg"
           alt="Tau Ceti Roadmap: lines written by date"/>
      <figcaption>"The human-owned roadmap repository, total lines by date."</figcaption>
    </figure>
  </div>
}}

/-- The per-roadmap chart: cumulative net lines of Lean, split by the roadmap each
merged PR advances (its `roadmap/<Area>` label). Regenerated at each deploy by the
`pages` workflow (`scripts/loc_roadmap_graph.py`), from the PR labels rather than git,
so it too needs no committed state. Embedded as a raw HTML blob pointing at the asset. -/
def roadmapGraph : Html := {{
  <figure class="loc-figure loc-figure-wide">
    <img class="loc-graph" src="static/loc-per-roadmap.svg"
         alt="Tau Ceti: cumulative net lines of Lean per roadmap, over time"/>
    <figcaption>"Net lines added or refactored per roadmap, stacked, by the date each PR merged."</figcaption>
  </figure>
}}

/-- A current snapshot of participation across the four project repositories: the GitHub
accounts that remain once recognised automation is excluded, which is not the same as a
verified count of people. Regenerated daily by the `pages` workflow
(`scripts/participant_graph.py`) from GitHub PR/issue participant connections and
default-branch commit contributors. -/
private def participationGraph : Html := {{
  <figure class="loc-figure loc-figure-wide">
    <img class="loc-graph" src="static/participation.svg"
         alt="Participation across the four Tau Ceti repositories, by repository"/>
    <figcaption>"Participating accounts by repository, once recognised automation is excluded; an account active in several repositories appears in several bars."</figcaption>
  </figure>
}}

/-- Current queue health and historical PR throughput. The five SVGs and their exact JSON
data are regenerated by `scripts/pr_stats_graphs.py` in the scheduled Pages workflow. -/
private def prGraphs : Html := {{
  <div class="loc-graphs">
    <figure class="loc-figure">
      <img class="loc-graph" src="static/pr-queue-age.svg"
           alt="Open pull request age, followed by time awaiting author and time in review"
           loading="lazy"/>
      <figcaption>"Age of every open PR, then elapsed time in its current awaiting-author or review cycle."</figcaption>
    </figure>
    <figure class="loc-figure">
      <img class="loc-graph" src="static/review-cycles-reached.svg"
           alt="Pull requests reaching each successive review cycle"
           loading="lazy"/>
      <figcaption>"PRs reaching each review cycle; a cycle begins whenever a PR returns to " <code>"awaiting-review"</code> " after its author's turn."</figcaption>
    </figure>
    <figure class="loc-figure">
      <img class="loc-graph" src="static/rolling-seven-day-history.svg"
           alt="Trailing-seven-day pull request throughput, participation, and merge latency"
           loading="lazy"/>
      <figcaption>"Merges, active PR authors, and creation-to-merge latency in trailing seven-day UTC windows."</figcaption>
    </figure>
    <figure class="loc-figure">
      <img class="loc-graph" src="static/cumulative-merges-by-contributor.svg"
           alt="Cumulative merged pull requests by contributor"
           loading="lazy"/>
      <figcaption>"Cumulative merged PRs by author since project inception."</figcaption>
    </figure>
    <figure class="loc-figure">
      <img class="loc-graph" src="static/cumulative-reviews-by-contributor.svg"
           alt="Cumulative trusted v1 review scoreboards by contributor"
           loading="lazy"/>
      <figcaption>"Cumulative canonical v1 review scoreboards posted by repository-associated accounts; external accounts and edits to existing scoreboards do not add counts."</figcaption>
    </figure>
  </div>
}}

#doc (Page) "Statistics" =>

How much mathematics has Tau Ceti formalized, and how fast is the roadmap that
directs it growing? Each chart plots the total number of lines present at every
commit, counted straight from the git history and rebuilt from scratch at each
deploy, so the figures cannot drift.

:::blob locGraphs
:::

The vertical scales differ by an order of magnitude and on purpose: the library is
measured in tens of thousands of lines of Lean, the roadmap in thousands of lines of
prose and target statements. The library figure counts only the mathematics — the
files under `TauCeti/` — not the website or tooling.

Which roadmap is all that Lean serving? Every pull request is labelled with the
roadmap it advances, so we can split the library by roadmap. The chart below stacks
the net lines each roadmap has accrued — every merged PR's additions minus its
deletions, attributed to its roadmap — by the day the PR merged. Because it sums
diffs rather than counting the lines in the tree, a line later rewritten counts under
both PRs, so this measures work landed per roadmap, not a snapshot line count.
Infrastructure and refactor PRs, which advance no roadmap, are left out.

:::blob roadmapGraph
:::

How is the contribution and review pipeline behaving? The first chart separates a
PR's total age from the clock on its current state. PRs outside the awaiting-author
and review states appear in total time open but not in the two current-state panels.
The review-cycle chart counts durable label transitions rather than scoreboard
comments, because a scoreboard may be edited in place as later rounds complete. A
cycle is one entry into review from an author or CI state, so the pipeline swapping
`awaiting-review` for `review-in-progress` and back within a single round stays one
cycle. Its subtitle states when those review-state transitions first appear in project
history.

The rolling historical charts use complete UTC days; cumulative contributor histories
include the current partial UTC day through the snapshot time. The contributor SVGs
show every contributor while that remains legible, then cap themselves at 24 named
lines and combine the remaining long tail. Exact totals for every login remain available in
the generated [`pr-stats.json`](static/pr-stats.json). Review attribution follows the
status pipeline's trust boundary: only canonical v1 scoreboards from repository owners,
members, or collaborators are included.

:::blob prGraphs
:::

Who has taken part? The snapshot below counts GitHub accounts that have
opened a pull request or issue, participated in those conversations (including
reviews), or authored a commit on the default branch of TauCeti, TauCetiRoadmap,
TauCetiWorker, or TauCetiReview. Accounts recognised as automation are dropped:
logins carrying GitHub's `[bot]` suffix, together with the project's own automation
aliases. Nothing verifies that the accounts left over belong to people, so any
automation the filter does not recognise is still counted. The headline
deduplicates accounts across all four repositories; the repository bars
deliberately overlap.

:::blob participationGraph
:::
