/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Geometry.Lie.Exponential.Smoothness

/-!
# Derivative of the Lie-group exponential

Let `center = extChartAt I 1 1` and let `F` be the tangent-space exponential written in the
extended chart at the identity. Smoothness of the exponential makes `F` differentiable at zero.
Along each line `t ↦ t • v`, the scaling law identifies `F` with the coordinate expression of
the canonical integral curve generated by `v`. Its initial velocity is `v`, so `F` has derivative
the identity at zero; equivalently, `F(v) = F(0) + v + o(‖v‖)`.

## Main results

* `hasFDerivAt_extChartAt_mulInvariantExp_zero`: in model-space identity coordinates, the
  tangent-space exponential has derivative the identity at zero.
* `hasFDerivAt_extChartAt_lieExp_zero`: the identity-chart derivative of the derivation-based
  exponential is the canonical linear isometry to the model space.

## References

* [Lie groups and the Lie algebra correspondence roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/LieGroups/README.md),
  Deliverable A, Layer 0, "The exponential map".
-/

public section

open Function Manifold
open scoped ContDiff Manifold Topology

noncomputable section

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
  {H : Type*} [TopologicalSpace H] {I : ModelWithCorners ℝ E H}
  {G : Type*} [TopologicalSpace G] [ChartedSpace H G] [Group G]

attribute [local instance] LieGroup.minSmoothnessThree

/-- **In identity coordinates the exponential along a ray is the integral curve of its
direction.** -/
private theorem extChartAt_mulInvariantExp_smul_eq [CompleteSpace E]
    [LieGroup I (minSmoothness ℝ 3) G] [T2Space G] [BoundarylessManifold I G] (v : E) :
    (fun t : ℝ => extChartAt I (1 : G)
        (mulInvariantExp (I := I) (G := G) (((t • v : E) : GroupLieAlgebra I G)))) =
      (extChartAt I (1 : G)) ∘
        mulInvariantIntegralCurve (I := I) (G := G) (v : GroupLieAlgebra I G) 1 := by
  funext t
  simp only [Function.comp_apply]
  apply congrArg (extChartAt I (1 : G))
  have hsmul : ((t • v : E) : GroupLieAlgebra I G) = t • (v : GroupLieAlgebra I G) :=
    (groupLieAlgebraEquivModelVectorSpace (I := I) (G := G)).symm.map_smul t v
  rw [hsmul]
  exact mulInvariantExp_smul (I := I) (G := G) (v : GroupLieAlgebra I G) t

/-- **In model-space identity coordinates, the tangent-space exponential is differentiable at
zero.** -/
private theorem differentiableAt_extChartAt_mulInvariantExp_zero [FiniteDimensional ℝ E]
    [LieGroup I ∞ G] [T2Space G] [BoundarylessManifold I G] :
    DifferentiableAt ℝ (fun v : E => extChartAt I (1 : G)
      (mulInvariantExp (I := I) (G := G) (v : GroupLieAlgebra I G))) 0 := by
  have hsource : mulInvariantExp (I := I) (G := G)
      (0 : GroupLieAlgebra I G) ∈ (chartAt H (1 : G)).source := by
    rw [mulInvariantExp_zero]
    exact mem_chart_source H (1 : G)
  have hsmoothCoord := (contMDiffAt_iff_target_of_mem_source
    (f := fun v : E => mulInvariantExp (I := I) (G := G)
      (v : GroupLieAlgebra I G)) (y := (1 : G)) hsource).mp
    (contMDiffAt_mulInvariantExp_modelSpace_zero (I := I) (G := G))
  exact (hsmoothCoord.2.mdifferentiableAt (by simp)).differentiableAt

/-- In model-space identity coordinates, the tangent-space exponential has derivative the identity
at zero. -/
theorem hasFDerivAt_extChartAt_mulInvariantExp_zero
    [FiniteDimensional ℝ E] [LieGroup I ∞ G] [T2Space G] [BoundarylessManifold I G] :
    HasFDerivAt
      (fun v : E => extChartAt I (1 : G)
        (mulInvariantExp (I := I) (G := G) (v : GroupLieAlgebra I G)))
      (ContinuousLinearMap.id ℝ E) 0 := by
  let _ : CompleteSpace E := FiniteDimensional.complete ℝ E
  have hFdiff := differentiableAt_extChartAt_mulInvariantExp_zero (I := I) (G := G)
  apply hFdiff.hasFDerivAt.congr_fderiv
  apply ContinuousLinearMap.ext
  intro v
  have hscale : HasDerivAt (fun t : ℝ => t • v) v 0 := by
    simpa using ((hasDerivAt_id (𝕜 := ℝ) (0 : ℝ)).smul_const v)
  have hline := hFdiff.hasFDerivAt.comp_hasDerivAt_of_eq 0 hscale (by simp)
  have hlineCurve : HasDerivAt (fun t : ℝ => extChartAt I (1 : G)
      (mulInvariantExp (I := I) (G := G) (((t • v : E) : GroupLieAlgebra I G)))) v 0 := by
    rw [extChartAt_mulInvariantExp_smul_eq v]
    exact hasDerivAt_extChartAt_mulInvariantIntegralCurve_zero (I := I) (G := G) v
  exact hline.unique hlineCurve

/-- In identity-chart coordinates, the derivative of the derivation-based Lie exponential at zero
is the canonical linear isometry from left-invariant derivations to the model space. -/
theorem hasFDerivAt_extChartAt_lieExp_zero
    [FiniteDimensional ℝ E] [LieGroup I ∞ G] [T2Space G] [BoundarylessManifold I G] :
    HasFDerivAt
      (fun X : LeftInvariantDerivation I G => extChartAt I (1 : G) (lieExp X))
      (leftInvariantDerivationLinearIsometryEquivModelVectorSpace
        (I := I) (G := G)).toContinuousLinearEquiv.toContinuousLinearMap 0 := by
  let L := leftInvariantDerivationLinearIsometryEquivModelVectorSpace
    (I := I) (G := G)
  have hmodel := hasFDerivAt_extChartAt_mulInvariantExp_zero (I := I) (G := G)
  have hmodelAt : HasFDerivAt
      (fun v : E => extChartAt I (1 : G)
        (mulInvariantExp (I := I) (G := G) (v : GroupLieAlgebra I G)))
      (ContinuousLinearMap.id ℝ E) (L 0) := by
    simpa using hmodel
  have hcomp := hmodelAt.comp 0 L.toContinuousLinearEquiv.hasFDerivAt
  have hfun :
      (fun X : LeftInvariantDerivation I G => extChartAt I (1 : G) (lieExp X)) =
        (fun v : E => extChartAt I (1 : G)
          (mulInvariantExp (I := I) (G := G) (v : GroupLieAlgebra I G))) ∘ L := by
    funext X
    apply congrArg (extChartAt I (1 : G))
    rw [lieExp_eq_mulInvariantExp]
    simp only [L, leftInvariantDerivationLinearIsometryEquivModelVectorSpace_apply]
  rw [hfun]
  simpa only [ContinuousLinearMap.id_comp] using hcomp
