/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.RingTheory.Spectrum.Prime.Topology
public import Mathlib.Topology.Connected.LocallyConnected

/-!
# The idempotent cutting out a connected component

When `Spec R` is locally connected, the connected component of a point `x` is clopen. The
idempotent--clopen correspondence therefore supplies a canonical idempotent `eₓ : R` whose basic
open is that component. Equivalently, the ideal `(1 - eₓ)` cuts out the component as a closed
subset, and the spectrum of `R / (1 - eₓ)` is homeomorphic to it.

The construction is stated under the natural topological hypothesis
`LocallyConnectedSpace (PrimeSpectrum R)`. In particular it applies to Noetherian rings, for which
Tau Ceti already supplies the locally connected instance.

## Main declarations

* `PrimeSpectrum.quotientHomeomorphZeroLocus`: the spectrum of a quotient is homeomorphic to the
  zero locus of the quotient ideal.
* `PrimeSpectrum.connectedComponentIdempotent`: the idempotent selecting the component of a point.
* `PrimeSpectrum.connectedComponentIdeal`: the ideal generated by its complementary idempotent.
* `PrimeSpectrum.primeSpectrumQuotientHomeomorphConnectedComponent`: the spectrum of the quotient
  by that ideal is the selected connected component.

## References

* The Stacks Project, Tag 00EE, for the idempotent--clopen correspondence.
* J. S. Milne, *Algebraic Groups* (2017), Section 2.a, for the identity-component construction.

This ordinary connected-component construction is a commutative-algebra prerequisite for the
geometric identity component in Layer 3 of the ReductiveGroups roadmap; it does not itself assert
compatibility with base change.
-/

public section

open Set Topology

namespace PrimeSpectrum

universe u

variable {R : Type u} [CommRing R]

/-- The image of the spectrum of a quotient is the zero locus of the quotient ideal. -/
theorem range_comap_quotientMk_eq_zeroLocus (I : Ideal R) :
    Set.range (comap (Ideal.Quotient.mk I)) = zeroLocus (I : Set R) := by
  rw [range_comap_of_surjective _ _ Ideal.Quotient.mk_surjective, Ideal.mk_ker]

/-- The spectrum of `R / I` is homeomorphic to the zero locus of `I` in `Spec R`. -/
noncomputable def quotientHomeomorphZeroLocus (I : Ideal R) :
    PrimeSpectrum (R ⧸ I) ≃ₜ (zeroLocus (I : Set R) : Set (PrimeSpectrum R)) :=
  (isEmbedding_comap_of_surjective
      (R ⧸ I) (Ideal.Quotient.mk I) Ideal.Quotient.mk_surjective).toHomeomorph.trans
    (Homeomorph.setCongr (range_comap_quotientMk_eq_zeroLocus I))

/-- After coercion to `PrimeSpectrum R`, the quotient-spectrum homeomorphism sends a point to its
contraction along the quotient map. -/
@[simp]
theorem quotientHomeomorphZeroLocus_apply_coe (I : Ideal R) (y : PrimeSpectrum (R ⧸ I)) :
    (quotientHomeomorphZeroLocus I y : PrimeSpectrum R) = comap (Ideal.Quotient.mk I) y := by
  -- `Homeomorph.setCongr` has no application lemma, so unfold it here; it preserves the
  -- underlying point while changing only the proof that the point belongs to the target set.
  simp only [quotientHomeomorphZeroLocus, Homeomorph.trans_apply, Homeomorph.setCongr]
  exact Topology.IsEmbedding.toHomeomorph_apply_coe
    (isEmbedding_comap_of_surjective
      (R ⧸ I) (Ideal.Quotient.mk I) Ideal.Quotient.mk_surjective) y

variable [LocallyConnectedSpace (PrimeSpectrum R)]

/-- The idempotent whose basic open is the connected component of `x` in `Spec R`.

It is the inverse image of the clopen connected component under Mathlib's order equivalence
between idempotents and clopen subsets of the prime spectrum. -/
noncomputable def connectedComponentIdempotent (x : PrimeSpectrum R) : R :=
  (isIdempotentElemEquivClopens.symm
    ⟨connectedComponent x, isClopen_connectedComponent⟩).1

/-- The element selecting a connected component is idempotent. -/
theorem isIdempotentElem_connectedComponentIdempotent (x : PrimeSpectrum R) :
    IsIdempotentElem (connectedComponentIdempotent x) :=
  (isIdempotentElemEquivClopens.symm
    ⟨connectedComponent x, isClopen_connectedComponent⟩).2

/-- The basic open of the component idempotent is exactly the connected component. -/
theorem basicOpen_connectedComponentIdempotent (x : PrimeSpectrum R) :
    (basicOpen (connectedComponentIdempotent x) : Set (PrimeSpectrum R)) =
      connectedComponent x := by
  simpa only [connectedComponentIdempotent, TopologicalSpace.Clopens.coe_toOpens,
    TopologicalSpace.Opens.coe_mk, TopologicalSpace.Clopens.coe_mk] using congrArg SetLike.coe
      (basicOpen_isIdempotentElemEquivClopens_symm
        (⟨connectedComponent x, isClopen_connectedComponent⟩ :
          TopologicalSpace.Clopens (PrimeSpectrum R)))

/-- The component idempotent does not belong to the prime ideal defining the selected point. -/
@[simp]
theorem connectedComponentIdempotent_notMem_asIdeal (x : PrimeSpectrum R) :
    connectedComponentIdempotent x ∉ x.asIdeal := by
  rw [← mem_basicOpen, ← SetLike.mem_coe, basicOpen_connectedComponentIdempotent]
  exact mem_connectedComponent

/-- An idempotent is the component idempotent exactly when its basic open is the selected
connected component. -/
theorem eq_connectedComponentIdempotent_iff {e : R} (he : IsIdempotentElem e)
    (x : PrimeSpectrum R) :
    e = connectedComponentIdempotent x ↔
      (basicOpen e : Set (PrimeSpectrum R)) = connectedComponent x := by
  constructor
  · rintro rfl
    exact basicOpen_connectedComponentIdempotent x
  · intro h
    apply basicOpen_injOn_isIdempotentElem he
      (isIdempotentElem_connectedComponentIdempotent x)
    exact TopologicalSpace.Opens.ext
      (h.trans (basicOpen_connectedComponentIdempotent x).symm)

/-- If the whole prime spectrum is connected, its component idempotent is one. -/
@[simp]
theorem connectedComponentIdempotent_eq_one [ConnectedSpace (PrimeSpectrum R)]
    (x : PrimeSpectrum R) : connectedComponentIdempotent x = 1 := by
  symm
  apply (eq_connectedComponentIdempotent_iff IsIdempotentElem.one x).mpr
  simp only [basicOpen_one, TopologicalSpace.Opens.coe_top]
  exact (PreconnectedSpace.connectedComponent_eq_univ x).symm

/-- The ideal generated by the complementary idempotent `1 - eₓ`. Its zero locus is the
connected component of `x`. -/
noncomputable def connectedComponentIdeal (x : PrimeSpectrum R) : Ideal R :=
  Ideal.span {1 - connectedComponentIdempotent x}

/-- Membership in the component ideal means being a multiple of its complementary idempotent. -/
theorem mem_connectedComponentIdeal_iff {x : PrimeSpectrum R} {r : R} :
    r ∈ connectedComponentIdeal x ↔
      ∃ a, a * (1 - connectedComponentIdempotent x) = r := by
  rw [connectedComponentIdeal, Ideal.mem_span_singleton']

/-- The component idempotent becomes one in the quotient by the component ideal. -/
@[simp]
theorem quotientMk_connectedComponentIdempotent_eq_one (x : PrimeSpectrum R) :
    Ideal.Quotient.mk (connectedComponentIdeal x) (connectedComponentIdempotent x) = 1 := by
  rw [← map_one (Ideal.Quotient.mk (connectedComponentIdeal x)), Ideal.Quotient.eq,
    mem_connectedComponentIdeal_iff]
  exact ⟨-1, by ring⟩

/-- The zero locus of the component ideal is exactly the connected component of the point. -/
@[simp]
theorem zeroLocus_connectedComponentIdeal (x : PrimeSpectrum R) :
    zeroLocus (connectedComponentIdeal x : Set R) = connectedComponent x := by
  rw [connectedComponentIdeal, zeroLocus_span,
    zeroLocus_eq_basicOpen_of_isIdempotentElem _
      (isIdempotentElem_connectedComponentIdempotent x).one_sub,
    sub_sub_cancel, basicOpen_connectedComponentIdempotent]

/-- The component ideal is contained in the prime ideal defining the selected point. -/
theorem connectedComponentIdeal_le_asIdeal (x : PrimeSpectrum R) :
    connectedComponentIdeal x ≤ x.asIdeal := by
  rw [← SetLike.coe_subset_coe, ← mem_zeroLocus,
    zeroLocus_connectedComponentIdeal]
  exact mem_connectedComponent

/-- **The spectrum of `R / (1 - eₓ)` is homeomorphic to the connected component of `x`.**

The homeomorphism is induced by contraction along the quotient map. -/
noncomputable def primeSpectrumQuotientHomeomorphConnectedComponent
    (x : PrimeSpectrum R) :
    PrimeSpectrum (R ⧸ connectedComponentIdeal x) ≃ₜ
      (connectedComponent x : Set (PrimeSpectrum R)) :=
  (quotientHomeomorphZeroLocus (connectedComponentIdeal x)).trans
    (Homeomorph.setCongr (zeroLocus_connectedComponentIdeal x))

/-- The spectrum of the component quotient is connected. -/
noncomputable instance connectedSpace_quotient_connectedComponentIdeal
    (x : PrimeSpectrum R) :
    ConnectedSpace (PrimeSpectrum (R ⧸ connectedComponentIdeal x)) := by
  let e := primeSpectrumQuotientHomeomorphConnectedComponent x
  let _ : ConnectedSpace (connectedComponent x) :=
    Subtype.connectedSpace isConnected_connectedComponent
  exact
    { isPreconnected_univ := by
        rw [← e.isPreconnected_image]
        simpa using (PreconnectedSpace.isPreconnected_univ :
          IsPreconnected (Set.univ : Set (connectedComponent x)))
      toNonempty := e.toEquiv.nonempty_congr.mpr inferInstance }

/-- The quotient by the component ideal is nontrivial. -/
noncomputable instance nontrivial_quotient_connectedComponentIdeal
    (x : PrimeSpectrum R) : Nontrivial (R ⧸ connectedComponentIdeal x) :=
  (Classical.choice
    (inferInstance : Nonempty (PrimeSpectrum (R ⧸ connectedComponentIdeal x)))).nontrivial

/-- After coercion to `PrimeSpectrum R`, the quotient-spectrum homeomorphism sends a point to its
contraction along the quotient map. -/
@[simp]
theorem primeSpectrumQuotientHomeomorphConnectedComponent_apply_coe
    (x : PrimeSpectrum R) (y : PrimeSpectrum (R ⧸ connectedComponentIdeal x)) :
    (primeSpectrumQuotientHomeomorphConnectedComponent x y : PrimeSpectrum R) =
      comap (Ideal.Quotient.mk (connectedComponentIdeal x)) y := by
  rw [primeSpectrumQuotientHomeomorphConnectedComponent, Homeomorph.trans_apply]
  change (quotientHomeomorphZeroLocus (connectedComponentIdeal x) y : PrimeSpectrum R) = _
  exact quotientHomeomorphZeroLocus_apply_coe _ y

end PrimeSpectrum
