/-
Copyright (c) 2026 Tau Ceti. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import TauCeti.LinearAlgebra.End.FiniteOrder
public import Mathlib.Analysis.Complex.Polynomial.Basic
public import Mathlib.RepresentationTheory.Character
public import Mathlib.RingTheory.RootsOfUnity.PrimitiveRoots

/-!
# The arithmetic of character values

If `g` is an element of finite order `n` in a group and `ρ` is a finite-dimensional
representation, then `ρ g` satisfies `X ^ n - 1`, so every root of its characteristic polynomial
is an `n`-th root of unity. As soon as that characteristic polynomial splits, over an
algebraically closed field for instance, the character value `ρ.character g` is the sum of
`finrank` of these roots of unity.

This file proves that dichotomy and reads off its arithmetic consequences: the character value is
integral over `ℤ`, and over `ℂ` it lies in the ring `ℤ[ζ]` generated by a primitive `n`-th root of
unity and is bounded in absolute value by the degree `χ(1)`. The endomorphism `ρ g` is moreover
semisimple as soon as `n` is invertible in the coefficient field, since `X ^ n - 1` is then
squarefree.

The two facts about `ρ g` as a bare endomorphism live in `TauCeti.LinearAlgebra.End.FiniteOrder`.

## Main results

* `TauCeti.Representation.exists_multiset_rootsOfUnity_char_eq_sum_of_splits`: whenever
  `(ρ g).charpoly` splits, a character value is a sum of `finrank` many `n`-th roots of unity. The
  variant `TauCeti.Representation.exists_multiset_rootsOfUnity_char_eq_sum` specializes it to an
  algebraically closed field.
* `TauCeti.FDRep.isIntegral_char`: **character values are algebraic integers**.
* `TauCeti.FDRep.char_mem_adjoin_of_isPrimitiveRoot`: over `ℂ` they lie in `ℤ[ζ_e]`, for `ζ_e`
  a primitive root of unity of order the exponent of the group.
* `TauCeti.FDRep.norm_char_le_finrank`: over `ℂ`, `‖χ(g)‖ ≤ χ(1)`.
* `TauCeti.FDRep.isSemisimple_ρ`: if the characteristic of `k` does not divide `|G|`, then
  `V.ρ g` is a semisimple endomorphism; over `ℂ` the hypothesis is found by instance search.

The eigenvalues are taken with algebraic multiplicity, as the root multiset of the characteristic
polynomial. The *set* of roots of the minimal polynomial is the same, namely the distinct
eigenvalues, but its root multiplicities record maximal Jordan block sizes rather than algebraic
multiplicities, so they do not sum to the trace.

Cyclotomic integrality is stated over `ℂ` only, as the roadmap prescribes.

## References

* [Character Theory roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/CharacterTheory/README.md),
  Layer 4, "The arithmetic of character values".
* I. M. Isaacs, *Character Theory of Finite Groups* (1976), Chapter 3.
* J.-P. Serre, *Linear Representations of Finite Groups* (1977), Section 12.1.
-/

public section

namespace TauCeti

open Module Polynomial

universe u v w

namespace Representation

section Field

variable {k : Type u} {G : Type v} {V : Type w} [Field k] [Monoid G] [AddCommGroup V] [Module k V]
  [FiniteDimensional k V]

/-- If `g ^ n = 1` then every eigenvalue of `ρ g` is an `n`-th root of unity. -/
theorem pow_eq_one_of_mem_roots_charpoly (ρ : Representation k G V) {g : G} {n : ℕ}
    (hg : g ^ n = 1) {μ : k} (hμ : μ ∈ (ρ g).charpoly.roots) : μ ^ n = 1 :=
  End.pow_eq_one_of_isRoot_charpoly (by rw [← map_pow, hg, map_one]) (isRoot_of_mem_roots hμ)

/-- **A character value is a sum of roots of unity.** If `g ^ n = 1` and the characteristic
polynomial of `ρ g` splits, then `ρ.character g` is the sum of a multiset of `finrank k V` many
`n`-th roots of unity, namely the eigenvalues of `ρ g` with algebraic multiplicity. -/
theorem exists_multiset_rootsOfUnity_char_eq_sum_of_splits (ρ : Representation k G V) {g : G}
    {n : ℕ} (hsplits : (ρ g).charpoly.Splits) (hg : g ^ n = 1) :
    ∃ s : Multiset k, Multiset.card s = finrank k V ∧ (∀ μ ∈ s, μ ^ n = 1) ∧
      ρ.character g = s.sum := by
  refine ⟨(ρ g).charpoly.roots, ?_, fun _ hμ => pow_eq_one_of_mem_roots_charpoly ρ hg hμ, ?_⟩
  · rw [← hsplits.natDegree_eq_card_roots, LinearMap.charpoly_natDegree]
  · simp only [Representation.character]
    exact End.trace_eq_sum_roots_charpoly_of_splits hsplits

/-- **A character value is a sum of roots of unity.** Over an algebraically closed field, if
`g ^ n = 1` then `ρ.character g` is the sum of a multiset of `finrank k V` many `n`-th roots of
unity, namely the eigenvalues of `ρ g` with algebraic multiplicity. -/
theorem exists_multiset_rootsOfUnity_char_eq_sum [IsAlgClosed k] (ρ : Representation k G V) {g : G}
    {n : ℕ} (hg : g ^ n = 1) :
    ∃ s : Multiset k, Multiset.card s = finrank k V ∧ (∀ μ ∈ s, μ ^ n = 1) ∧
      ρ.character g = s.sum :=
  exists_multiset_rootsOfUnity_char_eq_sum_of_splits ρ (IsAlgClosed.splits _) hg

omit [FiniteDimensional k V] in
/-- If `g ^ n = 1` with `n` invertible in `k`, then `ρ g` is a semisimple endomorphism. This needs
no hypothesis on the field beyond invertibility of `n`. Over a field splitting `X ^ n - 1`, an
algebraically closed one for instance, semisimplicity of `ρ g` is its diagonalizability, the form
in which it underlies the eigenvalue description of character values. -/
theorem isSemisimple_of_pow_eq_one (ρ : Representation k G V) {g : G} {n : ℕ} (hn : (n : k) ≠ 0)
    (hg : g ^ n = 1) : End.IsSemisimple (ρ g) :=
  End.isSemisimple_of_pow_eq_one hn (by rw [← map_pow, hg, map_one])

/-- **Character values are algebraic integers**: if the characteristic polynomial of `ρ g` splits,
the value of a character at an element `g` of finite order is integral over `ℤ`, being a sum of
roots of unity. -/
theorem isIntegral_char_of_splits (ρ : Representation k G V) {g : G} {n : ℕ}
    (hsplits : (ρ g).charpoly.Splits) (hn : n ≠ 0) (hg : g ^ n = 1) :
    IsIntegral ℤ (ρ.character g) := by
  obtain ⟨s, -, hroot, hsum⟩ := exists_multiset_rootsOfUnity_char_eq_sum_of_splits ρ hsplits hg
  rw [hsum]
  refine IsIntegral.multiset_sum fun μ hμ => IsIntegral.of_pow (Nat.pos_of_ne_zero hn) ?_
  rw [hroot μ hμ]
  exact isIntegral_one

/-- **Character values are algebraic integers**: over an algebraically closed field, the value of a
character at an element of finite order is integral over `ℤ`, being a sum of roots of unity. -/
theorem isIntegral_char [IsAlgClosed k] (ρ : Representation k G V) {g : G} {n : ℕ}
    (hn : n ≠ 0) (hg : g ^ n = 1) : IsIntegral ℤ (ρ.character g) :=
  isIntegral_char_of_splits ρ (IsAlgClosed.splits _) hn hg

end Field

section Complex

variable {G : Type v} {V : Type w} [Monoid G] [AddCommGroup V] [Module ℂ V] [FiniteDimensional ℂ V]

/-- **Character values are cyclotomic integers**: over `ℂ`, if `ζ` is a primitive `n`-th root of
unity and `g ^ n = 1`, then `ρ.character g` lies in the subring `ℤ[ζ]` of `ℂ`. -/
theorem char_mem_adjoin_of_isPrimitiveRoot (ρ : Representation ℂ G V) {g : G} {ζ : ℂ} {n : ℕ}
    [NeZero n] (hζ : IsPrimitiveRoot ζ n) (hg : g ^ n = 1) :
    ρ.character g ∈ Algebra.adjoin ℤ ({ζ} : Set ℂ) := by
  obtain ⟨s, -, hroot, hsum⟩ := exists_multiset_rootsOfUnity_char_eq_sum ρ hg
  have hmem : ζ ∈ Algebra.adjoin ℤ ({ζ} : Set ℂ) := Algebra.subset_adjoin rfl
  rw [hsum]
  refine Subalgebra.multiset_sum_mem (Algebra.adjoin ℤ ({ζ} : Set ℂ)) fun μ hμ => ?_
  obtain ⟨i, -, rfl⟩ := hζ.eq_pow_of_pow_eq_one (hroot μ hμ)
  exact Subalgebra.pow_mem _ hmem i

/-- Over `ℂ` a character value at an element of finite order is bounded in absolute value by the
degree of the representation, since it is a sum of `finrank ℂ V` many roots of unity. -/
theorem norm_char_le_finrank (ρ : Representation ℂ G V) {g : G} {n : ℕ} (hn : n ≠ 0)
    (hg : g ^ n = 1) : ‖ρ.character g‖ ≤ finrank ℂ V := by
  obtain ⟨s, hcard, hroot, hsum⟩ := exists_multiset_rootsOfUnity_char_eq_sum ρ hg
  have hmap : s.map (fun μ => ‖μ‖) = s.map (fun _ => (1 : ℝ)) :=
    Multiset.map_congr rfl fun μ hμ => Complex.norm_eq_one_of_pow_eq_one (hroot μ hμ) hn
  calc ‖ρ.character g‖ = ‖s.sum‖ := by rw [hsum]
    _ ≤ (s.map (fun μ => ‖μ‖)).sum := norm_multiset_sum_le s
    _ = finrank ℂ V := by rw [hmap]; simp [hcard]

end Complex

end Representation

namespace FDRep

variable {G : Type v} [Group G] [Finite G]

/-- **Character values are algebraic integers.** For a finite group, every value of the character
of a finite-dimensional complex representation is integral over `ℤ`. -/
theorem isIntegral_char (V : FDRep ℂ G) (g : G) : IsIntegral ℤ (V.character g) :=
  Representation.isIntegral_char V.ρ (isOfFinOrder_of_finite g).orderOf_pos.ne'
    (pow_orderOf_eq_one g)

/-- **Character values are cyclotomic integers.** For a finite group of exponent `e` and a
primitive `e`-th root of unity `ζ`, every value of a complex character lies in `ℤ[ζ]`. -/
theorem char_mem_adjoin_of_isPrimitiveRoot (V : FDRep ℂ G) {ζ : ℂ}
    (hζ : IsPrimitiveRoot ζ (Monoid.exponent G)) (g : G) :
    V.character g ∈ Algebra.adjoin ℤ ({ζ} : Set ℂ) :=
  haveI : NeZero (Monoid.exponent G) := ⟨Monoid.exponent_ne_zero_of_finite⟩
  Representation.char_mem_adjoin_of_isPrimitiveRoot V.ρ hζ (Monoid.pow_exponent_eq_one g)

/-- Over `ℂ`, a character of a finite group is bounded in absolute value by its degree,
`‖χ(g)‖ ≤ χ(1)`. -/
theorem norm_char_le_finrank (V : FDRep ℂ G) (g : G) : ‖V.character g‖ ≤ finrank ℂ V :=
  Representation.norm_char_le_finrank V.ρ (isOfFinOrder_of_finite g).orderOf_pos.ne'
    (pow_orderOf_eq_one g)

omit [Finite G] in
/-- **Diagonalizability.** If the order of `G` is invertible in `k`, which forces `G` to be finite
and which every finite group satisfies in characteristic zero, then `V.ρ g` is a semisimple
endomorphism. Over an algebraically closed field, `ℂ` for instance, this is its
diagonalizability. -/
theorem isSemisimple_ρ {k : Type u} [Field k] [NeZero (Nat.card G : k)] (V : FDRep k G)
    (g : G) : End.IsSemisimple (V.ρ g) := by
  refine Representation.isSemisimple_of_pow_eq_one V.ρ ?_ (pow_orderOf_eq_one g)
  obtain ⟨m, hm⟩ := orderOf_dvd_natCard g
  intro h
  exact NeZero.ne (Nat.card G : k) (by rw [hm, Nat.cast_mul, h, zero_mul])

end FDRep

end TauCeti
