/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.Algebra.Lie.Sl2
public import TauCeti.Algebra.Lie.GeneralLinear.Basic

/-!
# The standard `sl₂` triples of the special linear Lie algebra

Mathlib defines an abstract `sl₂` triple (`IsSl2Triple h e f`: the relations `⁅e, f⁆ = h`,
`⁅h, e⁆ = 2e`, `⁅h, f⁆ = -2f`, with `h ≠ 0`) and the whole primitive-vector calculus that rests on
it, but exhibits no triple in the special linear Lie algebra. This file supplies the standard ones:
for every pair `i ≠ j` of indices, the matrix units

`e = Eᵢⱼ`, `f = Eⱼᵢ`, `h = Eᵢᵢ - Eⱼⱼ`

form an `sl₂` triple inside `LieAlgebra.SpecialLinear.sl n R`, over an arbitrary nontrivial
commutative ring. These are the triples attached to the roots of `sl n`, and for `n = 2` the triple
is the whole Lie algebra: `sl (Fin 2) R` is free of rank `3` on `e`, `f`, `h`, so the Lie subalgebra
`IsSl2Triple.toLieSubalgebra` generated by the standard triple is everything.

That last fact is what makes `sl (Fin 2) R` usable as *the* model `sl₂`: statements about a triple
`t` which are false for a triple sitting inside a bigger Lie algebra become correct once
`t.toLieSubalgebra R = ⊤`, and this file provides the model in which that hypothesis holds.

## Main results

* `TauCeti.isSl2Triple_single`: for `i ≠ j`, the matrix units `Eᵢⱼ`, `Eⱼᵢ` and `Eᵢᵢ - Eⱼⱼ` form an
  `sl₂` triple in `sl n R`. The three bracket relations are available separately as
  `TauCeti.lie_single_single_eq_singleSubSingle`, `TauCeti.lie_singleSubSingle_single` and
  `TauCeti.lie_singleSubSingle_single_swap`.
* `TauCeti.slFinTwoBasis`: the standard basis `(e, f, h)` of `sl (Fin 2) R`, obtained from the
  coordinate isomorphism `TauCeti.slFinTwoEquivFun` and identified vector by vector in
  `TauCeti.slFinTwoBasis_zero`, `TauCeti.slFinTwoBasis_one` and `TauCeti.slFinTwoBasis_two`, with
  `TauCeti.finrank_sl_fin_two` reading off the rank `3`.
* `TauCeti.toLieSubalgebra_isSl2Triple_single_eq_top`: in `sl (Fin 2) R` the subalgebra generated
  by a standard triple is the whole of `sl (Fin 2) R`. The underlying expansion of an arbitrary
  element in the triple is `TauCeti.eq_smul_single_add_smul_single_add_smul_singleSubSingle`.

## Implementation notes

Everything is stated over an arbitrary commutative ring `R`; nontriviality of `R` is needed only
where `h ≠ 0` is claimed, and `StrongRankCondition R` only for the rank computation. Mathlib does
not register `LieRing.ofAssociativeRing` as a global instance, so, as in
`Mathlib/Algebra/Lie/Classical.lean`, it is a local instance here.

The `sl (Fin 2) R` results are stated for an arbitrary pair `i ≠ j` of indices in `Fin 2`, not just
for `(0, 1)`: the opposite pair gives the opposite triple `(-h, f, e)`, and both are standard.

## References

This is the concrete input to Layer 0 of
`TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`, whose worked `sl₂` is
*"`LieAlgebra.SpecialLinear.sl (Fin 2) K` with its standard triple"*, and whose classification
targets carry the hypothesis `htop : t.toLieSubalgebra K = ⊤` that
`TauCeti.toLieSubalgebra_isSl2Triple_single_eq_top` discharges for that model.
-/

public section

namespace TauCeti

open Matrix LieAlgebra Module

attribute [local instance 100] LieRing.ofAssociativeRing

variable (R : Type*) [CommRing R] {n : Type*} [DecidableEq n] [Fintype n]

/-! ### The standard triples of `sl n R` -/

section Triple

variable {R} {i j : n}

/-- `⁅Eᵢⱼ, Eⱼᵢ⁆ = Eᵢᵢ - Eⱼⱼ` in `sl n R`: the defining relation `⁅e, f⁆ = h` of the standard
`sl₂` triple. -/
@[simp]
theorem lie_single_single_eq_singleSubSingle (hij : i ≠ j) (c : R) :
    ⁅SpecialLinear.single i j hij c, SpecialLinear.single j i hij.symm (1 : R)⁆
      = SpecialLinear.singleSubSingle i j c := by
  ext : 1
  rw [SpecialLinear.sl_bracket, SpecialLinear.val_single, SpecialLinear.val_single,
    SpecialLinear.val_singleSubSingle, ← LieRing.of_associative_ring_bracket,
    lie_single_single_eq_sub]

/-- `⁅Eᵢᵢ - Eⱼⱼ, Eᵢⱼ⁆ = 2 Eᵢⱼ` in `sl n R`: the relation `⁅h, e⁆ = 2e` of the standard `sl₂`
triple. -/
@[simp]
theorem lie_singleSubSingle_single (hij : i ≠ j) (c : R) :
    ⁅SpecialLinear.singleSubSingle i j (1 : R), SpecialLinear.single i j hij c⁆
      = (2 : R) • SpecialLinear.single i j hij c := by
  ext : 1
  rw [SpecialLinear.sl_bracket]
  simp [sub_mul, mul_sub, hij.symm, two_smul]

/-- Swapping the two indices of `Eᵢᵢ - Eⱼⱼ` negates it. -/
@[simp]
theorem neg_singleSubSingle (i j : n) (c : R) :
    -SpecialLinear.singleSubSingle i j c = SpecialLinear.singleSubSingle j i c := by
  ext : 1
  simp [neg_sub]

/-- `⁅Eᵢᵢ - Eⱼⱼ, Eⱼᵢ⁆ = -2 Eⱼᵢ` in `sl n R`: the relation `⁅h, f⁆ = -2f` of the standard `sl₂`
triple. It is the previous relation for the opposite pair of indices, since swapping them negates
`h`. -/
@[simp]
theorem lie_singleSubSingle_single_swap (hij : i ≠ j) (c : R) :
    ⁅SpecialLinear.singleSubSingle i j (1 : R), SpecialLinear.single j i hij.symm c⁆
      = -((2 : R) • SpecialLinear.single j i hij.symm c) := by
  rw [← neg_singleSubSingle j i, neg_lie, lie_singleSubSingle_single hij.symm]

/-- `Eᵢᵢ (c) - Eⱼⱼ (c)` is nonzero in `sl n R` when `i ≠ j` and `c ≠ 0`: its `(i, i)` entry is
`c`. -/
theorem singleSubSingle_ne_zero (hij : i ≠ j) {c : R} (hc : c ≠ 0) :
    SpecialLinear.singleSubSingle i j c ≠ 0 := fun h => hc <| by
  have := congr_fun (congr_fun (congr_arg Subtype.val h) i) i
  simpa [Matrix.single_apply, hij, hij.symm] using this

/-- **The standard `sl₂` triple of `sl n R`.** For `i ≠ j` the matrix units `e = Eᵢⱼ`, `f = Eⱼᵢ`
and `h = Eᵢᵢ - Eⱼⱼ` satisfy the `sl₂` relations. These are the concrete counterparts of the triples
that `LieAlgebra.IsKilling.exists_isSl2Triple_of_weight_isNonZero` attaches to a root of a
Killing-semisimple Lie algebra: `e` and `f` span the root spaces of `εᵢ - εⱼ` and of its negative,
and `h` is the corresponding coroot. -/
theorem isSl2Triple_single [Nontrivial R] (hij : i ≠ j) :
    IsSl2Triple (SpecialLinear.singleSubSingle i j (1 : R))
      (SpecialLinear.single i j hij 1) (SpecialLinear.single j i hij.symm 1) where
  h_ne_zero := singleSubSingle_ne_zero hij one_ne_zero
  lie_e_f := lie_single_single_eq_singleSubSingle hij 1
  lie_h_e_nsmul := by
    rw [lie_singleSubSingle_single hij, two_smul, two_smul]
  lie_h_f_nsmul := by
    rw [lie_singleSubSingle_single_swap hij, two_smul, two_smul]

end Triple

/-! ### `sl (Fin 2) R` as the model `sl₂` -/

section FinTwo

variable {R}

/-- The bottom-right entry of a trace-zero `2 × 2` matrix is minus its top-left entry. -/
@[simp]
theorem val_one_one_eq_neg_val_zero_zero (A : SpecialLinear.sl (Fin 2) R) :
    A.val 1 1 = -A.val 0 0 := by
  have h : A.val.trace = 0 := A.2
  rw [Matrix.trace_fin_two] at h
  linear_combination h

variable (R)

/-- The coordinates of a trace-zero `2 × 2` matrix in the standard basis `(e, f, h)`, namely
`A ↦ (A 0 1, A 1 0, A 0 0)`. The inverse rebuilds `A` from them, using that the trace-zero
condition forces `A 1 1 = -A 0 0`. -/
def slFinTwoEquivFun : SpecialLinear.sl (Fin 2) R ≃ₗ[R] (Fin 3 → R) where
  toFun A := ![A.val 0 1, A.val 1 0, A.val 0 0]
  map_add' A B := by ext k; fin_cases k <;> simp
  map_smul' c A := by ext k; fin_cases k <;> simp
  invFun v := ⟨!![v 2, v 0; v 1, -v 2], by
    have h : (!![v 2, v 0; v 1, -v 2] : Matrix (Fin 2) (Fin 2) R).trace = 0 := by simp
    exact h⟩
  left_inv A := by
    refine Subtype.ext ?_
    ext a b
    fin_cases a <;> fin_cases b <;> simp
  right_inv v := by ext k; fin_cases k <;> simp

variable {R}

@[simp]
theorem slFinTwoEquivFun_apply (A : SpecialLinear.sl (Fin 2) R) :
    slFinTwoEquivFun R A = ![A.val 0 1, A.val 1 0, A.val 0 0] := by rfl

@[simp]
theorem slFinTwoEquivFun_symm_apply (v : Fin 3 → R) :
    ((slFinTwoEquivFun R).symm v).val = !![v 2, v 0; v 1, -v 2] := by rfl

variable (R)

/-- **The standard basis of `sl₂`.** The matrix units `e = E₀₁`, `f = E₁₀` and `h = E₀₀ - E₁₁` are
a basis of `sl (Fin 2) R`; see `TauCeti.slFinTwoBasis_apply`. -/
noncomputable def slFinTwoBasis : Basis (Fin 3) R (SpecialLinear.sl (Fin 2) R) :=
  Basis.ofEquivFun (slFinTwoEquivFun R)

/-- The three vectors of the standard basis of `sl (Fin 2) R`, as matrices: index `0` is the
raising element `e = E₀₁`, index `1` the lowering element `f = E₁₀`, and index `2` the semisimple
element `h = E₀₀ - E₁₁`. The individual cases, phrased inside `sl (Fin 2) R` rather than in
matrices, are `TauCeti.slFinTwoBasis_zero`, `TauCeti.slFinTwoBasis_one` and
`TauCeti.slFinTwoBasis_two`. -/
theorem slFinTwoBasis_apply (k : Fin 3) :
    (slFinTwoBasis R k).val =
      ![Matrix.single 0 1 1, Matrix.single 1 0 1,
        Matrix.single 0 0 1 - Matrix.single 1 1 (1 : R)] k := by
  rw [slFinTwoBasis, Basis.coe_ofEquivFun]
  fin_cases k <;> · ext a b; fin_cases a <;> fin_cases b <;> simp

/-- The first standard basis vector of `sl₂` is the raising element `e = E₀₁`. -/
@[simp]
theorem slFinTwoBasis_zero : slFinTwoBasis R 0 = SpecialLinear.single 0 1 zero_ne_one 1 :=
  Subtype.ext <| by simpa using slFinTwoBasis_apply R 0

/-- The second standard basis vector of `sl₂` is the lowering element `f = E₁₀`. -/
@[simp]
theorem slFinTwoBasis_one : slFinTwoBasis R 1 = SpecialLinear.single 1 0 one_ne_zero 1 :=
  Subtype.ext <| by simpa using slFinTwoBasis_apply R 1

/-- The third standard basis vector of `sl₂` is the semisimple element `h = E₀₀ - E₁₁`. -/
@[simp]
theorem slFinTwoBasis_two : slFinTwoBasis R 2 = SpecialLinear.singleSubSingle 0 1 (1 : R) :=
  Subtype.ext <| by simpa using slFinTwoBasis_apply R 2

instance instModuleFreeSlFinTwo : Module.Free R (SpecialLinear.sl (Fin 2) R) :=
  Module.Free.of_basis (slFinTwoBasis R)

instance instModuleFiniteSlFinTwo : Module.Finite R (SpecialLinear.sl (Fin 2) R) :=
  Module.Finite.of_basis (slFinTwoBasis R)

/-- `sl₂` is three-dimensional. -/
theorem finrank_sl_fin_two [StrongRankCondition R] :
    finrank R (SpecialLinear.sl (Fin 2) R) = 3 := by
  simpa using finrank_eq_card_basis (slFinTwoBasis R)

variable {R}

/-- Every element of `sl (Fin 2) R` is a combination of a standard triple: the coefficients are
read off from the entries, using `A 1 1 = -A 0 0`. -/
theorem eq_smul_single_add_smul_single_add_smul_singleSubSingle
    (A : SpecialLinear.sl (Fin 2) R) {i j : Fin 2} (hij : i ≠ j) :
    A = A.val i j • SpecialLinear.single i j hij 1 + A.val j i • SpecialLinear.single j i hij.symm 1
      + A.val i i • SpecialLinear.singleSubSingle i j (1 : R) := by
  have key : ∀ p q : Fin 2, p ≠ q → (p = 0 ∧ q = 1) ∨ (p = 1 ∧ q = 0) := by decide
  refine Subtype.ext ?_
  ext a b
  obtain ⟨rfl, rfl⟩ | ⟨rfl, rfl⟩ := key i j hij <;>
    fin_cases a <;> fin_cases b <;> simp

/-- **The standard triple generates `sl₂`.** In `sl (Fin 2) R` the Lie subalgebra spanned by a
standard `sl₂` triple is everything, so `sl (Fin 2) R` is the model in which the classification
hypothesis `t.toLieSubalgebra R = ⊤` holds. -/
theorem toLieSubalgebra_isSl2Triple_single_eq_top [Nontrivial R] {i j : Fin 2} (hij : i ≠ j) :
    (isSl2Triple_single (R := R) hij).toLieSubalgebra R = ⊤ := by
  refine eq_top_iff.mpr fun A _ => ?_
  rw [IsSl2Triple.mem_toLieSubalgebra_iff, lie_single_single_eq_singleSubSingle hij]
  exact ⟨A.val i j, A.val j i, A.val i i,
    eq_smul_single_add_smul_single_add_smul_singleSubSingle A hij⟩

end FinTwo

end TauCeti
