/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.Algebra.Lie.Quotient
public import TauCeti.Algebra.Lie.Sl2.Casimir

/-!
# Complete reducibility for `sl₂`

Every finite-dimensional module over a Lie algebra generated by an `sl₂` triple, over an
algebraically closed field of characteristic zero, is a direct sum of irreducibles: every Lie
submodule has a complement (`TauCeti.exists_isCompl_of_toLieSubalgebra_eq_top`). With the
classification of the irreducibles already in `TauCeti/Algebra/Lie/Sl2/Classification.lean`, this
says that every such module is `⨁ V(nᵢ)`.

The proof is the classical two-step one, run with the concrete Casimir operator of
`TauCeti/Algebra/Lie/Sl2/Casimir.lean`, which is built from the triple alone and so needs neither
the universal enveloping algebra nor the Killing form: this is Layer 0 of the roadmap, and the
general Casimir argument for a semisimple Lie algebra is Layer 5.

* **Step one, the invariant vector** (`TauCeti.exists_invariant_notMem`). If `L` carries `M` into a
  proper submodule `N`, then `M` has an invariant vector outside `N`. The induction is on `dim M`.
  If `L` acts trivially on `M`, any vector outside `N` will do. If `N` is irreducible, then `L` acts
  nontrivially on `N` — otherwise the action would compose to zero, and `L`, being perfect
  (`TauCeti.lie_eq_zero_of_lie_lie_eq_zero`), would act trivially on `M` — so the Casimir operator
  is injective on `N` while its range lies in `N`; it
  is therefore not surjective, hence not injective, and any nonzero kernel vector is invariant and
  outside `N`. If `N` is reducible, split off a proper nonzero `W < N`: the inductive hypothesis in
  `M ⧸ W` produces a vector `v₀ ∉ N` with `⁅L, v₀⁆ ⊆ W`, and the inductive hypothesis in
  `W + K v₀` turns it into a genuinely invariant vector.

* **Step two, the invariant projection** (`TauCeti.exists_isCompl_of_toLieSubalgebra_eq_top`). For
  an arbitrary submodule `N ≤ M`, apply step one inside the module `M →ₗ[K] M`, to the submodule of
  endomorphisms killing `N` sitting inside the submodule of those acting on `N` by a scalar. An
  invariant vector outside the first is, after rescaling, an `L`-equivariant projection of `M` onto
  `N`, and its kernel is the complement.

## Main results

* `TauCeti.exists_invariant_notMem`: an invariant vector outside a proper submodule containing
  `⁅L, M⁆`.
* `TauCeti.exists_isCompl_of_toLieSubalgebra_eq_top`: **complete reducibility.** Every Lie
  submodule of a finite-dimensional module over a Lie algebra generated by an `sl₂` triple has a
  complement.
* `TauCeti.exists_isCompl_sl_fin_two`: the same for the model algebra
  `LieAlgebra.SpecialLinear.sl (Fin 2) K`.

## References

This is Layer 0 of `TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`, whose `sl₂`
complete reducibility is `TauCeti.exists_isCompl_of_toLieSubalgebra_eq_top`.

* [J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*][humphreys1972],
  §6.2 and §6.3.
-/

public section

namespace TauCeti

open LieModule Module

universe v

/-! ### Step one: an invariant vector outside a proper submodule -/

section Invariant

variable {K : Type*} [Field K] [CharZero K] [IsAlgClosed K]
variable {L : Type*} [LieRing L] [LieAlgebra K L]
variable {h e f : L} {t : IsSl2Triple h e f}

omit [CharZero K] [IsAlgClosed K] in
/-- **A Lie submodule admitting no proper nonzero Lie submodule of the ambient module is
irreducible.** The hypothesis quantifies over Lie submodules of `M` lying below `N`, whereas
irreducibility speaks of Lie submodules of `N` itself; `LieSubmodule.map_incl_lt_iff_lt_top`
transports between the two. -/
private theorem isIrreducible_of_forall_not_le_of_ne_bot_of_ne {M : Type v} [AddCommGroup M]
    [Module K M] [LieRingModule L M] [LieModule K L M] {N : LieSubmodule K L M} (hNbot : N ≠ ⊥)
    (hred : ∀ W : LieSubmodule K L M, W ≠ ⊥ → W ≠ N → ¬ W ≤ N) :
    LieModule.IsIrreducible K L N := by
  have : Nontrivial N := (LieSubmodule.nontrivial_iff_ne_bot K L _).2 hNbot
  refine LieModule.IsIrreducible.mk fun N' hN' ↦ ?_
  by_contra hne
  have hlt : N'.map N.incl < N :=
    LieSubmodule.map_incl_lt_iff_lt_top.2 (lt_top_iff_ne_top.2 hne)
  have hbot : N'.map N.incl = ⊥ := by
    by_contra hb
    exact hred _ hb (ne_of_lt hlt) (le_of_lt hlt)
  refine hN' ((LieSubmodule.eq_bot_iff _).2 fun z hz ↦ ?_)
  have hmem : (z : M) ∈ N'.map N.incl := ⟨z, hz, rfl⟩
  rw [hbot] at hmem
  exact Subtype.ext (by simpa using hmem)

/-- **The Casimir operator supplies an invariant vector outside an irreducible submodule.** If `L`
carries `M` into an irreducible proper `N` and acts nontrivially somewhere on `M`, then `L` acts
nontrivially on `N`, so the Casimir operator is injective on `N`. Its range lies in `N`, so it is
not surjective on `M`, hence — `M` being finite-dimensional — not injective, and any nonzero kernel
vector is invariant and outside `N`. -/
private theorem exists_invariant_notMem_of_isIrreducible (htop : t.toLieSubalgebra K = ⊤)
    {M : Type v} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
    [FiniteDimensional K M] {N : LieSubmodule K L M} (hN : N ≠ ⊤)
    (htriv : ∀ (x : L) (m : M), ⁅x, m⁆ ∈ N) (hact : ∃ (x : L) (m : M), ⁅x, m⁆ ≠ 0)
    (hirr : LieModule.IsIrreducible K L N) : ∃ v : M, v ∉ N ∧ ∀ x : L, ⁅x, v⁆ = 0 := by
  have hactN : ∃ (x : L) (z : N), ⁅x, z⁆ ≠ 0 := by
    by_contra hcon
    push Not at hcon
    obtain ⟨x, m, hm⟩ := hact
    refine hm (lie_eq_zero_of_lie_lie_eq_zero htop (fun y z w ↦ ?_) x m)
    have hval := congrArg (Subtype.val : N → M) (hcon y ⟨⁅z, w⁆, htriv z w⟩)
    rw [LieSubmodule.coe_bracket] at hval
    simpa using hval
  have hinjN := sl2Casimir_injective (M := N) (t := t) htop hactN
  have hinj : ∀ w : M, w ∈ N → sl2Casimir K h e f M w = 0 → w = 0 := by
    intro w hw hw0
    have hz : (⟨w, hw⟩ : N) = 0 := by
      refine hinjN (Subtype.ext ?_)
      rw [coe_sl2Casimir_lieSubmodule]
      simpa using hw0
    exact congrArg Subtype.val hz
  have hrange : ∀ m : M, sl2Casimir K h e f M m ∈ N := by
    intro m
    rw [sl2Casimir_apply]
    exact N.add_mem (N.add_mem (N.lie_mem (htriv f m)) (N.lie_mem (htriv e m)))
      (N.smul_mem _ (N.lie_mem (htriv h m)))
  have hnotinj : ¬ Function.Injective (sl2Casimir K h e f M) := by
    intro hi
    refine hN ((LieSubmodule.toSubmodule_inj _ _).1 ?_)
    rw [LieSubmodule.top_toSubmodule, eq_top_iff]
    intro m _
    obtain ⟨w, rfl⟩ := LinearMap.injective_iff_surjective.1 hi m
    exact hrange w
  obtain ⟨v, hvmem, hv0⟩ := (Submodule.ne_bot_iff _).1
    (fun hc ↦ hnotinj (LinearMap.ker_eq_bot.1 hc))
  have hv : sl2Casimir K h e f M v = 0 := hvmem
  refine ⟨v, fun hc ↦ hv0 (hinj v hc hv), fun x ↦ ?_⟩
  refine hinj _ (htriv x v) ?_
  rw [← lie_sl2Casimir t (htop ▸ LieSubalgebra.mem_top x) v, hv, lie_zero]

omit [CharZero K] [IsAlgClosed K] in
/-- **In `M ⧸ W` the inductive hypothesis produces a vector outside `N` whose brackets land in
`W`.** This is the first half of the reducible step: the quotient by a nonzero `W ≤ N` is smaller,
so the induction applies to it, and pulling the resulting vector back along `W`-cosets turns
invariance in the quotient into `⁅L, v₀⁆ ⊆ W` upstairs. -/
private theorem exists_notMem_forall_lie_mem_of_le {d : ℕ}
    (ih : ∀ {M' : Type v} [AddCommGroup M'] [Module K M'] [LieRingModule L M'] [LieModule K L M'],
      ∀ [FiniteDimensional K M'] (N' : LieSubmodule K L M'), finrank K M' ≤ d → N' ≠ ⊤ →
        (∀ (x : L) (m : M'), ⁅x, m⁆ ∈ N') → ∃ v : M', v ∉ N' ∧ ∀ x : L, ⁅x, v⁆ = 0)
    {M : Type v} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
    {N W : LieSubmodule K L M} [FiniteDimensional K (M ⧸ W)] (hquot : finrank K (M ⧸ W) ≤ d)
    (hN : N ≠ ⊤) (htriv : ∀ (x : L) (m : M), ⁅x, m⁆ ∈ N) (hWle : W ≤ N) :
    ∃ v₀ : M, v₀ ∉ N ∧ ∀ x : L, ⁅x, v₀⁆ ∈ W := by
  have hNq : N.map (LieSubmodule.Quotient.mk' W) ≠ ⊤ := by
    intro hcon
    refine hN ((LieSubmodule.toSubmodule_inj _ _).1 ?_)
    have hmap : Submodule.map (W : Submodule K M).mkQ (N : Submodule K M) = ⊤ := by
      have := congrArg LieSubmodule.toSubmodule hcon
      rwa [LieSubmodule.toSubmodule_map, LieSubmodule.top_toSubmodule] at this
    have hWN := (Submodule.map_mkQ_eq_top _ _).1 hmap
    rwa [sup_eq_right.2 ((LieSubmodule.toSubmodule_le_toSubmodule _ _).2 hWle)] at hWN
  obtain ⟨w, hwmem, hwinv⟩ := ih (N.map (LieSubmodule.Quotient.mk' W)) hquot hNq
    (by
      intro x q
      induction q using Quotient.inductionOn' with
      | h m => exact ⟨⁅x, m⁆, htriv x m, rfl⟩)
  obtain ⟨v₀, rfl⟩ := LieSubmodule.Quotient.surjective_mk' W w
  refine ⟨v₀, fun hc ↦ hwmem ⟨v₀, hc, rfl⟩, fun x ↦ ?_⟩
  rw [← LieSubmodule.Quotient.mk_eq_zero]
  simpa using hwinv x

omit [CharZero K] [IsAlgClosed K] in
/-- **The span of a Lie submodule and one extra vector is carried into that submodule**, provided
every bracket of the extra vector already lies in it. -/
private theorem lie_mem_of_mem_sup_span_singleton {M : Type v} [AddCommGroup M] [Module K M]
    [LieRingModule L M] [LieModule K L M] {W : LieSubmodule K L M} {v₀ : M}
    (hv₀W : ∀ x : L, ⁅x, v₀⁆ ∈ W) (x : L) {m : M}
    (hm : m ∈ (W : Submodule K M) ⊔ Submodule.span K {v₀}) : ⁅x, m⁆ ∈ W := by
  obtain ⟨y, hy, z, hz, rfl⟩ := Submodule.mem_sup.1 hm
  obtain ⟨c, rfl⟩ := Submodule.mem_span_singleton.1 hz
  rw [lie_add, lie_smul]
  exact W.add_mem (W.lie_mem hy) (W.smul_mem c (hv₀W x))

omit [CharZero K] [IsAlgClosed K] in
/-- **A vector of `W + K v₀` lying outside `W` lies outside `N`**, when `W ≤ N` and `v₀ ∉ N`. -/
private theorem notMem_of_mem_sup_span_singleton {M : Type v} [AddCommGroup M] [Module K M]
    {N W : Submodule K M} {v₀ p : M} (hWle : W ≤ N) (hv₀N : v₀ ∉ N)
    (hp : p ∈ W ⊔ Submodule.span K {v₀}) (hpW : p ∉ W) : p ∉ N := by
  intro hcon
  obtain ⟨y, hy, z, hz, hyz⟩ := Submodule.mem_sup.1 hp
  obtain ⟨c, rfl⟩ := Submodule.mem_span_singleton.1 hz
  rcases eq_or_ne c 0 with rfl | hc0
  · exact hpW (by simpa [← hyz] using hy)
  · refine hv₀N ?_
    have hcv : c • v₀ ∈ N := by
      have hsub : c • v₀ = p - y := by rw [← hyz]; abel
      rw [hsub]
      exact N.sub_mem hcon (hWle hy)
    simpa [hc0] using N.smul_mem c⁻¹ hcv

omit [CharZero K] [IsAlgClosed K] in
/-- **A vector outside `N` whose brackets land in `W` upgrades to a genuinely invariant one.** This
is the second half of the reducible step. The span `W + K v₀` is carried into `W` by `L`, so it is a
Lie submodule; it has dimension at most `finrank W + 1`, so the induction applies to it with `W`
pulled back inside, and the vector it returns is invariant in `M` and still outside `N`. -/
private theorem exists_invariant_notMem_of_forall_lie_mem {d : ℕ}
    (ih : ∀ {M' : Type v} [AddCommGroup M'] [Module K M'] [LieRingModule L M'] [LieModule K L M'],
      ∀ [FiniteDimensional K M'] (N' : LieSubmodule K L M'), finrank K M' ≤ d → N' ≠ ⊤ →
        (∀ (x : L) (m : M'), ⁅x, m⁆ ∈ N') → ∃ v : M', v ∉ N' ∧ ∀ x : L, ⁅x, v⁆ = 0)
    {M : Type v} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
    {N W : LieSubmodule K L M} [FiniteDimensional K W] {v₀ : M} (hWrank : finrank K W + 1 ≤ d)
    (hWle : W ≤ N) (hv₀N : v₀ ∉ N) (hv₀W : ∀ x : L, ⁅x, v₀⁆ ∈ W) :
    ∃ v : M, v ∉ N ∧ ∀ x : L, ⁅x, v⁆ = 0 := by
  let P : LieSubmodule K L M :=
    { __ := (W : Submodule K M) ⊔ Submodule.span K {v₀}
      lie_mem := fun {x m} hm ↦
        Submodule.mem_sup_left (lie_mem_of_mem_sup_span_singleton hv₀W _ hm) }
  have hPmem : ∀ m : M, m ∈ P ↔ m ∈ (W : Submodule K M) ⊔ Submodule.span K {v₀} :=
    fun _ ↦ Iff.rfl
  have hv₀P : v₀ ∈ P :=
    (hPmem _).2 (Submodule.mem_sup_right (Submodule.mem_span_singleton_self v₀))
  have hPrank : finrank K P ≤ d := by
    have hne : v₀ ≠ 0 := fun hc ↦ hv₀N (hc ▸ N.zero_mem)
    have hle := Submodule.finrank_add_le_finrank_add_finrank
      (W : Submodule K M) (Submodule.span K {v₀})
    rw [finrank_span_singleton hne] at hle
    have hP : finrank K (((W : Submodule K M) ⊔ Submodule.span K {v₀} :
        Submodule K M) : Type _) = finrank K P := rfl
    have hw : finrank K ((W : Submodule K M) : Type _) = finrank K W := rfl
    omega
  have : FiniteDimensional K P :=
    Submodule.finiteDimensional_sup (W : Submodule K M) (Submodule.span K {v₀})
  have hWcomap : W.comap P.incl ≠ ⊤ := by
    rw [Ne, LieSubmodule.comap_incl_eq_top]
    exact fun hc ↦ hv₀N (hWle (hc hv₀P))
  obtain ⟨p, hpmem, hpinv⟩ := ih (W.comap P.incl) hPrank hWcomap
    (fun x q ↦ lie_mem_of_mem_sup_span_singleton hv₀W x ((hPmem _).1 q.2))
  refine ⟨(p : M), notMem_of_mem_sup_span_singleton hWle hv₀N ((hPmem _).1 p.2) hpmem,
    fun x ↦ ?_⟩
  have hp := hpinv x
  rw [← LieSubmodule.coe_bracket, hp]
  rfl

omit [CharZero K] [IsAlgClosed K] in
/-- **The reducible step.** If the proper submodule `N` admits a Lie submodule `W` that is neither
`⊥` nor `N`, then `M` has an invariant vector outside `N`.

Neither algebraic closure nor characteristic zero is needed here; those enter only through the
Casimir argument on the irreducible branch. -/
private theorem exists_invariant_notMem_of_ne_bot_of_ne_of_le {d : ℕ}
    (ih : ∀ {M' : Type v} [AddCommGroup M'] [Module K M'] [LieRingModule L M'] [LieModule K L M'],
      ∀ [FiniteDimensional K M'] (N' : LieSubmodule K L M'), finrank K M' ≤ d → N' ≠ ⊤ →
        (∀ (x : L) (m : M'), ⁅x, m⁆ ∈ N') → ∃ v : M', v ∉ N' ∧ ∀ x : L, ⁅x, v⁆ = 0)
    {M : Type v} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
    [FiniteDimensional K M] {N W : LieSubmodule K L M} (hrank : finrank K M ≤ d + 1)
    (hN : N ≠ ⊤) (htriv : ∀ (x : L) (m : M), ⁅x, m⁆ ∈ N) (hWbot : W ≠ ⊥) (hWN : W ≠ N)
    (hWle : W ≤ N) : ∃ v : M, v ∉ N ∧ ∀ x : L, ⁅x, v⁆ = 0 := by
  -- The inductive hypothesis is used twice: on the quotient `M ⧸ W`, which is strictly smaller
  -- because `W` is nonzero, to get a vector outside `N` whose brackets land in `W`; and then,
  -- through `exists_invariant_notMem_of_forall_lie_mem`, on `W + K v₀`.
  have hNlt : finrank K N < finrank K M := Submodule.finrank_lt (fun hc ↦ hN
    ((LieSubmodule.toSubmodule_inj _ _).1 (by rw [hc, LieSubmodule.top_toSubmodule])))
  have hWnt : Nontrivial W := (LieSubmodule.nontrivial_iff_ne_bot K L _).2 hWbot
  have hWpos : 0 < finrank K W := finrank_pos_iff.2 hWnt
  have hWsub : (W : Submodule K M) < (N : Submodule K M) :=
    lt_of_le_of_ne ((LieSubmodule.toSubmodule_le_toSubmodule _ _).2 hWle)
      (fun hc ↦ hWN ((LieSubmodule.toSubmodule_inj _ _).1 hc))
  have hWlt : finrank K W < finrank K N := Submodule.finrank_lt_finrank_of_lt hWsub
  have hquot : finrank K (M ⧸ W) ≤ d := by
    -- There is no cross-type conversion here to justify. Mathlib *defines* the Lie-submodule
    -- quotient to be the submodule quotient, `HasQuotient M (LieSubmodule R L M)` being
    -- `⟨fun N => M ⧸ N.toSubmodule⟩` in `Mathlib/Algebra/Lie/Quotient.lean`, and `↥W` carries the
    -- submodule's own carrier. So the submodule rank identity *is* the identity for `M ⧸ W`;
    -- ascribing the type is what states it in that form.
    have hadd : finrank K (M ⧸ W) + finrank K W = finrank K M :=
      Submodule.finrank_quotient_add_finrank (W : Submodule K M)
    omega
  obtain ⟨v₀, hv₀N, hv₀W⟩ := exists_notMem_forall_lie_mem_of_le ih hquot hN htriv hWle
  exact exists_invariant_notMem_of_forall_lie_mem ih (by omega) hWle hv₀N hv₀W

/-- The inductive form of `TauCeti.exists_invariant_notMem`, with the dimension of the ambient
module bounded by an explicit `d`, since the induction changes the module. -/
private theorem exists_invariant_notMem_aux (htop : t.toLieSubalgebra K = ⊤) (d : ℕ) :
    ∀ {M : Type v} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M],
      ∀ [FiniteDimensional K M] (N : LieSubmodule K L M), finrank K M ≤ d → N ≠ ⊤ →
        (∀ (x : L) (m : M), ⁅x, m⁆ ∈ N) → ∃ v : M, v ∉ N ∧ ∀ x : L, ⁅x, v⁆ = 0 := by
  induction d with
  | zero =>
    intro M _ _ _ _ _ N hrank hN _
    refine absurd ((LieSubmodule.toSubmodule_inj _ _).1 ?_) hN
    rw [LieSubmodule.top_toSubmodule]
    refine Submodule.eq_top_of_finrank_eq ?_
    have := Submodule.finrank_le (N : Submodule K M)
    omega
  | succ d ih =>
    intro M _ _ _ _ _ N hrank hN htriv
    obtain ⟨u, hu⟩ : ∃ u : M, u ∉ N := by
      by_contra hcon
      push Not at hcon
      exact hN (eq_top_iff.2 fun v _ ↦ hcon v)
    by_cases hact : ∀ (x : L) (m : M), ⁅x, m⁆ = 0
    · exact ⟨u, hu, fun x ↦ hact x u⟩
    push Not at hact
    have hNbot : N ≠ ⊥ := by
      rintro rfl
      obtain ⟨x, m, hm⟩ := hact
      exact hm (by simpa using htriv x m)
    by_cases hred : ∃ W : LieSubmodule K L M, W ≠ ⊥ ∧ W ≠ N ∧ W ≤ N
    · -- `N` is reducible: pass to `M ⧸ W`, then to the submodule `W + K v₀`.
      obtain ⟨W, hWbot, hWN, hWle⟩ := hred
      exact exists_invariant_notMem_of_ne_bot_of_ne_of_le ih hrank hN htriv hWbot hWN hWle
    · -- `N` is irreducible: the Casimir operator supplies the invariant vector.
      push Not at hred
      exact exists_invariant_notMem_of_isIrreducible htop hN htriv hact
        (isIrreducible_of_forall_not_le_of_ne_bot_of_ne hNbot hred)

variable {M : Type v} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]

/-- **An invariant vector outside a proper submodule.** If a Lie algebra generated by an `sl₂`
triple carries a finite-dimensional module `M` into a proper Lie submodule `N`, then `M` has an
invariant vector outside `N`.

This is the load-bearing half of complete reducibility: applied inside the endomorphism module
`M →ₗ[K] M` it produces the equivariant projection onto an arbitrary submodule. -/
theorem exists_invariant_notMem (htop : t.toLieSubalgebra K = ⊤) [FiniteDimensional K M]
    (N : LieSubmodule K L M) (hN : N ≠ ⊤) (htriv : ∀ (x : L) (m : M), ⁅x, m⁆ ∈ N) :
    ∃ v : M, v ∉ N ∧ ∀ x : L, ⁅x, v⁆ = 0 :=
  exists_invariant_notMem_aux htop (finrank K M) N le_rfl hN htriv

end Invariant

/-! ### Step two: complete reducibility -/

section Hom

variable {K : Type*} [Field K]
variable {L : Type*} [LieRing L] [LieAlgebra K L]
variable {M : Type*} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]

/-- The endomorphisms of `M` carrying `M` into `N` and acting on `N` by a scalar. It is a Lie
submodule of `M →ₗ[K] M` because bracketing with an element of `L` kills `N`. -/
private def homScalarOn (N : LieSubmodule K L M) : LieSubmodule K L (M →ₗ[K] M) where
  carrier := {φ | (∀ m, φ m ∈ N) ∧ ∃ c : K, ∀ n ∈ N, φ n = c • n}
  zero_mem' := ⟨fun m ↦ by simp, 0, fun n _ ↦ by simp⟩
  add_mem' := by
    rintro φ ψ ⟨hφ, c, hc⟩ ⟨hψ, c', hc'⟩
    exact ⟨fun m ↦ N.add_mem (hφ m) (hψ m), c + c',
      fun n hn ↦ by simp [hc n hn, hc' n hn, add_smul]⟩
  smul_mem' := by
    rintro a φ ⟨hφ, c, hc⟩
    exact ⟨fun m ↦ N.smul_mem a (hφ m), a * c, fun n hn ↦ by simp [hc n hn, mul_smul]⟩
  lie_mem := by
    rintro x φ ⟨hφ, c, hc⟩
    refine ⟨fun m ↦ ?_, 0, fun n hn ↦ ?_⟩
    · rw [LieHom.lie_apply]
      exact N.sub_mem (N.lie_mem (hφ m)) (hφ _)
    · rw [LieHom.lie_apply, hc n hn, hc _ (N.lie_mem hn), lie_smul, sub_self, zero_smul]

/-- The endomorphisms of `M` carrying `M` into `N` and killing `N`, a Lie submodule of
`TauCeti.homScalarOn` that misses every projection onto a nonzero `N`. -/
private def homVanishOn (N : LieSubmodule K L M) : LieSubmodule K L (M →ₗ[K] M) where
  carrier := {φ | (∀ m, φ m ∈ N) ∧ ∀ n ∈ N, φ n = 0}
  zero_mem' := ⟨fun m ↦ by simp, fun n _ ↦ by simp⟩
  add_mem' := by
    rintro φ ψ ⟨hφ, hc⟩ ⟨hψ, hc'⟩
    exact ⟨fun m ↦ N.add_mem (hφ m) (hψ m), fun n hn ↦ by simp [hc n hn, hc' n hn]⟩
  smul_mem' := by
    rintro a φ ⟨hφ, hc⟩
    exact ⟨fun m ↦ N.smul_mem a (hφ m), fun n hn ↦ by simp [hc n hn]⟩
  lie_mem := by
    rintro x φ ⟨hφ, hc⟩
    refine ⟨fun m ↦ ?_, fun n hn ↦ ?_⟩
    · rw [LieHom.lie_apply]
      exact N.sub_mem (N.lie_mem (hφ m)) (hφ _)
    · rw [LieHom.lie_apply, hc n hn, hc _ (N.lie_mem hn), lie_zero, sub_zero]

private theorem mem_homScalarOn {N : LieSubmodule K L M} {φ : M →ₗ[K] M} :
    φ ∈ homScalarOn N ↔ (∀ m, φ m ∈ N) ∧ ∃ c : K, ∀ n ∈ N, φ n = c • n := Iff.rfl

private theorem mem_homVanishOn {N : LieSubmodule K L M} {φ : M →ₗ[K] M} :
    φ ∈ homVanishOn N ↔ (∀ m, φ m ∈ N) ∧ ∀ n ∈ N, φ n = 0 := Iff.rfl

end Hom

section Compl

variable {K : Type*} [Field K] [CharZero K] [IsAlgClosed K]
variable {L : Type*} [LieRing L] [LieAlgebra K L]
variable {M : Type v} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
variable {h e f : L} {t : IsSl2Triple h e f}

/-- **A nonzero Lie submodule admits an `L`-equivariant projection onto it.** For `L` generated by
an `sl₂` triple and `M` finite-dimensional, there is a linear endomorphism of `M` taking values in
`N`, restricting to the identity on `N`, and commuting with the action of `L`. -/
private theorem exists_equivariant_projection (htop : t.toLieSubalgebra K = ⊤)
    [FiniteDimensional K M] {N : LieSubmodule K L M} (hNbot : N ≠ ⊥) :
    ∃ ψ : M →ₗ[K] M, (∀ m, ψ m ∈ N) ∧ (∀ n ∈ N, ψ n = n) ∧
      ∀ (x : L) (m : M), ψ ⁅x, m⁆ = ⁅x, ψ m⁆ := by
  -- Run step one inside `M →ₗ[K] M`: a linear projection onto `N` acts on `N` by the scalar `1`
  -- but does not vanish on `N`, so `homVanishOn N` is proper inside `homScalarOn N`. Step one
  -- returns an invariant element outside it; invariance is equivariance, and it acts on `N` by a
  -- nonzero scalar, so rescaling turns it into a projection.
  obtain ⟨n₀, hn₀, hn₀0⟩ : ∃ n : M, n ∈ N ∧ n ≠ 0 := by
    by_contra hcon
    push Not at hcon
    exact hNbot ((LieSubmodule.eq_bot_iff _).2 hcon)
  -- A linear projection of `M` onto `N`, not yet equivariant.
  obtain ⟨π, hπmem, hπid⟩ : ∃ π : M →ₗ[K] M, (∀ m, π m ∈ N) ∧ ∀ n ∈ N, π n = n := by
    obtain ⟨Q, hQ⟩ := Submodule.exists_isCompl (N : Submodule K M)
    exact ⟨(N : Submodule K M).projection Q hQ, fun m ↦ Submodule.projection_apply_mem hQ m,
      fun n hn ↦ Submodule.projection_apply_of_mem_left hQ hn⟩
  have hπscal : π ∈ homScalarOn N :=
    mem_homScalarOn.2 ⟨hπmem, 1, fun n hn ↦ by rw [hπid n hn, one_smul]⟩
  have hproper : (homVanishOn N).comap (homScalarOn N).incl ≠ ⊤ := by
    rw [Ne, LieSubmodule.comap_incl_eq_top]
    intro hcon
    exact hn₀0 ((hπid n₀ hn₀).symm.trans ((mem_homVanishOn.1 (hcon hπscal)).2 n₀ hn₀))
  obtain ⟨φ, hφmem, hφinv⟩ :=
    exists_invariant_notMem (t := t) htop ((homVanishOn N).comap (homScalarOn N).incl) hproper
      (fun x ψ ↦ by
        obtain ⟨hψ, c, hc⟩ := mem_homScalarOn.1 ψ.2
        simp only [LieSubmodule.mem_comap, LieSubmodule.incl_apply, LieSubmodule.coe_bracket]
        refine mem_homVanishOn.2 ⟨fun m ↦ ?_, fun n hn ↦ ?_⟩
        · rw [LieHom.lie_apply]
          exact N.sub_mem (N.lie_mem (hψ m)) (hψ _)
        · rw [LieHom.lie_apply, hc n hn, hc _ (N.lie_mem hn), lie_smul, sub_self])
  rw [LieSubmodule.mem_comap, LieSubmodule.incl_apply] at hφmem
  obtain ⟨hφN, c, hc⟩ := mem_homScalarOn.1 φ.2
  have hc0 : c ≠ 0 := by
    rintro rfl
    exact hφmem (mem_homVanishOn.2 ⟨hφN, fun n hn ↦ by rw [hc n hn, zero_smul]⟩)
  refine ⟨c⁻¹ • (φ : M →ₗ[K] M), fun m ↦ N.smul_mem _ (hφN m), fun n hn ↦ ?_, fun x m ↦ ?_⟩
  · simp [hc n hn, smul_smul, inv_mul_cancel₀ hc0]
  · have hzero : ⁅x, (φ : M →ₗ[K] M)⁆ = 0 := by
      rw [← LieSubmodule.coe_bracket, hφinv x]
      rfl
    have happ := congrArg (fun g : M →ₗ[K] M ↦ g m) hzero
    simp only [LieHom.lie_apply, LinearMap.zero_apply, sub_eq_zero] at happ
    simp [← happ]

/-- **A Lie submodule admitting an equivariant projection is a direct summand.** If an
`L`-equivariant linear endomorphism of `M` takes values in `N` and restricts to the identity on `N`,
then `N` has a complement, namely the kernel of that endomorphism. -/
private theorem exists_isCompl_of_equivariant_projection {R : Type*} {L' M' : Type*} [CommRing R]
    [LieRing L'] [LieAlgebra R L'] [AddCommGroup M'] [Module R M'] [LieRingModule L' M']
    [LieModule R L' M'] {N : LieSubmodule R L' M'} {ψ : M' →ₗ[R] M'}
    (hψmem : ∀ m, ψ m ∈ N) (hψid : ∀ n ∈ N, ψ n = n)
    (hψlie : ∀ (x : L') (m : M'), ψ ⁅x, m⁆ = ⁅x, ψ m⁆) :
    ∃ N' : LieSubmodule R L' M', IsCompl N N' := by
  -- `ψ` corestricted to `N` is a Lie module hom, and a projection in Mathlib's sense.
  let g : M' →ₗ⁅R,L'⁆ M' := { __ := ψ, map_lie' := fun {x m} ↦ hψlie x m }
  let f : M' →ₗ⁅R,L'⁆ N := LieModuleHom.codRestrict N g hψmem
  refine ⟨f.ker, ?_⟩
  rw [← LieSubmodule.isCompl_toSubmodule, LieModuleHom.ker_toSubmodule]
  exact LinearMap.isCompl_of_proj fun n ↦ Subtype.ext (hψid n n.2)

/-- **Complete reducibility for `sl₂`.** Over an algebraically closed field of characteristic zero,
every Lie submodule of a finite-dimensional module over a Lie algebra generated by an `sl₂` triple
has a complement, so the module is a direct sum of irreducibles.

Combined with the classification of the irreducibles
(`TauCeti.Sl2Std.existsUnique_nonempty_lieModuleEquiv`), every such module is `⨁ V(nᵢ)`. -/
theorem exists_isCompl_of_toLieSubalgebra_eq_top (htop : t.toLieSubalgebra K = ⊤)
    [FiniteDimensional K M]
    (N : LieSubmodule K L M) : ∃ N' : LieSubmodule K L M, IsCompl N N' := by
  rcases eq_or_ne N ⊥ with rfl | hNbot
  · exact ⟨⊤, isCompl_bot_top⟩
  obtain ⟨ψ, hψmem, hψid, hψlie⟩ := exists_equivariant_projection htop hNbot
  exact exists_isCompl_of_equivariant_projection hψmem hψid hψlie

/-- **Complete reducibility for the model `sl₂`.** Over an algebraically closed field of
characteristic zero, every Lie submodule of a finite-dimensional module over
`LieAlgebra.SpecialLinear.sl (Fin 2) K` has a complement. This is
`TauCeti.exists_isCompl_of_toLieSubalgebra_eq_top` for the standard triple, which generates
`sl (Fin 2) K` by
`TauCeti.toLieSubalgebra_isSl2Triple_single_eq_top`. -/
theorem exists_isCompl_sl_fin_two {K : Type*} [Field K] [CharZero K] [IsAlgClosed K]
    {M : Type v} [AddCommGroup M] [Module K M]
    [LieRingModule (LieAlgebra.SpecialLinear.sl (Fin 2) K) M]
    [LieModule K (LieAlgebra.SpecialLinear.sl (Fin 2) K) M] [FiniteDimensional K M]
    (N : LieSubmodule K (LieAlgebra.SpecialLinear.sl (Fin 2) K) M) :
    ∃ N' : LieSubmodule K (LieAlgebra.SpecialLinear.sl (Fin 2) K) M, IsCompl N N' :=
  exists_isCompl_of_toLieSubalgebra_eq_top
    (t := isSl2Triple_single (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1))
    (toLieSubalgebra_isSl2Triple_single_eq_top (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1)) N

end Compl

end TauCeti
