/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.Algebra.Lie.Semisimple.Defs
public import Mathlib.Algebra.Lie.Sl2

/-!
# The weight string of a primitive vector for an `sl₂` triple

Fix an `sl₂` triple `t : IsSl2Triple h e f` in a Lie algebra `L` over a commutative ring `K`, and a
primitive vector `m` of weight `μ` in an `L`-module `M`. Mathlib supplies the ladder calculus for
the vectors `fⁱ • m`: their `h`-eigenvalues (`lie_h_pow_toEnd_f`), the effect of the
raising operator (`lie_e_pow_succ_toEnd_f`), the integrality `μ = n` of the weight of a primitive
vector of a Noetherian torsion-free module (`exists_nat`), and the two endpoint statements
`pow_toEnd_f_ne_zero_of_eq_nat` and `pow_toEnd_f_eq_zero_of_eq_nat` saying that the string
`m, f • m, …, fⁿ • m` consists of nonzero vectors and stops immediately afterwards.

What Mathlib does not do is assemble those vectors into a submodule. This file does: their span is
a Lie submodule for the subalgebra `t.toLieSubalgebra K` generated by the triple
(`TauCeti.weightStringSubmodule`), because each of `e`, `f` and `h` carries a string vector to a
multiple of a string vector. The string vectors lie in distinct `h`-eigenspaces, so they are
linearly independent; as soon as `M` is irreducible over that subalgebra the string is therefore a
basis, and `M` is the standard `(n+1)`-dimensional irreducible `V(n)`. The span is a Lie submodule
over any commutative coefficient ring. Over a domain of characteristic zero the string of a
torsion-free module is linearly independent; the end of the string, the ladder basis, and the
dimension and classification read off from that basis ask in addition, exactly as Mathlib's
endpoint statements do, that the module be Noetherian — for the classification, both modules.

Irreducibility over `t.toLieSubalgebra K` — not over the ambient `L` — is the correct hypothesis:
the adjoint module of `sl₃` is irreducible over `sl₃` and contains a primitive vector of weight `1`
for the `sl₂` triple of a simple root, yet has dimension `8`, not `2`. The two hypotheses agree
when `t.toLieSubalgebra K = ⊤`, which `TauCeti.toLieSubalgebra_isSl2Triple_single_eq_top`
verifies for the standard triple of `sl (Fin 2) K`.

## Main definitions

* `TauCeti.weightStringSubmodule`: the span of the weight string `m, f • m, f² • m, …` of a
  primitive vector, as a Lie submodule for the subalgebra generated by the triple.
* `TauCeti.lieModuleEquivOfHasPrimitiveVectorWith`: **the classification.** Two modules irreducible
  over the subalgebra of the triple with primitive vectors of the same weight are equivalent over
  that subalgebra, so `V(n)` is determined by `n`. Underlying it is the linear equivalence matching
  the two ladder bases position by position.

## Main results

* `TauCeti.pow_toEnd_f_eq_zero_of_lt`: the string of a primitive vector of weight `n : ℕ` stops
  after `n` steps, not merely at step `n + 1`.
* `TauCeti.linearIndependent_pow_toEnd_f`: the `n + 1` vectors of the string are linearly
  independent, being eigenvectors of `h` for the distinct eigenvalues `n, n - 2, …, -n`.
* `TauCeti.weightStringSubmodule_eq_top`: a primitive vector of an irreducible module generates it.
* `TauCeti.basisOfHasPrimitiveVectorWith`: the resulting ladder basis of an irreducible module,
  with the action of the triple on it read off in `TauCeti.lie_h_basisOfHasPrimitiveVectorWith`,
  `TauCeti.lie_f_basisOfHasPrimitiveVectorWith` and
  `TauCeti.lie_e_basisOfHasPrimitiveVectorWith`.
* `TauCeti.finrank_eq_of_hasPrimitiveVectorWith`: **the dimension of `V(n)`.** A Noetherian module
  irreducible over the subalgebra of the triple, with a primitive vector of weight `n`, has rank
  `n + 1`.

## References

This is Layer 0 of `TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`, whose
`sl2_finrank_of_hasPrimitiveVector` is `TauCeti.finrank_eq_of_hasPrimitiveVectorWith`.

* [J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*][humphreys1972],
  §7.2.
-/

public section

namespace TauCeti

open LieModule Module

section CommRing

variable {K : Type*} [CommRing K]
variable {L : Type*} [LieRing L] [LieAlgebra K L]
variable {M : Type*} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
variable {h e f : L} {t : IsSl2Triple h e f} {m : M} {μ : K}

/-! ### The weight string as a Lie submodule -/

/-- The span of the weight string `m, f • m, f² • m, …` of a primitive vector `m`, as a Lie
submodule for the subalgebra `t.toLieSubalgebra K` generated by the triple. Each of the three
generators of that subalgebra carries a string vector to a multiple of a string vector, so the span
is invariant; it is *not* in general invariant under the ambient Lie algebra `L`. -/
def weightStringSubmodule (P : t.HasPrimitiveVectorWith m μ) :
    LieSubmodule K (t.toLieSubalgebra K) M where
  __ := Submodule.span K (Set.range fun i : ℕ ↦ (toEnd K L M f ^ i) m)
  lie_mem := by
    set S := Submodule.span K (Set.range fun i : ℕ ↦ (toEnd K L M f ^ i) m)
    have hmem : ∀ i : ℕ, (toEnd K L M f ^ i) m ∈ S := fun i ↦ Submodule.subset_span ⟨i, rfl⟩
    -- Invariance of the span reduces to invariance of the generating string.
    have key : ∀ z : L, (∀ i : ℕ, ⁅z, (toEnd K L M f ^ i) m⁆ ∈ S) → ∀ y ∈ S, ⁅z, y⁆ ∈ S := by
      intro z hz y hy
      have hle : S ≤ S.comap (toEnd K L M z) :=
        Submodule.span_le.2 (Set.range_subset_iff.2 fun i ↦ by simpa using hz i)
      exact hle hy
    have he : ∀ i : ℕ, ⁅e, (toEnd K L M f ^ i) m⁆ ∈ S := by
      rintro (_ | i)
      · rw [pow_zero, Module.End.one_apply, P.lie_e]
        exact Submodule.zero_mem _
      · rw [P.lie_e_pow_succ_toEnd_f]
        exact Submodule.smul_mem _ _ (hmem i)
    have hf : ∀ i : ℕ, ⁅f, (toEnd K L M f ^ i) m⁆ ∈ S := by
      intro i
      rw [P.lie_f_pow_toEnd_f]
      exact hmem (i + 1)
    have hh : ∀ i : ℕ, ⁅h, (toEnd K L M f ^ i) m⁆ ∈ S := by
      intro i
      rw [P.lie_h_pow_toEnd_f]
      exact Submodule.smul_mem _ _ (hmem i)
    rintro ⟨x, hx⟩ y hy
    obtain ⟨c₁, c₂, c₃, rfl⟩ := IsSl2Triple.mem_toLieSubalgebra_iff.1 hx
    refine key _ (fun i ↦ ?_) y hy
    rw [add_lie, add_lie, smul_lie, smul_lie, smul_lie, t.lie_e_f]
    exact Submodule.add_mem _ (Submodule.add_mem _ (Submodule.smul_mem _ _ (he i))
      (Submodule.smul_mem _ _ (hf i))) (Submodule.smul_mem _ _ (hh i))

/-- The underlying submodule of the weight string is the span of the string.

This is the abstraction boundary: importing modules should reason through this lemma rather than
unfold `weightStringSubmodule`, which is why the definition is not `@[expose]`. -/
@[simp]
theorem weightStringSubmodule_toSubmodule (P : t.HasPrimitiveVectorWith m μ) :
    (weightStringSubmodule P).toSubmodule =
      Submodule.span K (Set.range fun i : ℕ ↦ (toEnd K L M f ^ i) m) := by
  simp only [weightStringSubmodule]

theorem pow_toEnd_f_mem_weightStringSubmodule (P : t.HasPrimitiveVectorWith m μ) (i : ℕ) :
    (toEnd K L M f ^ i) m ∈ weightStringSubmodule P := by
  rw [← LieSubmodule.mem_toSubmodule, weightStringSubmodule_toSubmodule]
  exact Submodule.subset_span ⟨i, rfl⟩

theorem mem_weightStringSubmodule (P : t.HasPrimitiveVectorWith m μ) :
    m ∈ weightStringSubmodule P := by
  simpa using pow_toEnd_f_mem_weightStringSubmodule P 0

/-- The weight string submodule is nontrivial, the primitive vector `m` witnessing it: `m` lies in
the string and is nonzero. This is what lets irreducibility hypotheses be applied to the weight
string. -/
instance (P : t.HasPrimitiveVectorWith m μ) : Nontrivial (weightStringSubmodule P) :=
  ⟨⟨m, mem_weightStringSubmodule P⟩, 0, by simpa using P.ne_zero⟩

/-- A primitive vector of an irreducible module generates it: its weight string spans. -/
theorem weightStringSubmodule_eq_top [LieModule.IsIrreducible K (t.toLieSubalgebra K) M]
    (P : t.HasPrimitiveVectorWith m μ) : weightStringSubmodule P = ⊤ :=
  LieSubmodule.eq_top_of_isIrreducible _ _ _ _

end CommRing

section Domain

variable {K : Type*} [CommRing K] [IsDomain K] [CharZero K]
variable {L : Type*} [LieRing L] [LieAlgebra K L]
variable {M : Type*} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
variable [IsTorsionFree K M]
variable {h e f : L} {t : IsSl2Triple h e f} {m : M} {n : ℕ}

/-! ### The end of the string -/

/-- The weight string of a primitive vector of weight `n : ℕ` has length `n + 1`: lowering past
step `n` gives zero. Mathlib's
`IsSl2Triple.HasPrimitiveVectorWith.pow_toEnd_f_eq_zero_of_eq_nat` is the first such step. -/
theorem pow_toEnd_f_eq_zero_of_lt [IsNoetherian K M] (P : t.HasPrimitiveVectorWith m (n : K))
    {i : ℕ} (hi : n < i) : (toEnd K L M f ^ i) m = 0 :=
  Module.End.pow_map_zero_of_le hi (P.pow_toEnd_f_eq_zero_of_eq_nat rfl)

/-! ### Linear independence of the string -/

/-- The `n + 1` vectors of the weight string of a primitive vector of weight `n` are linearly
independent: `fⁱ • m` is a nonzero eigenvector of `h` for the eigenvalue `n - 2i`, and these
eigenvalues are distinct. -/
theorem linearIndependent_pow_toEnd_f (P : t.HasPrimitiveVectorWith m (n : K)) :
    LinearIndependent K fun i : Fin (n + 1) ↦ (toEnd K L M f ^ (i : ℕ)) m := by
  refine (toEnd K L M h).eigenvectors_linearIndependent'
    (fun i : Fin (n + 1) ↦ (n : K) - 2 * (i : ℕ)) (fun i j hij ↦ ?_) _ (fun i ↦ ⟨?_, ?_⟩)
  · have hcast : ((i : ℕ) : K) = ((j : ℕ) : K) :=
      mul_left_cancel₀ (two_ne_zero (α := K)) (by linear_combination -hij)
    exact Fin.ext (Nat.cast_injective hcast)
  · rw [Module.End.mem_eigenspace_iff, toEnd_apply_apply]
    exact P.lie_h_pow_toEnd_f i
  · exact P.pow_toEnd_f_ne_zero_of_eq_nat rfl (Nat.lt_succ_iff.1 i.isLt)

/-! ### The ladder basis and the dimension of `V(n)` -/

/-- The weight string of a primitive vector of weight `n` in an irreducible module spans it, as a
family indexed by the `n + 1` positions of the string. -/
theorem span_range_pow_toEnd_f_eq_top [IsNoetherian K M]
    [LieModule.IsIrreducible K (t.toLieSubalgebra K) M]
    (P : t.HasPrimitiveVectorWith m (n : K)) :
    Submodule.span K (Set.range fun i : Fin (n + 1) ↦ (toEnd K L M f ^ (i : ℕ)) m) = ⊤ := by
  have hspan : Submodule.span K (Set.range fun i : ℕ ↦ (toEnd K L M f ^ i) m) =
      Submodule.span K (Set.range fun i : Fin (n + 1) ↦ (toEnd K L M f ^ (i : ℕ)) m) := by
    refine le_antisymm (Submodule.span_le.2 ?_) (Submodule.span_le.2 ?_)
    · rintro _ ⟨i, rfl⟩
      rcases le_or_gt i n with hi | hi
      · exact Submodule.subset_span ⟨⟨i, by omega⟩, rfl⟩
      · have hzero : (toEnd K L M f ^ i) m = 0 := pow_toEnd_f_eq_zero_of_lt P hi
        simp [hzero]
    · rintro _ ⟨i, rfl⟩
      exact Submodule.subset_span ⟨(i : ℕ), rfl⟩
  rw [← hspan, ← weightStringSubmodule_toSubmodule P, weightStringSubmodule_eq_top P]
  simp

/-- **The ladder basis.** A module irreducible over the subalgebra of an `sl₂` triple, with a
primitive vector `m` of weight `n : ℕ`, has the weight string `m, f • m, …, fⁿ • m` as a basis. -/
noncomputable def basisOfHasPrimitiveVectorWith [IsNoetherian K M]
    [LieModule.IsIrreducible K (t.toLieSubalgebra K) M]
    (P : t.HasPrimitiveVectorWith m (n : K)) : Basis (Fin (n + 1)) K M :=
  Basis.mk (linearIndependent_pow_toEnd_f P) (span_range_pow_toEnd_f_eq_top P).ge

variable [IsNoetherian K M] [LieModule.IsIrreducible K (t.toLieSubalgebra K) M]

@[simp]
theorem basisOfHasPrimitiveVectorWith_apply (P : t.HasPrimitiveVectorWith m (n : K))
    (i : Fin (n + 1)) :
    basisOfHasPrimitiveVectorWith P i = (toEnd K L M f ^ (i : ℕ)) m :=
  Basis.mk_apply _ _ _

theorem basisOfHasPrimitiveVectorWith_zero (P : t.HasPrimitiveVectorWith m (n : K)) :
    basisOfHasPrimitiveVectorWith P 0 = m := by
  simp

/-- **The dimension of `V(n)`.** A Noetherian module irreducible over the subalgebra of an `sl₂`
triple, carrying a primitive vector of weight `n`, has rank `n + 1`. -/
theorem finrank_eq_of_hasPrimitiveVectorWith (P : t.HasPrimitiveVectorWith m (n : K)) :
    finrank K M = n + 1 := by
  rw [finrank_eq_card_basis (basisOfHasPrimitiveVectorWith P), Fintype.card_fin]

/-- On the ladder basis, `h` acts diagonally with the eigenvalues `n, n - 2, …, -n`. -/
theorem lie_h_basisOfHasPrimitiveVectorWith (P : t.HasPrimitiveVectorWith m (n : K))
    (i : Fin (n + 1)) :
    ⁅h, basisOfHasPrimitiveVectorWith P i⁆ =
      ((n : K) - 2 * (i : ℕ)) • basisOfHasPrimitiveVectorWith P i := by
  simpa using P.lie_h_pow_toEnd_f (i : ℕ)

/-- On the ladder basis, `f` is the lowering operator, moving one step down the string. -/
theorem lie_f_basisOfHasPrimitiveVectorWith (P : t.HasPrimitiveVectorWith m (n : K))
    (i : Fin (n + 1)) (hi : (i : ℕ) + 1 < n + 1) :
    ⁅f, basisOfHasPrimitiveVectorWith P i⁆ =
      basisOfHasPrimitiveVectorWith P ⟨(i : ℕ) + 1, hi⟩ := by
  simpa using P.lie_f_pow_toEnd_f (i : ℕ)

/-- The lowering operator kills the bottom of the ladder basis. -/
theorem lie_f_basisOfHasPrimitiveVectorWith_last (P : t.HasPrimitiveVectorWith m (n : K)) :
    ⁅f, basisOfHasPrimitiveVectorWith P (Fin.last n)⁆ = 0 := by
  rw [basisOfHasPrimitiveVectorWith_apply, P.lie_f_pow_toEnd_f]
  exact pow_toEnd_f_eq_zero_of_lt P (by simp)

/-- On the ladder basis, `e` is the raising operator, moving one step up the string with the
Casimir-type coefficient `(i + 1)(n - i)`. -/
theorem lie_e_basisOfHasPrimitiveVectorWith (P : t.HasPrimitiveVectorWith m (n : K))
    (i : Fin (n + 1)) (hi : (i : ℕ) + 1 < n + 1) :
    ⁅e, basisOfHasPrimitiveVectorWith P ⟨(i : ℕ) + 1, hi⟩⁆ =
      (((i : ℕ) + 1) * ((n : K) - (i : ℕ))) • basisOfHasPrimitiveVectorWith P i := by
  simpa using P.lie_e_pow_succ_toEnd_f (i : ℕ)

/-- The raising operator kills the primitive vector at the top of the ladder basis. -/
theorem lie_e_basisOfHasPrimitiveVectorWith_zero (P : t.HasPrimitiveVectorWith m (n : K)) :
    ⁅e, basisOfHasPrimitiveVectorWith P 0⁆ = 0 := by
  rw [basisOfHasPrimitiveVectorWith_zero]
  exact P.lie_e

/-! ### The classification: the highest weight determines the module -/

section Classification

variable {M' : Type*} [AddCommGroup M'] [Module K M'] [LieRingModule L M'] [LieModule K L M']
  {m' : M'} [IsTorsionFree K M'] [IsNoetherian K M']
  [LieModule.IsIrreducible K (t.toLieSubalgebra K) M']

/-- The linear equivalence matching the two ladder bases position by position. This is an
implementation detail of the classifying equivalence
`TauCeti.lieModuleEquivOfHasPrimitiveVectorWith`, split off from it only so that its action on the
whole weight string is available both while the intertwining property is being proved and
afterwards; consumers use the Lie module equivalence, whose underlying linear equivalence this
is. -/
private noncomputable def linearEquivOfHasPrimitiveVectorWith
    (P : t.HasPrimitiveVectorWith m (n : K)) (P' : t.HasPrimitiveVectorWith m' (n : K)) :
    M ≃ₗ[K] M' :=
  (basisOfHasPrimitiveVectorWith P).equiv (basisOfHasPrimitiveVectorWith P')
    (Equiv.refl (Fin (n + 1)))

/-- The matching of the two ladder bases carries the weight string to the weight string, position
by position and past the end of the string too. The public form of this is
`TauCeti.lieModuleEquivOfHasPrimitiveVectorWith_apply_pow_toEnd_f`. -/
private theorem linearEquivOfHasPrimitiveVectorWith_apply_pow_toEnd_f
    (P : t.HasPrimitiveVectorWith m (n : K)) (P' : t.HasPrimitiveVectorWith m' (n : K)) (i : ℕ) :
    linearEquivOfHasPrimitiveVectorWith P P' ((toEnd K L M f ^ i) m) =
      (toEnd K L M' f ^ i) m' := by
  rcases le_or_gt i n with hi | hi
  · simpa [linearEquivOfHasPrimitiveVectorWith] using
      Basis.equiv_apply (basisOfHasPrimitiveVectorWith P) ⟨i, by omega⟩
        (basisOfHasPrimitiveVectorWith P') (Equiv.refl (Fin (n + 1)))
  · rw [pow_toEnd_f_eq_zero_of_lt P hi, pow_toEnd_f_eq_zero_of_lt P' hi, map_zero]

/-- **The highest weight determines the irreducible.** Two modules irreducible over the subalgebra
of an `sl₂` triple, each carrying a primitive vector of the same weight `n`, are equivalent as
modules over that subalgebra: the linear equivalence matching the two ladder bases position by
position intertwines the action of the triple, because the ladder relations depend only on `n`.

The conclusion is an equivalence over `t.toLieSubalgebra K`, not over the ambient `L`; outside the
subalgebra the two actions have nothing to do with one another. -/
noncomputable def lieModuleEquivOfHasPrimitiveVectorWith
    (P : t.HasPrimitiveVectorWith m (n : K)) (P' : t.HasPrimitiveVectorWith m' (n : K)) :
    M ≃ₗ⁅K, t.toLieSubalgebra K⁆ M' :=
  { linearEquivOfHasPrimitiveVectorWith P P' with
    map_lie' := by
      set φ := linearEquivOfHasPrimitiveVectorWith P P'
      -- The equivalence matches the two weight strings position by position, past the end too.
      have hψ : ∀ i : ℕ, φ ((toEnd K L M f ^ i) m) = (toEnd K L M' f ^ i) m' :=
        linearEquivOfHasPrimitiveVectorWith_apply_pow_toEnd_f P P'
      -- Intertwining a single element of `L` may be checked on the spanning weight string.
      have hspan : Submodule.span K (Set.range fun i : ℕ ↦ (toEnd K L M f ^ i) m) = ⊤ := by
        rw [← weightStringSubmodule_toSubmodule P, weightStringSubmodule_eq_top P]
        simp
      have key : ∀ z : L, (∀ i : ℕ, φ ⁅z, (toEnd K L M f ^ i) m⁆ = ⁅z, (toEnd K L M' f ^ i) m'⁆) →
          ∀ w : M, φ ⁅z, w⁆ = ⁅z, φ w⁆ := by
        intro z hz w
        have := LinearMap.ext_on_range (f := (φ : M →ₗ[K] M') ∘ₗ toEnd K L M z)
          (g := toEnd K L M' z ∘ₗ (φ : M →ₗ[K] M')) hspan
          (fun i ↦ by simpa [hψ i] using hz i)
        simpa using DFunLike.congr_fun this w
      have hf : ∀ w : M, φ ⁅f, w⁆ = ⁅f, φ w⁆ :=
        key f fun i ↦ by rw [P.lie_f_pow_toEnd_f, P'.lie_f_pow_toEnd_f, hψ]
      have hh : ∀ w : M, φ ⁅h, w⁆ = ⁅h, φ w⁆ :=
        key h fun i ↦ by rw [P.lie_h_pow_toEnd_f, P'.lie_h_pow_toEnd_f, map_smul, hψ]
      have he : ∀ w : M, φ ⁅e, w⁆ = ⁅e, φ w⁆ := by
        refine key e fun i ↦ ?_
        rcases i with _ | i
        · rw [pow_zero, Module.End.one_apply, pow_zero, Module.End.one_apply, P.lie_e, P'.lie_e,
            map_zero]
        · rw [P.lie_e_pow_succ_toEnd_f, P'.lie_e_pow_succ_toEnd_f, map_smul, hψ]
      intro x y
      obtain ⟨c₁, c₂, c₃, hx⟩ := IsSl2Triple.mem_toLieSubalgebra_iff.1 x.2
      -- The action of the subalgebra is the ambient action of the underlying element of `L`,
      -- which is a linear combination of `e`, `f` and `h`.
      -- The `map_lie'` goal is phrased with the anonymous constructor's `toFun`, which is the
      -- coercion of the `with`-clause `LinearEquiv`; that is `φ` only up to unfolding the bundled
      -- structure, so no rewrite reaches it and `change` is needed to name `φ` before rewriting.
      change φ ⁅x, y⁆ = ⁅x, φ y⁆
      rw [LieSubalgebra.coe_bracket_of_module, LieSubalgebra.coe_bracket_of_module, hx, t.lie_e_f]
      simp only [add_lie, smul_lie, map_add, map_smul, he, hf, hh] }

/-- The classifying equivalence carries the ladder basis to the ladder basis. -/
theorem lieModuleEquivOfHasPrimitiveVectorWith_apply_basis (P : t.HasPrimitiveVectorWith m (n : K))
    (P' : t.HasPrimitiveVectorWith m' (n : K)) (i : Fin (n + 1)) :
    lieModuleEquivOfHasPrimitiveVectorWith P P' (basisOfHasPrimitiveVectorWith P i) =
      basisOfHasPrimitiveVectorWith P' i :=
  Basis.equiv_apply _ _ _ _

/-- The classifying equivalence carries the weight string to the weight string, position by
position and past the end of the string too. -/
@[simp]
theorem lieModuleEquivOfHasPrimitiveVectorWith_apply_pow_toEnd_f
    (P : t.HasPrimitiveVectorWith m (n : K)) (P' : t.HasPrimitiveVectorWith m' (n : K)) (i : ℕ) :
    lieModuleEquivOfHasPrimitiveVectorWith P P' ((toEnd K L M f ^ i) m) =
      (toEnd K L M' f ^ i) m' :=
  linearEquivOfHasPrimitiveVectorWith_apply_pow_toEnd_f P P' i

end Classification

end Domain

end TauCeti
