/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Mathlib.Algebra.Lie.Ideal
public import Mathlib.LinearAlgebra.Dimension.Finrank
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Quotient.Kernel.Basic
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Tangent

/-!
# The Lie algebra of the kernel of an affine group morphism

For a morphism `f : H ⟶ K` of commutative Hopf algebras, the induced morphism of affine group
schemes runs from `Spec K` to `Spec H`. Its scheme-theoretic kernel has coordinate ring
`K ⧸ kernelHopfIdeal f`, where `kernelHopfIdeal f` is generated by the image in `K` of the
augmentation ideal of `H`.

This file proves that the Lie algebra of this kernel is canonically the kernel of the differential
of `f`. The key algebraic step says that a counit-valued derivation of `K` vanishes on the ideal
generated by the image of the augmentation ideal exactly when its precomposition with `f` is zero.
Combining this with the closed-subgroup tangent equivalence gives the expected Lie equivalence and
the corresponding dimension identity.

This is the coordinate-Hopf-algebra form of the kernel part of the ReductiveGroups roadmap's
Layer 2 target on dimension tools through `Lie(G)`.

## Main declarations

* `TauCeti.CommHopfAlgCat.derivationComp_eq_zero_iff_vanishes_kernelHopfIdeal`: the differential
  vanishes exactly on derivations annihilating the kernel Hopf ideal.
* `TauCeti.CommHopfAlgCat.lieSubalgebra_kernelHopfIdeal`: the closed-subgroup Lie algebra cut out by
  the kernel Hopf ideal is the kernel of the differential.
* `TauCeti.CommHopfAlgCat.kernelLieEquiv`: the Lie algebra of the scheme-theoretic kernel is
  canonically Lie-equivalent to the kernel of the differential.
* `TauCeti.CommHopfAlgCat.finrank_kernelLie`: the resulting equality of Lie algebra dimensions over
  a field.

## References

J. S. Milne, *Algebraic Groups* (2017), §10.a, identifies tangent spaces with counit-valued
derivations; the kernel calculation is the coordinate form of this functoriality. The coordinate
ring of the kernel used here is Milne's Proposition 4.1.
-/

public section

open CategoryTheory

namespace TauCeti

universe u v w x

namespace CommHopfAlgCat

variable {R : Type u} [CommRing R]
variable {H K : _root_.CommHopfAlgCat.{v} R}
variable {B : Type w} [CommRing B] [Algebra R B]

/-- The ideal on which both the counit and a counit-valued derivation vanish.

The counit condition is what makes the vanishing of the derivation stable under multiplication:
if `ε(x) = 0` and `d(x) = 0`, then the Leibniz rule gives `d(a * x) = 0` for every `a`. This
auxiliary ideal packages the generated-ideal argument in
`derivationComp_eq_zero_iff_vanishes_kernelHopfIdeal`. -/
private def derivationVanishingIdeal
    (d : Derivation R K (Bialgebra.CounitAlgebra R K B)) : Ideal K where
  carrier := {x | Coalgebra.counit (R := R) x = 0 ∧ d x = 0}
  zero_mem' := by simp
  add_mem' := by
    rintro a b ⟨haε, had⟩ ⟨hbε, hbd⟩
    simp [map_add, haε, hbε, had, hbd]
  smul_mem' := by
    rintro a b ⟨hbε, hbd⟩
    constructor
    · -- An ideal's scalar action is multiplication; no rewrite lemma exposes that notation here.
      change Coalgebra.counit (R := R) (a * b) = 0
      simp [hbε]
    · -- Restate the same scalar action so that the derivation's Leibniz lemma applies.
      change d (a * b) = 0
      rw [d.leibniz]
      have hb_smul : b • d a = 0 := by
        rw [Algebra.smul_def, Bialgebra.CounitAlgebra.algebraMap_apply, hbε,
          ← Bialgebra.CounitAlgebra.algebraMap_base R K B 0, map_zero, zero_mul]
      rw [hbd, smul_zero, hb_smul, add_zero]

/-- Membership in the auxiliary vanishing ideal is simultaneous vanishing of the counit and the
derivation. -/
private theorem mem_derivationVanishingIdeal_iff
    (d : Derivation R K (Bialgebra.CounitAlgebra R K B)) (x : K) :
    x ∈ derivationVanishingIdeal d ↔ Coalgebra.counit (R := R) x = 0 ∧ d x = 0 :=
  Iff.rfl

/-- The canonical linear identification of the copies of `B` indexed by `K` and `H`. -/
private noncomputable def counitCoefficientEquiv :
    Bialgebra.CounitAlgebra R K B ≃ₗ[R] Bialgebra.CounitAlgebra R H B :=
  (Bialgebra.CounitAlgebra.algEquivSelf R K B).toLinearEquiv.trans
    (Bialgebra.CounitAlgebra.algEquivSelf R H B).symm.toLinearEquiv

/-- The coefficient identification is the identity after forgetting its Hopf-algebra index. -/
@[simp]
private theorem counitCoefficientEquiv_apply
    (b : Bialgebra.CounitAlgebra R K B) :
    Bialgebra.CounitAlgebra.algEquivSelf R H B (counitCoefficientEquiv b) =
      Bialgebra.CounitAlgebra.algEquivSelf R K B b := by
  -- `counitCoefficientEquiv` is a composition through `B`; unfolding it is the only way to expose
  -- the inverse pair because the private definition has no equation lemma.
  change Bialgebra.CounitAlgebra.algEquivSelf R H B
      ((Bialgebra.CounitAlgebra.algEquivSelf R H B).symm
        (Bialgebra.CounitAlgebra.algEquivSelf R K B b)) =
    Bialgebra.CounitAlgebra.algEquivSelf R K B b
  exact (Bialgebra.CounitAlgebra.algEquivSelf R H B).apply_symm_apply _

/-- The differential value is precomposition, with the coefficient copy made explicit. -/
private theorem derivationComp_apply_eq_counitCoefficientEquiv (f : H ⟶ K)
    (d : Derivation R K (Bialgebra.CounitAlgebra R K B)) (x : H) :
    derivationComp (B := B) f.hom d x = counitCoefficientEquiv (d (f.hom x)) := by
  apply (Bialgebra.CounitAlgebra.algEquivSelf R H B).injective
  rw [counitCoefficientEquiv_apply]
  simp only [derivationComp_apply]
  exact (Bialgebra.CounitAlgebra.algEquivSelf_apply R H B (d (f.hom x))).trans
    (Bialgebra.CounitAlgebra.algEquivSelf_apply R K B (d (f.hom x))).symm

/-- A counit-valued derivation lies in the kernel of the differential exactly when it vanishes on
the kernel Hopf ideal.

The forward implication is the nontrivial one: zero precomposition says that the derivation
vanishes on the image of the augmentation ideal. Those images lie in `derivationVanishingIdeal`,
so the ideal they generate lies there as well. The reverse implication tests on
`x - ε(x)`, whose image belongs to the kernel Hopf ideal and differs from the image of `x` by a
scalar, on which every derivation vanishes. -/
theorem derivationComp_eq_zero_iff_vanishes_kernelHopfIdeal (f : H ⟶ K)
    (d : Derivation R K (Bialgebra.CounitAlgebra R K B)) :
    derivationComp (B := B) f.hom d = 0 ↔
      ∀ x ∈ (kernelHopfIdeal f).toIdeal, d x = 0 := by
  constructor
  · intro hcomp
    have hle : (kernelHopfIdeal f).toIdeal ≤ derivationVanishingIdeal d := by
      rw [kernelHopfIdeal_toIdeal, Ideal.map_le_iff_le_comap]
      intro x hx
      rw [Ideal.mem_comap, mem_derivationVanishingIdeal_iff]
      have hxε : Coalgebra.counit (R := R) x = 0 :=
        (HopfIdeal.mem_augmentation R H).mp (HopfIdeal.mem_toIdeal.mp hx)
      constructor
      · simpa using (CoalgHomClass.counit_comp_apply f.hom x).trans hxε
      · have hvalue := DFunLike.congr_fun hcomp x
        rw [derivationComp_apply_eq_counitCoefficientEquiv] at hvalue
        exact counitCoefficientEquiv.map_eq_zero_iff.mp hvalue
    intro x hx
    exact (mem_derivationVanishingIdeal_iff d x).mp (hle hx) |>.2
  · intro hvanish
    apply Derivation.ext
    intro x
    let y : H := x - algebraMap R H (Coalgebra.counit (R := R) x)
    have hyε : Coalgebra.counit (R := R) y = 0 := by
      simp [y]
    have hyMem : f.hom y ∈ (kernelHopfIdeal f).toIdeal :=
      HopfIdeal.mem_toIdeal.mpr (mem_kernelHopfIdeal_of_mem_augmentation f hyε)
    have hy := hvanish (f.hom y) hyMem
    rw [derivationComp_apply_eq_counitCoefficientEquiv]
    apply counitCoefficientEquiv.map_eq_zero_iff.mpr
    simpa [y, map_sub, AlgHomClass.commutes, Derivation.map_algebraMap] using hy

/-- The Lie subalgebra of `Lie(Spec K)` cut out by the kernel Hopf ideal is exactly the kernel of
the differential `Lie(Spec K) → Lie(Spec H)`. -/
theorem lieSubalgebra_kernelHopfIdeal (f : H ⟶ K) :
    HopfIdeal.lieSubalgebra (B := B) (kernelHopfIdeal f) =
      LieIdeal.toLieSubalgebra R
        (Derivation R K (Bialgebra.CounitAlgebra R K B))
        (LieHom.ker (derivationCompLieHom (B := B) f.hom)) := by
  apply LieSubalgebra.ext _ _
  intro d
  rw [HopfIdeal.mem_lieSubalgebra_iff, LieIdeal.mem_toLieSubalgebra, LieHom.mem_ker,
    derivationCompLieHom_apply]
  exact (derivationComp_eq_zero_iff_vanishes_kernelHopfIdeal f d).symm

/-- The subtype of a Lie ideal and the subtype of its underlying Lie subalgebra are canonically
Lie-equivalent. -/
private def lieIdealSubtypeEquiv
    {L : Type x} [LieRing L] [LieAlgebra R L] (I : LieIdeal R L) :
    LieIdeal.toLieSubalgebra R L I ≃ₗ⁅R⁆ I where
  toFun x := ⟨x, x.property⟩
  invFun x := ⟨x, x.property⟩
  left_inv _ := rfl
  right_inv _ := rfl
  map_add' _ _ := rfl
  map_smul' _ _ := rfl
  map_lie' := by
    intro x y
    apply Subtype.ext
    rfl

/-- The subtype equivalence is the identity on ambient values. -/
@[simp]
private theorem lieIdealSubtypeEquiv_apply_coe
    {L : Type x} [LieRing L] [LieAlgebra R L] (I : LieIdeal R L)
    (z : LieIdeal.toLieSubalgebra R L I) :
    ((lieIdealSubtypeEquiv I z : I) : L) = z :=
  by
    unfold lieIdealSubtypeEquiv
    rfl

/-- The Lie algebra of the scheme-theoretic kernel of `Spec K ⟶ Spec H` is canonically
Lie-equivalent to the kernel of its differential.

The source is the derivation presentation of the Lie algebra of
`Spec (K ⧸ kernelHopfIdeal f)`. The map is induced by precomposition with the quotient map, and its
range is identified with the differential kernel by `lieSubalgebra_kernelHopfIdeal`. -/
noncomputable def kernelLieEquiv (f : H ⟶ K) :
    Derivation R (K ⧸ (kernelHopfIdeal f).toIdeal)
        (Bialgebra.CounitAlgebra R (K ⧸ (kernelHopfIdeal f).toIdeal) B) ≃ₗ⁅R⁆
      LieHom.ker (derivationCompLieHom (B := B) f.hom) :=
  (HopfIdeal.quotientLieEquiv (B := B) (kernelHopfIdeal f)).trans
    ((LieEquiv.ofEq _ _
      (congrArg SetLike.coe (lieSubalgebra_kernelHopfIdeal (B := B) f))).trans
        (lieIdealSubtypeEquiv
          (LieHom.ker (derivationCompLieHom (B := B) f.hom))))

/-- Under `kernelLieEquiv`, a derivation of the kernel coordinate ring is included into the
ambient Lie algebra by precomposition with the quotient map. -/
@[simp]
theorem kernelLieEquiv_apply_coe (f : H ⟶ K)
    (d : Derivation R (K ⧸ (kernelHopfIdeal f).toIdeal)
      (Bialgebra.CounitAlgebra R (K ⧸ (kernelHopfIdeal f).toIdeal) B)) :
    ((kernelLieEquiv (B := B) f d :
        LieHom.ker (derivationCompLieHom (B := B) f.hom)) :
      Derivation R K (Bialgebra.CounitAlgebra R K B)) =
        HopfIdeal.quotientLieHom (B := B) (kernelHopfIdeal f) d := by
  simp only [kernelLieEquiv, LieEquiv.trans_apply]
  rw [lieIdealSubtypeEquiv_apply_coe]
  exact (LieEquiv.ofEq_apply _ _ _ _).trans
    (HopfIdeal.quotientLieEquiv_apply_coe (B := B) (kernelHopfIdeal f) d)

/-- The differential of a group morphism vanishes after the inclusion of its
scheme-theoretic kernel. -/
@[simp]
theorem derivationCompLieHom_comp_quotientLieHom_kernelHopfIdeal_eq_zero (f : H ⟶ K) :
    (derivationCompLieHom (B := B) f.hom).comp
        (HopfIdeal.quotientLieHom (B := B) (kernelHopfIdeal f)) = 0 := by
  apply LieHom.ext
  intro d
  have hd := (kernelLieEquiv (B := B) f d).property
  rw [LieHom.mem_ker, kernelLieEquiv_apply_coe] at hd
  exact hd

section Field

variable {k : Type u} [Field k]
variable {H K : _root_.CommHopfAlgCat.{v} k}

/-- The Lie algebra dimension of a scheme-theoretic kernel is the dimension of the kernel of the
differential. -/
theorem finrank_kernelLie (f : H ⟶ K) :
    Module.finrank k
        (Derivation k (K ⧸ (kernelHopfIdeal f).toIdeal)
          (Bialgebra.CounitAlgebra k (K ⧸ (kernelHopfIdeal f).toIdeal) k)) =
      Module.finrank k (LieHom.ker (derivationCompLieHom (B := k) f.hom)) :=
  (kernelLieEquiv (B := k) f).toLinearEquiv.finrank_eq

end Field

end CommHopfAlgCat

end TauCeti
