/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Analysis.Semigroups.Generator.Basic
public import TauCeti.Analysis.Semigroups.GrowthBound
public import TauCeti.Analysis.Semigroups.Generator.Uniqueness
public import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Analysis.Calculus.Deriv.Mul

/-!
# The uniformly continuous semigroup generated by a bounded operator

For a bounded operator `A : X →L[ℝ] X` on a Banach space, the operator exponential
`t ↦ exp (t • A)` is a strongly (indeed uniformly, norm-) continuous one-parameter
semigroup.  This file records that construction, `ofBounded A`, and its basic API:

* `ofBounded A` is a `StronglyContinuousSemigroup`, with `exp (t • A)` at time `t`;
* it satisfies the growth bound `(‖A‖, 1)`, from `‖exp x‖ ≤ Real.exp ‖x‖`;
* its infinitesimal generator is `A` itself, on the whole space (`ofBounded_domain_eq_top`,
  `ofBounded_generator`);
* conversely, uniqueness of the semigroup generated by an operator identifies every C₀-semigroup
  whose generator is `A` on the whole space with `ofBounded A` (`eq_ofBounded_of_generator_eq`).

This is the general bounded-generator acceptance example for the one-parameter-semigroups
roadmap; the zero-operator case is the identity semigroup
(`TauCeti/Analysis/Semigroups/Identity.lean`), and here `A` is an arbitrary bounded operator.
The endomorphism algebra `X →L[ℝ] X` is a Banach algebra, so Mathlib's `NormedSpace.exp`
and its derivative `hasDerivAt_exp_smul_const` apply directly.

## References
The uniformly continuous semigroup `S(t) = exp (tA)` and the identification of its generator
with `A` are standard; see Engel--Nagel, *One-Parameter Semigroups for Linear Evolution
Equations*, Ch. I, and Pazy, *Semigroups of Linear Operators*, Ch. 1.
-/

public section

noncomputable section

open scoped NNReal Topology
open NormedSpace

namespace TauCeti.Semigroups

variable {X : Type*} [NormedAddCommGroup X] [NormedSpace ℝ X] [CompleteSpace X]

namespace StronglyContinuousSemigroup

omit [CompleteSpace X] in
/-- In the Banach algebra `X →L[ℝ] X`, the operator exponential is norm-bounded by the scalar
exponential of the norm: `‖exp x‖ ≤ Real.exp ‖x‖`.  This is the termwise triangle inequality
on the exponential series, using submultiplicativity `‖xⁿ‖ ≤ ‖x‖ⁿ`. -/
private lemma norm_exp_le_exp_norm (x : X →L[ℝ] X) : ‖exp x‖ ≤ Real.exp ‖x‖ := by
  rw [exp_eq_tsum ℝ]
  refine (norm_tsum_le_tsum_norm (norm_expSeries_summable' (𝕂 := ℝ) x)).trans ?_
  rw [Real.exp_eq_exp_ℝ, exp_eq_tsum ℝ]
  refine Summable.tsum_le_tsum (fun n => ?_) (norm_expSeries_summable' (𝕂 := ℝ) x)
    (expSeries_summable' (𝕂 := ℝ) ‖x‖)
  rw [norm_smul, Real.norm_eq_abs, abs_of_nonneg (by positivity), smul_eq_mul]
  gcongr
  cases n with
  | zero => simp only [pow_zero, ContinuousLinearMap.one_def]; exact ContinuousLinearMap.norm_id_le
  | succ m => exact norm_pow_le' x m.succ_pos

/-- The operator exponential is additive on commuting elements of `X →L[ℝ] X`, phrased over the
scalar field `ℝ` (the `ℚ`-algebra instance required by `NormedSpace.exp_add_of_commute` is not
available here). -/
private lemma exp_add_of_commute {x y : X →L[ℝ] X} (h : Commute x y) :
    exp (x + y) = exp x * exp y :=
  exp_add_of_commute_of_mem_ball (𝕂 := ℝ) h
    ((expSeries_radius_eq_top ℝ (X →L[ℝ] X)).symm ▸ edist_lt_top _ _)
    ((expSeries_radius_eq_top ℝ (X →L[ℝ] X)).symm ▸ edist_lt_top _ _)

/-- The uniformly continuous C₀-semigroup `S(t) = exp (t • A)` generated by a bounded operator
`A : X →L[ℝ] X`. -/
def ofBounded (A : X →L[ℝ] X) : StronglyContinuousSemigroup X where
  toFun t := exp ((t : ℝ) • A)
  map_zero' := by
    rw [NNReal.coe_zero, zero_smul, exp_zero, ContinuousLinearMap.one_def]
  map_add' s t := by
    rw [NNReal.coe_add, add_smul,
      exp_add_of_commute (((Commute.refl A).smul_left _).smul_right _), ContinuousLinearMap.mul_def]
  continuousAt_zero' x :=
    (((differentiable_exp_smul_const ℝ A).continuous.comp NNReal.continuous_coe).clm_apply
      continuous_const).continuousAt

/-- The operator of `ofBounded A` at nonnegative time `t` is `exp (t • A)`. -/
@[simp]
theorem ofBounded_apply (A : X →L[ℝ] X) (t : ℝ≥0) : (ofBounded A) t = exp ((t : ℝ) • A) := by
  rw [ofBounded]; rfl

/-- The operator of `ofBounded A` at nonnegative time `t`, applied to `x`, is `exp (t • A) x`. -/
theorem ofBounded_apply_apply (A : X →L[ℝ] X) (t : ℝ≥0) (x : X) :
    (ofBounded A) t x = exp ((t : ℝ) • A) x := by
  rw [ofBounded_apply]

/-- The real-time operator of `ofBounded A` at `t ≥ 0` is `exp (t • A)`. -/
theorem ofBounded_realOperator_of_nonneg (A : X →L[ℝ] X) {t : ℝ} (ht : 0 ≤ t) :
    (ofBounded A).realOperator t = exp (t • A) := by
  have ht_coe : ((t.toNNReal : ℝ) = t) := Real.coe_toNNReal t ht
  rw [← ht_coe, realOperator_coe, ofBounded_apply]

/-- The real-time operator of `ofBounded A` at `t ≥ 0`, applied to `x`, is `exp (t • A) x`. -/
theorem ofBounded_realOperator_apply_of_nonneg (A : X →L[ℝ] X) {t : ℝ} (ht : 0 ≤ t) (x : X) :
    (ofBounded A).realOperator t x = exp (t • A) x := by
  rw [ofBounded_realOperator_of_nonneg A ht]

/-- The bounded-generator semigroup is norm-continuous in nonnegative time. -/
theorem ofBounded_continuous (A : X →L[ℝ] X) :
    Continuous fun t : ℝ≥0 => (ofBounded A) t := by
  simpa only [ofBounded_apply, Function.comp_def] using
    (differentiable_exp_smul_const ℝ A).continuous.comp NNReal.continuous_coe

/-- The real-time operator of `ofBounded A` is norm-continuous on the nonnegative half-line. -/
theorem ofBounded_realOperator_continuousOn_Ici (A : X →L[ℝ] X) :
    ContinuousOn (fun t : ℝ => (ofBounded A).realOperator t) (Set.Ici 0) := by
  refine ((differentiable_exp_smul_const ℝ A).continuous.continuousOn).congr ?_
  exact fun t ht => ofBounded_realOperator_of_nonneg A ht

/-- The semigroup `ofBounded A` has the growth bound `(‖A‖, 1)`: `‖exp (t • A)‖ ≤ e^{‖A‖ t}`. -/
theorem ofBounded_hasGrowthBound (A : X →L[ℝ] X) : (ofBounded A).HasGrowthBound ‖A‖ 1 := by
  refine hasGrowthBound_of_bound le_rfl (fun t ht => ?_)
  rw [one_mul, ofBounded_realOperator_of_nonneg A ht]
  calc ‖exp (t • A)‖ ≤ Real.exp ‖t • A‖ := norm_exp_le_exp_norm _
    _ = Real.exp (‖A‖ * t) := by
        rw [norm_smul, Real.norm_eq_abs, abs_of_nonneg ht, mul_comm]

/-- The difference quotient `(exp (t • A) x - x)/t` tends to `A x` as `t → 0⁺`: the strong
derivative of `ofBounded A` at time `0` is `A`. -/
private theorem ofBounded_genQuot_tendsto (A : X →L[ℝ] X) (x : X) :
    Filter.Tendsto (fun t => (1 / t) • ((ofBounded A).realOperator t x - x))
      (nhdsWithin 0 (Set.Ioi 0)) (nhds (A x)) := by
  -- `u ↦ exp (u • A) x` is differentiable at `0` with derivative `A x`.
  have h1 : HasDerivAt (fun u : ℝ => exp (u • A)) A 0 := by
    -- The derivative `exp (0 • A) * A` normalizes to `A` via `0 • A = 0`, `exp 0 = 1`, `1 * A = A`.
    simpa only [zero_smul, exp_zero, one_mul] using hasDerivAt_exp_smul_const A (0 : ℝ)
  have hD : HasDerivAt (fun u : ℝ => exp (u • A) x) (A x) 0 := by
    -- The derivative `A x + exp (0 • A) 0` normalizes to `A x` via `_ 0 = 0`, `_ + 0 = _`.
    have h := HasDerivAt.clm_apply h1 (hasDerivAt_const (0 : ℝ) x)
    rwa [ContinuousLinearMap.map_zero, add_zero] at h
  rw [hasDerivAt_iff_tendsto_slope] at hD
  have hmono : nhdsWithin (0 : ℝ) (Set.Ioi 0) ≤ nhdsWithin 0 {(0 : ℝ)}ᶜ :=
    nhdsWithin_mono _ fun y hy => ne_of_gt hy
  refine (hD.mono_left hmono).congr' ?_
  filter_upwards [self_mem_nhdsWithin] with t ht
  have htpos : (0 : ℝ) < t := ht
  have h0 : exp ((0 : ℝ) • A) x = x := by
    rw [zero_smul, exp_zero, ContinuousLinearMap.one_def, ContinuousLinearMap.id_apply]
  simp only [slope_def_module, sub_zero]
  rw [ofBounded_realOperator_of_nonneg A htpos.le, one_div, h0]

/-- Every vector lies in the generator domain of `ofBounded A`: its generator is bounded. -/
theorem mem_ofBounded_domain (A : X →L[ℝ] X) (x : X) :
    x ∈ (ofBounded A).domain :=
  ((ofBounded A).generator_eq_toPMap_top_of_forall_tendsto (A : X →ₗ[ℝ] X)
    (ofBounded_genQuot_tendsto A)).1.ge trivial

/-- The generator domain of `ofBounded A` is the whole space. -/
@[simp]
theorem ofBounded_domain_eq_top (A : X →L[ℝ] X) : (ofBounded A).domain = ⊤ :=
  ((ofBounded A).generator_eq_toPMap_top_of_forall_tendsto (A : X →ₗ[ℝ] X)
    (ofBounded_genQuot_tendsto A)).1

/-- The generator of `ofBounded A` is `A` itself, viewed as a total unbounded operator. -/
@[simp]
theorem ofBounded_generator (A : X →L[ℝ] X) : (ofBounded A).generator = (A : X →ₗ[ℝ] X).toPMap ⊤ :=
  ((ofBounded A).generator_eq_toPMap_top_of_forall_tendsto (A : X →ₗ[ℝ] X)
    (ofBounded_genQuot_tendsto A)).2

/-- A strongly continuous semigroup whose generator is the bounded operator `A`, defined on all
of `X`, is the operator exponential `t ↦ exp (t • A)`. -/
theorem eq_ofBounded_of_generator_eq {S : StronglyContinuousSemigroup X} (A : X →L[ℝ] X)
    (h : S.generator = (A : X →ₗ[ℝ] X).toPMap ⊤) : S = ofBounded A :=
  eq_of_generator_eq (h.trans (ofBounded_generator A).symm)

end StronglyContinuousSemigroup

end TauCeti.Semigroups

end
