/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Functoriality
public import TauCeti.Algebra.Lie.UniversalEnveloping.PBW.Basic
public import TauCeti.Algebra.Module.Rat
public import TauCeti.RingTheory.DividedPowers.Associative
public import TauCeti.RingTheory.Binomial

/-!
# The Kostant integral form generated by root and Cartan vectors

Let `L` be a Lie algebra over `ℚ`. Given families `e : ι → L` of root vectors and
`h : κ → L` of Cartan vectors, the associated **Kostant integral form** is the subring of
`UniversalEnvelopingAlgebra ℚ L` generated by

```text
eᵢ⁽ⁿ⁾ = eᵢⁿ / n!       and       (hⱼ choose n)
```

for all indices and all natural numbers `n`. When `e` ranges over the Chevalley root vectors
`x_α` for every root `α` (positive and negative), and `h` ranges over the Cartan generators,
this is the usual Kostant `ℤ`-form. The definition in this file deliberately takes the two
distinguished families as data: the later Chevalley construction will supply them from a pinned
root datum, while the integral-form construction and its functoriality do not use the Chevalley
relations.

The divided powers are `TauCeti.Associative.dividedPower`. The Cartan generators are Mathlib's
`Ring.choose`, which evaluates the descending Pochhammer polynomial and divides by `n!`; no second
binomial-coefficient API is introduced here. The form is a `Subring`, rather than a `ℚ`-subalgebra,
because multiplication by arbitrary rational scalars would destroy the integral lattice. A local
`ℚ≥0`-module structure supplies the `BinomialRing` instance used to elaborate `Ring.choose`.

The Cartan--Cartan normal-ordering rule is `TauCeti.ringChoose_mul_ringChoose`: it expands a
product of two binomial coefficients in one Cartan vector as an integral linear combination of
binomial coefficients in that vector. Separately, because each coefficient in a designated Cartan
vector is a generator of the Kostant form, the subring they generate lies in that form.

The main results are a spanning theorem and exact functoriality. When `e` and `h` generate `L` as
a Lie algebra, the form spans the enveloping algebra over `ℚ`. A Lie homomorphism sends the form
generated by `(e, h)` onto the form generated by their images, so a Lie equivalence restricts to a
ring equivalence of the corresponding integral forms. These are respectively the fullness and
transport results needed by the Chevalley construction.

## Main definitions and results

* `TauCeti.UniversalEnvelopingAlgebra.kostantForm`: the generated integral form.
* `TauCeti.UniversalEnvelopingAlgebra.kostantForm_le_iff`: its universal property.
* `TauCeti.UniversalEnvelopingAlgebra.subringClosure_range_ringChoose_le_kostantForm`: the subring
  generated by the binomial coefficients in one Cartan vector lies in the Kostant form.
* `TauCeti.UniversalEnvelopingAlgebra.span_kostantForm_eq_top`: under a Lie-generation
  hypothesis, the form spans the enveloping algebra over `ℚ`.
* `TauCeti.UniversalEnvelopingAlgebra.map_kostantForm`: exact functoriality under Lie maps.
* `TauCeti.UniversalEnvelopingAlgebra.kostantFormMap`: the restricted map of integral forms.
* `TauCeti.UniversalEnvelopingAlgebra.kostantFormEquiv`: transport under a Lie equivalence.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §26.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.
-/

public section

namespace TauCeti.UniversalEnvelopingAlgebra

open Set

universe u v w

variable {L : Type u} {M : Type v}
variable [LieRing L] [LieAlgebra ℚ L]
variable [LieRing M] [LieAlgebra ℚ M]
variable {ι : Type w} {κ : Type*}

attribute [local instance] TauCeti.moduleNNRat

/-! ## Generators and the integral form -/

/-- The divided powers of a specified family of root vectors in the universal enveloping algebra. -/
def kostantRootGenerators (e : ι → L) :
    Set (_root_.UniversalEnvelopingAlgebra ℚ L) :=
  range fun p : ι × ℕ =>
    Associative.dividedPower p.2 (_root_.UniversalEnvelopingAlgebra.ι ℚ (e p.1))

/-- The binomial coefficients of a specified family of Cartan vectors in the universal enveloping
algebra. Mathlib's `Ring.choose x n` is `x * (x - 1) * ... * (x - n + 1) / n!`. -/
def kostantCartanGenerators (h : κ → L) :
    Set (_root_.UniversalEnvelopingAlgebra ℚ L) :=
  range fun p : κ × ℕ => Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ (h p.1)) p.2

/-- The generators of the Kostant integral form attached to root vectors `e` and Cartan vectors
`h`: all divided powers of the former and all binomial coefficients of the latter. -/
def kostantGenerators (e : ι → L) (h : κ → L) :
    Set (_root_.UniversalEnvelopingAlgebra ℚ L) :=
  kostantRootGenerators e ∪ kostantCartanGenerators h

/-- The **Kostant integral form** generated by specified root and Cartan vectors.

When `e` ranges over the Chevalley root vectors for every root, both positive and negative, and
`h` ranges over the Cartan generators, this is the usual `ℤ`-form inside the universal enveloping
algebra. It is represented as the smallest subring containing the divided powers of the supplied
root vectors and the binomial coefficients of the supplied Cartan vectors. -/
def kostantForm (e : ι → L) (h : κ → L) :
    Subring (_root_.UniversalEnvelopingAlgebra ℚ L) :=
  Subring.closure (kostantGenerators e h)

/-- A divided power of a designated root vector is one of the root-generator elements. -/
theorem dividedPower_mem_kostantRootGenerators (e : ι → L) (i : ι) (n : ℕ) :
    Associative.dividedPower n (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)) ∈
      kostantRootGenerators e :=
  ⟨(i, n), rfl⟩

/-- Membership in the root generators: the elements are exactly the divided powers of the
designated root vectors. -/
@[simp]
theorem mem_kostantRootGenerators_iff {e : ι → L}
    {x : _root_.UniversalEnvelopingAlgebra ℚ L} :
    x ∈ kostantRootGenerators e ↔
      ∃ i n, Associative.dividedPower n (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)) = x := by
  constructor
  · rintro ⟨⟨i, n⟩, rfl⟩
    exact ⟨i, n, rfl⟩
  · rintro ⟨i, n, rfl⟩
    exact ⟨(i, n), rfl⟩

/-- A binomial coefficient of a designated Cartan vector is one of the Cartan-generator
elements. -/
theorem ringChoose_mem_kostantCartanGenerators (h : κ → L) (i : κ) (n : ℕ) :
    Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ (h i)) n ∈
      kostantCartanGenerators h :=
  ⟨(i, n), rfl⟩

/-- Membership in the Cartan generators: the elements are exactly the binomial coefficients of the
designated Cartan vectors. -/
@[simp]
theorem mem_kostantCartanGenerators_iff {h : κ → L}
    {x : _root_.UniversalEnvelopingAlgebra ℚ L} :
    x ∈ kostantCartanGenerators h ↔
      ∃ i n, Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ (h i)) n = x := by
  constructor
  · rintro ⟨⟨i, n⟩, rfl⟩
    exact ⟨i, n, rfl⟩
  · rintro ⟨i, n, rfl⟩
    exact ⟨(i, n), rfl⟩

/-- Membership in the full generator set: an element is a generator exactly when it is a divided
power of a designated root vector or a binomial coefficient of a designated Cartan vector. -/
@[simp]
theorem mem_kostantGenerators_iff {e : ι → L} {h : κ → L}
    {x : _root_.UniversalEnvelopingAlgebra ℚ L} :
    x ∈ kostantGenerators e h ↔
      (∃ i n, Associative.dividedPower n (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)) = x) ∨
        ∃ i n, Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ (h i)) n = x := by
  rw [kostantGenerators, mem_union, mem_kostantRootGenerators_iff,
    mem_kostantCartanGenerators_iff]

/-- Every divided power of a designated root vector belongs to the Kostant form. -/
theorem dividedPower_mem_kostantForm (e : ι → L) (h : κ → L) (i : ι) (n : ℕ) :
    Associative.dividedPower n (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)) ∈
      kostantForm e h :=
  Subring.subset_closure <| Or.inl (dividedPower_mem_kostantRootGenerators e i n)

/-- Every binomial coefficient of a designated Cartan vector belongs to the Kostant form. -/
theorem ringChoose_mem_kostantForm (e : ι → L) (h : κ → L) (i : κ) (n : ℕ) :
    Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ (h i)) n ∈
      kostantForm e h :=
  Subring.subset_closure <| Or.inr (ringChoose_mem_kostantCartanGenerators h i n)

/-- The subring generated by the binomial coefficients in one designated Cartan vector is
contained in the Kostant form. -/
theorem subringClosure_range_ringChoose_le_kostantForm (e : ι → L) (h : κ → L) (i : κ) :
    Subring.closure
      (Set.range (Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ (h i)))) ≤ kostantForm e h :=
  Subring.closure_le.2 (Set.range_subset_iff.2 (ringChoose_mem_kostantForm e h i))

/-- Each designated root vector itself belongs to the Kostant form. -/
theorem rootVector_mem_kostantForm (e : ι → L) (h : κ → L) (i : ι) :
    _root_.UniversalEnvelopingAlgebra.ι ℚ (e i) ∈ kostantForm e h := by
  simpa using dividedPower_mem_kostantForm e h i 1

/-- Each designated Cartan vector itself belongs to the Kostant form. -/
theorem cartanVector_mem_kostantForm (e : ι → L) (h : κ → L) (i : κ) :
    _root_.UniversalEnvelopingAlgebra.ι ℚ (h i) ∈ kostantForm e h := by
  simpa using ringChoose_mem_kostantForm e h i 1

/-- The universal property of the Kostant form: it lies in a subring exactly when that subring
contains every root divided power and every Cartan binomial coefficient. -/
@[simp]
theorem kostantForm_le_iff (e : ι → L) (h : κ → L)
    (S : Subring (_root_.UniversalEnvelopingAlgebra ℚ L)) :
    kostantForm e h ≤ S ↔
      (∀ i n, Associative.dividedPower n (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)) ∈ S) ∧
      (∀ i n, Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ (h i)) n ∈ S) := by
  rw [kostantForm, Subring.closure_le]
  constructor
  · intro hS
    exact ⟨fun i n => hS (Or.inl ⟨(i, n), rfl⟩),
      fun i n => hS (Or.inr ⟨(i, n), rfl⟩)⟩
  · rintro ⟨he, hh⟩ x (hx | hx)
    · obtain ⟨⟨i, n⟩, rfl⟩ := hx
      exact he i n
    · obtain ⟨⟨i, n⟩, rfl⟩ := hx
      exact hh i n

/-! ## Spanning the enveloping algebra -/

/-- **The Kostant integral form spans the enveloping algebra.** If the supplied root and Cartan
vectors generate `L` as a Lie algebra, every element of `U(L)` is a `ℚ`-linear combination of
elements of `kostantForm e h`; equivalently, `ℚ ⊗ℤ U_ℤ → U(L)` is onto.

This is the half of "`U_ℤ` is a `ℤ`-form of `U(L)`" that does not need the integral
Poincaré--Birkhoff--Witt theorem. The hypothesis is exactly what a Chevalley basis supplies, since
the root vectors and the Cartan generators generate a semisimple Lie algebra. -/
theorem span_kostantForm_eq_top (e : ι → L) (h : κ → L)
    (hgen : LieSubalgebra.lieSpan ℚ L (range e ∪ range h) = ⊤) :
    Submodule.span ℚ (kostantForm e h : Set (_root_.UniversalEnvelopingAlgebra ℚ L)) = ⊤ := by
  have hadjoin : _root_.Algebra.adjoin ℚ
      (kostantForm e h : Set (_root_.UniversalEnvelopingAlgebra ℚ L)) = ⊤ := by
    rw [eq_top_iff, ← adjoin_image_ι_eq_top ℚ L hgen]
    refine _root_.Algebra.adjoin_le ?_
    rintro _ ⟨x, (⟨i, rfl⟩ | ⟨i, rfl⟩), rfl⟩
    · exact _root_.Algebra.subset_adjoin (rootVector_mem_kostantForm e h i)
    · exact _root_.Algebra.subset_adjoin (cartanVector_mem_kostantForm e h i)
  have hspan : Subalgebra.toSubmodule (_root_.Algebra.adjoin ℚ
      (kostantForm e h : Set (_root_.UniversalEnvelopingAlgebra ℚ L))) =
      Submodule.span ℚ (kostantForm e h : Set (_root_.UniversalEnvelopingAlgebra ℚ L)) := by
    apply _root_.Algebra.adjoin_eq_span_of_subset
    rw [← Subring.coe_toSubmonoid, (kostantForm e h).toSubmonoid.closure_eq]
    exact Submodule.subset_span
  rw [← hspan, hadjoin, _root_.Algebra.top_toSubmodule]

/-! ## Functoriality -/

variable (f : LieHom ℚ L M)

/-- A Lie homomorphism maps the root generators to the root generators of the image family. -/
theorem image_kostantRootGenerators (e : ι → L) :
    (map ℚ f) '' kostantRootGenerators e =
      kostantRootGenerators (fun i => f (e i)) := by
  ext x
  constructor
  · rintro ⟨_, ⟨⟨i, n⟩, rfl⟩, rfl⟩
    exact ⟨(i, n), by simp⟩
  · rintro ⟨⟨i, n⟩, rfl⟩
    refine ⟨Associative.dividedPower n
      (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)), ⟨(i, n), rfl⟩, ?_⟩
    simp

/-- A Lie homomorphism maps the Cartan generators to the Cartan generators of the image family. -/
theorem image_kostantCartanGenerators (h : κ → L) :
    (map ℚ f) '' kostantCartanGenerators h =
      kostantCartanGenerators (fun i => f (h i)) := by
  ext x
  constructor
  · rintro ⟨_, ⟨⟨i, n⟩, rfl⟩, rfl⟩
    exact ⟨(i, n), by simp [Ring.map_choose]⟩
  · rintro ⟨⟨i, n⟩, rfl⟩
    refine ⟨Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ (h i)) n,
      ⟨(i, n), rfl⟩, ?_⟩
    simp [Ring.map_choose]

/-- A Lie homomorphism maps the full Kostant generator set onto the generator set of the image
families. -/
theorem image_kostantGenerators (e : ι → L) (h : κ → L) :
    (map ℚ f) '' kostantGenerators e h =
      kostantGenerators (fun i => f (e i)) (fun i => f (h i)) := by
  rw [kostantGenerators, image_union, image_kostantRootGenerators,
    image_kostantCartanGenerators, kostantGenerators]

/-- **Exact functoriality of the Kostant form.** The enveloping-algebra map induced by a Lie
homomorphism sends the integral form generated by `(e, h)` onto the integral form generated by
their pointwise images. -/
theorem map_kostantForm (e : ι → L) (h : κ → L) :
    (kostantForm e h).map (map ℚ f).toRingHom =
      kostantForm (fun i => f (e i)) (fun i => f (h i)) := by
  rw [kostantForm, RingHom.map_closure, kostantForm]
  exact congrArg Subring.closure (image_kostantGenerators f e h)

/-- The restriction of an enveloping-algebra map to the corresponding Kostant integral forms. -/
noncomputable def kostantFormMap (e : ι → L) (h : κ → L) :
    kostantForm e h →+* kostantForm (fun i => f (e i)) (fun i => f (h i)) :=
  (map ℚ f).toRingHom.restrict _ _ fun x hx => by
    rw [← map_kostantForm f e h]
    exact ⟨x, hx, rfl⟩

/-- The restricted map agrees with the enveloping-algebra map on underlying elements. -/
@[simp]
theorem coe_kostantFormMap_apply (e : ι → L) (h : κ → L) (x : kostantForm e h) :
    (kostantFormMap f e h x : _root_.UniversalEnvelopingAlgebra ℚ M) = map ℚ f x :=
  RingHom.coe_restrict_apply _ _ _ _ x

/-- The restricted map is onto the form generated by the image families. No surjectivity
hypothesis on the ambient Lie homomorphism is needed, since the target families are its images. -/
theorem kostantFormMap_surjective (e : ι → L) (h : κ → L) :
    Function.Surjective (kostantFormMap f e h) :=
  RingHom.surjective_codRestrict.2 <| SetLike.coe_injective <| by
    rw [← map_kostantForm f e h]
    simp only [RingHom.coe_rangeS, Subsemiring.coe_ofClass, Subring.coe_map, Set.image_eq_range]
    exact congrArg Set.range (funext fun x => RingHom.domRestrict_apply _ x)

/-- A Lie equivalence restricts to a ring equivalence between the Kostant forms generated by a
family and by its pointwise image. -/
noncomputable def kostantFormEquiv (g : LieEquiv ℚ L M) (e : ι → L) (h : κ → L) :
    kostantForm e h ≃+* kostantForm (fun i => g (e i)) (fun i => g (h i)) :=
  (RingEquiv.subringMap (s := kostantForm e h) (mapEquiv ℚ g).toRingEquiv).trans
    (RingEquiv.subringCongr (by
      have hmap : (mapEquiv ℚ g).toRingEquiv.toRingHom =
          (map ℚ g.toLieHom).toRingHom :=
        congrArg AlgHom.toRingHom (mapEquiv_toAlgHom ℚ g)
      rw [hmap]
      exact map_kostantForm g.toLieHom e h))

/-- The restricted equivalence acts by the enveloping-algebra map induced by the original Lie
equivalence. -/
@[simp]
theorem coe_kostantFormEquiv_apply (g : LieEquiv ℚ L M) (e : ι → L) (h : κ → L)
    (x : kostantForm e h) :
    (kostantFormEquiv g e h x : _root_.UniversalEnvelopingAlgebra ℚ M) =
      map ℚ g.toLieHom x := by
  rw [kostantFormEquiv, RingEquiv.trans_apply, RingEquiv.coe_subringCongr_apply]
  -- `RingEquiv.subringMap` is `RingEquiv.subsemiringMap` on the underlying subsemiring, so
  -- `RingEquiv.subsemiringMap_apply_coe` computes it; it cannot be used by `rw`, since the two
  -- carriers `↥(kostantForm e h)` and `↥(kostantForm e h).toSubsemiring` are only definitionally
  -- equal, so the computation is recorded as an explicit coercion equation instead.
  have hsub : ((RingEquiv.subringMap (s := kostantForm e h) (mapEquiv ℚ g).toRingEquiv) x :
      _root_.UniversalEnvelopingAlgebra ℚ M) =
      mapEquiv ℚ g (x : _root_.UniversalEnvelopingAlgebra ℚ L) :=
    RingEquiv.subsemiringMap_apply_coe _ _ _
  rw [hsub, ← AlgEquiv.toAlgHom_apply, mapEquiv_toAlgHom]

/-- The inverse restricted equivalence acts by the enveloping-algebra map induced by the inverse
Lie equivalence. -/
@[simp]
theorem coe_kostantFormEquiv_symm_apply (g : LieEquiv ℚ L M) (e : ι → L) (h : κ → L)
    (y : kostantForm (fun i => g (e i)) (fun i => g (h i))) :
    ((kostantFormEquiv g e h).symm y : _root_.UniversalEnvelopingAlgebra ℚ L) =
      map ℚ g.symm.toLieHom y := by
  rw [kostantFormEquiv, RingEquiv.symm_trans_apply]
  -- As in `coe_kostantFormEquiv_apply`, the inverse of the restricted equivalence is computed by
  -- `RingEquiv.subsemiringMap_symm_apply_coe` through the definitional identification of
  -- `RingEquiv.subringMap` with `RingEquiv.subsemiringMap`.
  have hsub : ∀ z : (kostantForm e h).map (mapEquiv ℚ g).toRingEquiv.toRingHom,
      ((RingEquiv.subringMap (s := kostantForm e h) (mapEquiv ℚ g).toRingEquiv).symm z :
        _root_.UniversalEnvelopingAlgebra ℚ L) =
        (mapEquiv ℚ g).symm (z : _root_.UniversalEnvelopingAlgebra ℚ M) :=
    fun z => RingEquiv.subsemiringMap_symm_apply_coe _ _ _
  rw [hsub, RingEquiv.subringCongr_symm, RingEquiv.coe_subringCongr_apply, mapEquiv_symm,
    ← AlgEquiv.toAlgHom_apply, mapEquiv_toAlgHom]

end TauCeti.UniversalEnvelopingAlgebra
