/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.Form

/-!
# Integral orbits of a Kostant form

Let `L` be a Lie algebra over `ℚ` and let `U_ℤ = kostantForm e h` be the Kostant integral form
generated by families `e` of root vectors and `h` of Cartan vectors. For a module `V` over
`U(L)` and a vector `v : V`, this file studies the integral orbit

```text
U_ℤ • v ⊆ V.
```

The orbit is stable under `U_ℤ`; in particular, it is preserved by the divided powers of the root
vectors and the binomial coefficients of the Cartan vectors. When `e` and `h` generate `L` as a
Lie algebra, its `ℚ`-span is the whole `U(L)`-submodule generated by `v`. For a cyclic module this
is all of `V`.

Finite generation over `ℤ` is not proved here. Thus the orbit is not yet asserted to be a lattice
in the sense of Humphreys §27; that requires the integral Poincaré--Birkhoff--Witt theorem. The
present stability and spanning results are the parts of the admissible-lattice construction that
are available without integral PBW.

## Main definitions and results

* `TauCeti.UniversalEnvelopingAlgebra.kostantOrbit`: the integral orbit `U_ℤ • v`.
* `TauCeti.UniversalEnvelopingAlgebra.smul_mem_kostantOrbit`: stability under the integral form.
* `TauCeti.UniversalEnvelopingAlgebra.dividedPower_smul_mem_kostantOrbit` and
  `TauCeti.UniversalEnvelopingAlgebra.ringChoose_smul_mem_kostantOrbit`: stability under the two
  families of Kostant generators.
* `TauCeti.UniversalEnvelopingAlgebra.span_kostantOrbit_eq_span_singleton`: under a
  Lie-generation hypothesis, the `ℚ`-span is the `U(L)`-submodule generated by `v`.
* `TauCeti.UniversalEnvelopingAlgebra.span_kostantOrbit_eq_top`: for a cyclic module the orbit
  spans `V` over `ℚ`.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §26 and §27.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.
* R. Steinberg, *Lectures on Chevalley Groups*, §2.
-/

public section

universe u v w

namespace TauCeti.UniversalEnvelopingAlgebra

open Set

private theorem span_subring_smul_eq_span_singleton
    {A : Type u} [Ring A] [Algebra ℚ A] {V : Type v} [AddCommGroup V]
    [Module A V] [Module ℚ V] [IsScalarTower ℚ A V] (S : Subring A)
    (hspan : Submodule.span ℚ (S : Set A) = ⊤) (v : V) :
    Submodule.span ℚ ((Submodule.span S {v}).restrictScalars ℤ : Set V) =
      (Submodule.span A {v}).restrictScalars ℚ := by
  have horbit : ((Submodule.span S {v}).restrictScalars ℤ : Set V) =
      (LinearMap.toSpanSingleton A V v).restrictScalars ℚ '' (S : Set A) := by
    ext x
    rw [Set.mem_image, Submodule.coe_restrictScalars]
    simp only [SetLike.mem_coe]
    rw [Submodule.mem_span_singleton]
    simp only [LinearMap.restrictScalars_apply, LinearMap.toSpanSingleton_apply]
    constructor
    · rintro ⟨u, rfl⟩
      exact ⟨u, u.property, (Subring.smul_def u v).symm⟩
    · rintro ⟨u, hu, rfl⟩
      exact ⟨⟨u, hu⟩, Subring.smul_def ⟨u, hu⟩ v⟩
  rw [horbit, Submodule.span_image, hspan, Submodule.map_top,
    LinearMap.span_singleton_eq_range, LinearMap.range_restrictScalars]

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {ι : Type w} {κ : Type*}

attribute [local instance] TauCeti.moduleNNRat

local notation "U" => _root_.UniversalEnvelopingAlgebra ℚ L

section Orbit

variable {V : Type v} [AddCommGroup V]
variable [Module (_root_.UniversalEnvelopingAlgebra ℚ L) V]
variable {e : ι → L} {h : κ → L} {v : V}

/-- The integral orbit generated by `v` under the Kostant form attached to `e` and `h`.

This is the span of `v` over the subring `kostantForm e h`, regarded as a `ℤ`-submodule of `V`.
No finite-generation or lattice property is asserted. -/
def kostantOrbit (e : ι → L) (h : κ → L) (v : V) : Submodule ℤ V :=
  (Submodule.span (kostantForm e h) {v}).restrictScalars ℤ

/-- The Kostant orbit consists exactly of the vectors `u • v` for `u` in the integral form. -/
@[simp]
theorem mem_kostantOrbit_iff {x : V} :
    x ∈ kostantOrbit e h v ↔ ∃ u ∈ kostantForm e h, u • v = x := by
  unfold kostantOrbit
  rw [Submodule.restrictScalars_mem, Submodule.mem_span_singleton]
  constructor
  · rintro ⟨u, rfl⟩
    exact ⟨u, u.property, (Subring.smul_def u v).symm⟩
  · rintro ⟨u, hu, rfl⟩
    exact ⟨⟨u, hu⟩, Subring.smul_def ⟨u, hu⟩ v⟩

/-- The generating vector belongs to its Kostant orbit. -/
theorem mem_kostantOrbit_self : v ∈ kostantOrbit e h v :=
  mem_kostantOrbit_iff.2 ⟨1, (kostantForm e h).one_mem, one_smul U v⟩

/-- The Kostant orbit is stable under the integral form. -/
theorem smul_mem_kostantOrbit {u : U} (hu : u ∈ kostantForm e h) {x : V}
    (hx : x ∈ kostantOrbit e h v) : u • x ∈ kostantOrbit e h v := by
  unfold kostantOrbit at hx ⊢
  rw [Submodule.restrictScalars_mem] at hx ⊢
  rw [← Subring.smul_def (⟨u, hu⟩ : kostantForm e h) x]
  exact Submodule.smul_mem _ ⟨u, hu⟩ hx

/-- The divided powers of the root vectors preserve the Kostant orbit. This is the stability
statement needed before locally finite root-vector exponentials can be defined. -/
theorem dividedPower_smul_mem_kostantOrbit (i : ι) (n : ℕ) {x : V}
    (hx : x ∈ kostantOrbit e h v) :
    Associative.dividedPower n (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i)) • x ∈
      kostantOrbit e h v :=
  smul_mem_kostantOrbit (dividedPower_mem_kostantForm e h i n) hx

/-- The binomial coefficients of the Cartan vectors preserve the Kostant orbit. -/
theorem ringChoose_smul_mem_kostantOrbit (i : κ) (n : ℕ) {x : V}
    (hx : x ∈ kostantOrbit e h v) :
    Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ (h i)) n • x ∈ kostantOrbit e h v :=
  smul_mem_kostantOrbit (ringChoose_mem_kostantForm e h i n) hx

/-- The Kostant orbit of the identity in the regular module is the integral form itself. -/
@[simp]
theorem kostantOrbit_one (e : ι → L) (h : κ → L) :
    kostantOrbit e h (1 : U) = (kostantForm e h).toAddSubgroup.toIntSubmodule := by
  refine SetLike.ext' ?_
  rw [AddSubgroup.coe_toIntSubmodule]
  ext x
  simp [mem_kostantOrbit_iff, eq_comm]

section Rational

variable [Module ℚ V]
variable [IsScalarTower ℚ (_root_.UniversalEnvelopingAlgebra ℚ L) V]

/-- If the supplied root and Cartan vectors generate `L` as a Lie algebra, the `ℚ`-span of their
Kostant orbit is the `U(L)`-submodule generated by `v`. -/
theorem span_kostantOrbit_eq_span_singleton (e : ι → L) (h : κ → L)
    (hgen : LieSubalgebra.lieSpan ℚ L (range e ∪ range h) = ⊤) (v : V) :
    Submodule.span ℚ (kostantOrbit e h v : Set V) =
      (Submodule.span U {v}).restrictScalars ℚ :=
  span_subring_smul_eq_span_singleton (kostantForm e h) (span_kostantForm_eq_top e h hgen) v

/-- If `v` generates `V` over `U(L)`, the Kostant orbit spans the whole module over `ℚ`. -/
theorem span_kostantOrbit_eq_top (e : ι → L) (h : κ → L)
    (hgen : LieSubalgebra.lieSpan ℚ L (range e ∪ range h) = ⊤) (v : V)
    (hv : Submodule.span U {v} = ⊤) :
    Submodule.span ℚ (kostantOrbit e h v : Set V) = ⊤ := by
  rw [span_kostantOrbit_eq_span_singleton e h hgen v, hv]
  exact Submodule.restrictScalars_top ℚ U V

end Rational

end Orbit

end TauCeti.UniversalEnvelopingAlgebra
