/-
Copyright (c) 2026 Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import TauCeti.RepresentationTheory.Induction.VirtualCharacter
public import TauCeti.RepresentationTheory.Induction.Spanning
import Mathlib.LinearAlgebra.Dimension.OrzechProperty
import Mathlib.LinearAlgebra.Dimension.StrongRankCondition
import Mathlib.LinearAlgebra.LinearIndependent.Lemmas
import Mathlib.LinearAlgebra.Matrix.Adjugate
import Mathlib.LinearAlgebra.Matrix.Basis

/-!
# Artin's induction theorem, rational form

Over an algebraically closed field `k` of characteristic zero, there is a single nonzero integer
`d` such that `d • χ` is a `ℤ`-linear combination of characters induced from irreducible characters
of cyclic subgroups, for **every** virtual character `χ` of the finite group `G`
(`TauCeti.ClassFunction.exists_zsmul_mem_indVirtualCharacterSpanCyclic`). Dividing by `d`, every
virtual character is a `ℚ`-linear combination of characters induced from cyclic subgroups: the
induction map `⨁_{C cyclic} R(C) → R(G)` is rationally surjective.

The proof turns the `k`-linear spanning statement of
`TauCeti.RepresentationTheory.Induction.Spanning` into an arithmetic one by a lattice descent.  The
characters induced from the cyclic subgroups span the class functions over `k`, so a subfamily of
them is a `k`-basis; that subfamily has as many members as the basis of irreducible characters
`TauCeti.basisIrreducibleCharacter`, and, being characters, its members lie in the `ℤ`-lattice that
the irreducible characters span.  The integer matrix expressing them in that basis is invertible
over `k`, so its determinant `d` is a nonzero integer, and multiplying by the adjugate expresses
`d • χᵢ` over the induced characters with integer coefficients.

## What this is not: the sharp constant

Artin's theorem in its sharp form takes the denominator to be `|G|` itself: `|G| • χ` is a
`ℤ`-linear combination of characters induced from cyclic subgroups.  The `d` produced here is the
determinant of a change-of-basis matrix, and nothing below identifies it with `|G|` or bounds it.
That refinement needs the explicit Artin identity writing `|G| • 1` as a sum of characters induced
from cyclic subgroups, together with the projection formula, and is not proved here; neither is
Brauer's integral induction theorem, whose denominator is `1`.

## Main statements

* `TauCeti.ClassFunction.indVirtualCharacterSpanCyclic`: the additive subgroup generated by the
  characters induced from irreducible characters of cyclic subgroups.
* `TauCeti.ClassFunction.exists_zsmul_mem_indVirtualCharacterSpanCyclic`: **Artin's induction
  theorem, rational form**, in the explicit shape "some nonzero integer multiple of every virtual
  character belongs to the subgroup generated by characters induced from cyclic subgroups".
## Implementation notes

`k` and `G` lie in the same universe here, unlike in
`TauCeti.RepresentationTheory.Induction.Spanning`, because the FDRep-level induction API used here
(`TauCeti.indFDRep` and `TauCeti.ClassFunction.ind_ofFDRep`) is currently stated in one universe.

The lattice descent is a general statement about a `ℤ`-lattice inside a finite-dimensional vector
space and has nothing to do with characters, but it is kept `private` here rather than given a home
of its own in the linear-algebra hierarchy, there being exactly one use of it.

## References

This proves the rational half of the "Artin's induction theorem" item of Layer 6 in
`TauCetiRoadmap/RepresentationTheory/InductionRestriction/README.md`, which asks for "the rational
surjectivity of `⨁_{C cyclic} R(C) → R(G)`" and, separately, for the `ℤ`-membership of `|G| • χ`;
the latter is not proved here.

* J.-P. Serre, *Linear Representations of Finite Groups*, Springer GTM 42 (1977), Section 9.2,
  Theorem 17 and its corollary.
* C. W. Curtis, I. Reiner, *Methods of Representation Theory, Vol. I*, Wiley (1981), Section 15.
-/

public section

namespace TauCeti

namespace ClassFunction

open Matrix Module

universe u

/-- **The adjugate combination recovers the determinant multiple.** If each `T j` is the
`N`-combination `∑ i, N j i • B i`, then `∑ j, N.adjugate i j • T j = N.det • B i`. Neither family
need be a basis. -/
private theorem sum_adjugate_smul_eq_det_smul {R ι M : Type*} [CommRing R] [Fintype ι]
    [DecidableEq ι] [AddCommMonoid M] [Module R M] (N : Matrix ι ι R) (B T : ι → M)
    (hMN : ∀ j, ∑ i, N j i • B i = T j) (i : ι) :
    ∑ j, N.adjugate i j • T j = N.det • B i :=
  calc ∑ j, N.adjugate i j • T j
      = ∑ j, ∑ l, (N.adjugate i j * N j l) • B l := by
        simp_rw [← hMN, Finset.smul_sum, smul_smul]
    _ = ∑ l, (∑ j, N.adjugate i j * N j l) • B l := by
        rw [Finset.sum_comm]; simp_rw [← Finset.sum_smul]
    _ = ∑ l, ((N.adjugate * N) i l) • B l := by simp_rw [Matrix.mul_apply]
    _ = N.det • B i := by rw [Matrix.adjugate_mul]; simp [Matrix.one_apply]

/-- **An integer matrix expressing a spanning family in a basis has nonzero determinant.** -/
private theorem det_ne_zero_of_span_eq_top {k V ι : Type*} [Field k] [CharZero k] [AddCommGroup V]
    [Module k V] [Fintype ι] [DecidableEq ι] (B : Basis ι k V) (T : ι → V) (N : Matrix ι ι ℤ)
    (hMN : ∀ j, ∑ i, N j i • B i = T j) (hspan : Submodule.span k (Set.range T) = ⊤) :
    N.det ≠ 0 := by
  -- A spanning family of the right cardinality is a basis, and `N` is then the change-of-basis
  -- matrix from `B`, whose determinant is a unit.
  let B' : Basis ι k V :=
    basisOfTopLeSpanOfCardEqFinrank T (by rw [hspan]) (finrank_eq_card_basis B).symm
  have hB' : ⇑B' = T := coe_basisOfTopLeSpanOfCardEqFinrank _ _ _
  have hrepr : ∀ j i, B.repr (T j) i = (N j i : k) := by
    intro j i
    rw [← hMN j]
    simp [Finsupp.single_apply]
  have htoMatrix : B.toMatrix ⇑B' = (N.map (Int.cast : ℤ → k))ᵀ := by
    ext i j
    rw [Basis.toMatrix_apply, hB', hrepr]
    simp
  have hdet : ((N.det : ℤ) : k) ≠ 0 := by
    rw [Int.cast_det, ← Matrix.det_transpose, ← htoMatrix, ← Module.Basis.det_apply]
    exact (B.isUnit_det B').ne_zero
  simpa using hdet

/-- The lattice descent behind Artin's theorem, as a statement of linear algebra: if a `ℤ`-lattice
in a finite-dimensional vector space is spanned by a basis `B`, and a family `T` of lattice vectors
spans the space over the field, then some nonzero integer multiple of every lattice vector is an
integer combination of the `T`.

The integer is the determinant of the matrix expressing `T` in `B`: that matrix is a change of basis
over the field, hence has nonzero determinant, and its adjugate exhibits the combinations. -/
private theorem exists_zsmul_mem_span_int {k V ι : Type*} [Field k] [CharZero k]
    [AddCommGroup V] [Module k V] [Finite ι] (B : Basis ι k V) (T : ι → V)
    (hT : ∀ j, T j ∈ Submodule.span ℤ (Set.range B))
    (hspan : Submodule.span k (Set.range T) = ⊤) :
    ∃ d : ℤ, d ≠ 0 ∧ ∀ v ∈ Submodule.span ℤ (Set.range B),
      d • v ∈ Submodule.span ℤ (Set.range T) := by
  classical
  let _ := Fintype.ofFinite ι
  choose M hM using fun j => (Submodule.mem_span_range_iff_exists_fun ℤ).mp (hT j)
  let N : Matrix ι ι ℤ := Matrix.of M
  have hMN : ∀ j, ∑ i, N j i • B i = T j := hM
  refine ⟨N.det, det_ne_zero_of_span_eq_top B T N hMN hspan, ?_⟩
  have hB : ∀ i, (N.det : ℤ) • B i ∈ Submodule.span ℤ (Set.range T) := by
    intro i
    rw [← sum_adjugate_smul_eq_det_smul N B T hMN i]
    exact Submodule.sum_mem _ fun j _ =>
      Submodule.smul_mem _ _ (Submodule.subset_span ⟨j, rfl⟩)
  intro v hv
  refine Submodule.span_induction ?_ ?_ ?_ ?_ hv
  · rintro - ⟨i, rfl⟩
    exact hB i
  · simp
  · intro x y _ _ hx hy
    rw [smul_add]
    exact Submodule.add_mem _ hx hy
  · intro c x _ hx
    rw [smul_comm]
    exact Submodule.smul_mem _ _ hx

variable {k G : Type u} [Field k] [Group G]
variable [Finite G]

variable (k G)

/-- The set of characters induced from irreducible characters of cyclic subgroups of `G`, viewed
as functions on `G`. -/
def indVirtualCharacterSetCyclic : Set (G → k) :=
  {f | ∃ χ ∈ indCharacterSet k G {C | IsCyclic C}, (χ : G → k) = f}

/-- Membership in `TauCeti.ClassFunction.indVirtualCharacterSetCyclic` reduces to membership in
the existing class-function generating set `TauCeti.ClassFunction.indCharacterSet`. -/
@[simp]
theorem mem_indVirtualCharacterSetCyclic {f : G → k} :
    f ∈ indVirtualCharacterSetCyclic k G ↔
      ∃ χ ∈ indCharacterSet k G {C | IsCyclic C}, (χ : G → k) = f :=
  Iff.rfl

/-- The additive subgroup of functions on `G` generated by characters induced from irreducible
characters of cyclic subgroups.  Artin's rational induction theorem says that a single nonzero
integer sends every virtual character into this subgroup. -/
def indVirtualCharacterSpanCyclic : AddSubgroup (G → k) :=
  AddSubgroup.closure (indVirtualCharacterSetCyclic k G)

variable {k G}

/-- A character induced from an irreducible character of a cyclic subgroup belongs to
`TauCeti.ClassFunction.indVirtualCharacterSpanCyclic`. -/
theorem ind_ofCharacter_mem_indVirtualCharacterSpanCyclic (C : Subgroup G) (hC : IsCyclic C)
    {n : ℕ} (ρ : Representation k C (Fin n → k)) (hρ : ρ.IsIrreducible) :
    ((ind C (ofCharacter ρ) : ClassFunction k G) : G → k) ∈
      indVirtualCharacterSpanCyclic k G :=
  AddSubgroup.subset_closure ⟨ind C (ofCharacter ρ),
    (mem_indCharacterSet k G).2 ⟨C, hC, n, ρ, hρ, rfl⟩, rfl⟩

/-- The universal property of `TauCeti.ClassFunction.indVirtualCharacterSpanCyclic`: it is
contained in an additive subgroup exactly when every generating cyclic-induced irreducible
character is. -/
theorem indVirtualCharacterSpanCyclic_le_iff {H : AddSubgroup (G → k)} :
    indVirtualCharacterSpanCyclic k G ≤ H ↔
      ∀ (C : Subgroup G), IsCyclic C → ∀ (n : ℕ) (ρ : Representation k C (Fin n → k)),
        ρ.IsIrreducible → ((ind C (ofCharacter ρ) : ClassFunction k G) : G → k) ∈ H := by
  rw [indVirtualCharacterSpanCyclic, AddSubgroup.closure_le]
  constructor
  · intro h C hC n ρ hρ
    exact h ⟨ind C (ofCharacter ρ),
      (mem_indCharacterSet k G).2 ⟨C, hC, n, ρ, hρ, rfl⟩, rfl⟩
  · rintro h - ⟨χ, hχ, rfl⟩
    obtain ⟨C, hC, n, ρ, hρ, rfl⟩ := (mem_indCharacterSet k G).1 hχ
    exact h C hC n ρ hρ

/-- Every generator of `TauCeti.ClassFunction.indVirtualCharacterSpanCyclic` is a genuine
character, so the generated subgroup lies in the virtual-character lattice. -/
theorem indVirtualCharacterSpanCyclic_le_virtualCharacters :
    indVirtualCharacterSpanCyclic k G ≤ virtualCharacters k G :=
  indVirtualCharacterSpanCyclic_le_iff.mpr fun C _ _ ρ _ => by
    have hof : (ofCharacter ρ : ClassFunction k C) = ofFDRep (FDRep.of ρ) :=
      (ofFDRep_eq_ofCharacter (FDRep.of ρ)).symm
    rw [hof]
    exact ind_ofFDRep_mem_virtualCharacters C (FDRep.of ρ)

section AlgClosed

variable [IsAlgClosed k] [Invertible (Nat.card G : k)]

/-- A class function that is a virtual character lies in the `ℤ`-span of the basis of irreducible
characters: the lattice is the `ℤ`-span of the irreducible characters
(`TauCeti.mem_virtualCharacters_iff`), and those are exactly the basis vectors. -/
private theorem mem_span_int_range_basisIrreducibleCharacter {f : ClassFunction k G}
    (hf : (f : G → k) ∈ virtualCharacters k G) :
    f ∈ Submodule.span ℤ (Set.range (basisIrreducibleCharacter k G)) := by
  obtain ⟨c, hc⟩ := mem_virtualCharacters_iff.mp hf
  have hbasis : ∀ i, ((basisIrreducibleCharacter k G i : ClassFunction k G) : G → k) =
      irreducibleCharacter k i := fun i => funext fun g => basisIrreducibleCharacter_apply i g
  have hsum : f = ∑ i, c i • basisIrreducibleCharacter k G i := by
    refine Subtype.ext (hc.trans (funext fun g => ?_))
    rw [Submodule.coe_sum]
    simp only [Finset.sum_apply]
    exact Finset.sum_congr rfl fun i _ => by
      rw [← Int.cast_smul_eq_zsmul k (c i), SetLike.val_smul, hbasis]
  rw [hsum]
  exact Submodule.sum_mem _ fun i _ =>
    Submodule.smul_mem _ _ (Submodule.subset_span ⟨i, rfl⟩)

end AlgClosed

private theorem exists_artin_induction_data [IsAlgClosed k] [CharZero k] :
    ∃ (d : ℤ), d ≠ 0 ∧ ∃ (m : ℕ) (C : Fin m → Subgroup G) (_ : ∀ i, IsCyclic (C i))
      (n : Fin m → ℕ) (ρ : ∀ i, Representation k (C i) (Fin (n i) → k))
      (_ : ∀ i, (ρ i).IsIrreducible), ∀ f ∈ virtualCharacters k G, ∃ c : Fin m → ℤ,
        ∑ i, c i • ((ind (C i) (ofCharacter (ρ i)) : ClassFunction k G) : G → k) = d • f := by
  classical
  have : Invertible (Nat.card G : k) :=
    invertibleOfNonzero (Nat.cast_ne_zero.mpr Nat.card_pos.ne')
  let 𝒢 := indCharacterSet k G {S | IsCyclic S}
  have hspan : Submodule.span k 𝒢 = ⊤ := by
    have hle : indCharacterSpan k G {S | IsCyclic S} ≤ Submodule.span k 𝒢 :=
      indCharacterSpan_le_iff.mpr fun S hS n ρ hρ =>
        Submodule.subset_span ((mem_indCharacterSet k G).2 ⟨S, hS, n, ρ, hρ, rfl⟩)
    rw [indCharacterSpan_cyclic_eq_top] at hle
    exact top_le_iff.mp hle
  obtain ⟨b, hbsub, hbspan, hbli⟩ := exists_linearIndependent k 𝒢
  let Bb : Basis b k (ClassFunction k G) :=
    Basis.mk hbli (by rw [Subtype.range_coe, hbspan, hspan])
  let B := basisIrreducibleCharacter k G
  let e : Fin (Nat.card (ConjClasses G)) ≃ b := B.indexEquiv Bb
  let T : Fin (Nat.card (ConjClasses G)) → ClassFunction k G := Subtype.val ∘ e
  have hTmem : ∀ i, T i ∈ 𝒢 := fun i => hbsub (e i).2
  have hTspan : Submodule.span k (Set.range T) = ⊤ := by
    have : Set.range T = b := by
      rw [Set.range_comp, e.range_eq_univ, Set.image_univ, Subtype.range_coe]
    rw [this, hbspan, hspan]
  obtain ⟨d, hd, hlattice⟩ := exists_zsmul_mem_span_int B T
    (fun j => mem_span_int_range_basisIrreducibleCharacter
      (by
        obtain ⟨S, -, n, ρ, -, hρ⟩ := (mem_indCharacterSet k G).mp (hTmem j)
        rw [← hρ]
        have hof : (ofCharacter ρ : ClassFunction k S) = ofFDRep (FDRep.of ρ) :=
          (ofFDRep_eq_ofCharacter (FDRep.of ρ)).symm
        rw [hof]
        exact ind_ofFDRep_mem_virtualCharacters S (FDRep.of ρ)))
    hTspan
  choose C hC n ρ hρ hTeq using fun i => (mem_indCharacterSet k G).mp (hTmem i)
  refine ⟨d, hd, Nat.card (ConjClasses G), C, hC, n, ρ, hρ, fun f hf => ?_⟩
  have hfmem : (⟨f, virtualCharacters_le_classFunction hf⟩ : ClassFunction k G) ∈
      Submodule.span ℤ (Set.range B) := mem_span_int_range_basisIrreducibleCharacter hf
  obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun ℤ).mp (hlattice _ hfmem)
  refine ⟨c, ?_⟩
  have hcoe := congrArg (fun F : ClassFunction k G => (F : G → k)) hc
  simpa [hTeq, Submodule.coe_sum] using hcoe

variable (k G)

/-- **Artin's induction theorem, rational form.**  Over an algebraically closed field of
characteristic zero there is a nonzero integer `d`, independent of the character, such that `d • f`
belongs to the additive subgroup generated by characters induced from irreducible characters of
cyclic subgroups, for every virtual character `f`.  Equivalently, after inverting `d`, the induction
map `⨁_{C cyclic} R(C) → R(G)` is surjective.

The sharp form takes `d = |G|`; that is not proved here. -/
theorem exists_zsmul_mem_indVirtualCharacterSpanCyclic [IsAlgClosed k] [CharZero k] :
    ∃ d : ℤ, d ≠ 0 ∧ ∀ f ∈ virtualCharacters k G,
      d • f ∈ indVirtualCharacterSpanCyclic k G := by
  obtain ⟨d, hd, m, C, hC, n, ρ, hρ, h⟩ := exists_artin_induction_data (k := k) (G := G)
  refine ⟨d, hd, fun f hf => ?_⟩
  obtain ⟨c, hc⟩ := h f hf
  rw [← hc]
  exact AddSubgroup.sum_mem _ fun i _ =>
    AddSubgroup.zsmul_mem _
      (ind_ofCharacter_mem_indVirtualCharacterSpanCyclic (C i) (hC i) (ρ i) (hρ i)) (c i)

/-- The explicit finite-combination form of
`TauCeti.ClassFunction.exists_zsmul_mem_indVirtualCharacterSpanCyclic`.  The cyclic subgroups and
irreducible representations are chosen once and work for every virtual character; only the integer
coefficients depend on the character. -/
theorem exists_sum_zsmul_ind_ofCharacter_eq_zsmul_cyclic [IsAlgClosed k] [CharZero k] :
    ∃ (d : ℤ), d ≠ 0 ∧ ∃ (m : ℕ) (C : Fin m → Subgroup G) (_ : ∀ i, IsCyclic (C i))
      (n : Fin m → ℕ) (ρ : ∀ i, Representation k (C i) (Fin (n i) → k))
      (_ : ∀ i, (ρ i).IsIrreducible), ∀ f ∈ virtualCharacters k G, ∃ c : Fin m → ℤ,
        ∑ i, c i • ((ind (C i) (ofCharacter (ρ i)) : ClassFunction k G) : G → k) = d • f :=
  exists_artin_induction_data

end ClassFunction

end TauCeti
