/-
Copyright (c) 2026 Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Claude
-/
module

public import TauCeti.RepresentationTheory.CharacterTable.Completeness
public import TauCeti.RepresentationTheory.Induction.FrobeniusReciprocity
public import Mathlib.GroupTheory.SpecificGroups.Cyclic.Basic
public import Mathlib.LinearAlgebra.BilinearForm.Orthogonal

/-!
# Induction from a covering family of subgroups spans the class functions

Let `𝒮` be a family of subgroups of a finite group `G` that **covers `G` up to conjugacy**: every
element of `G` has a conjugate lying in some member of `𝒮`.  Over a field `k` in which `|G|` is
invertible, induction from `𝒮` is then surjective on class functions: the class functions
`Ind_S^G ψ`, for `S ∈ 𝒮` and `ψ` a class function of `S`, span all class functions of `G`
(`TauCeti.ClassFunction.indSpan_eq_top`).

The proof is the classical duality argument.  The character pairing is nondegenerate, so the span is
everything as soon as nothing nonzero is orthogonal to it.  Frobenius reciprocity converts
orthogonality to *every* class function induced from `S` into the vanishing of the restriction of
`h` to `S`, and a class function whose restriction to every member of `𝒮` vanishes is zero, because
each `x` is conjugate into some member and a class function is constant on conjugacy classes.

The cyclic subgroups cover `G`, for the trivial reason that `x` generates a cyclic subgroup
containing it, so the class functions induced from them span
(`TauCeti.ClassFunction.indSpan_cyclic_eq_top`).  The covering hypothesis is stated for a general
family because the elementary subgroups, which Brauer's induction theorem uses, satisfy it too.

Over an algebraically closed `k` the spanning set can be cut down to genuine induced *characters*:
the irreducible characters of `S` span the class functions of `S`, so
`TauCeti.ClassFunction.indCharacterSpan_cyclic_eq_top` says that the characters induced from the
irreducible characters of the cyclic subgroups already span.

## What this is not: Artin's induction theorem

Artin's induction theorem is the sharper *arithmetic* statement, about the virtual-character
lattice `TauCeti.virtualCharacters` rather than about the class functions: over a
characteristic-zero splitting field, `|G| • χ` is a `ℤ`-linear combination of characters induced
from cyclic subgroups.  The rational form says that every character is a `ℚ`-linear combination
of them — equivalently, that some nonzero integer multiple is an integral combination — or that
`⨁_{C cyclic} R(C) → R(G)` is surjective after tensoring with `ℚ`.  The `|G|` statement is strictly
sharper.  **Nothing below says
anything about the arithmetic of the coefficients**: every result here produces coefficients that
are arbitrary elements of `k`.

What this file supplies is the duality half of that development, run on the class functions instead
of on `ℚ ⊗ R(G)`.  `TauCeti.RepresentationTheory.Induction.Artin` is the arithmetic half: it
descends `TauCeti.ClassFunction.indCharacterSpan_cyclic_eq_top` to the virtual-character lattice
and obtains the rational form of Artin's theorem.  The sharp form, with the denominator identified
as `|G|`, remains open, as do Brauer's induction theorem and Brauer's characterization of
characters.  The covering-family formulation is stated here for its own sake: the elementary
subgroups Brauer's theorem uses satisfy the same hypothesis.

## Main definitions

* `TauCeti.ClassFunction.indSpan`: the submodule of class functions of `G` spanned by the class
  functions induced from a family `𝒮` of subgroups.
* `TauCeti.ClassFunction.indCharacterSpan`: the smaller submodule generated by inductions of only
  irreducible characters of the members of `𝒮`.

## Main statements

* `TauCeti.ClassFunction.indSpan_eq_top`: induction from a family of subgroups covering `G` up
  to conjugacy spans all class functions, and
  `TauCeti.ClassFunction.indSpan_cyclic_eq_top`: its cyclic case, with
  `TauCeti.ClassFunction.exists_sum_smul_ind_cyclic` the explicit finite-combination form.
* `TauCeti.ClassFunction.indCharacterSpan_eq_indSpan`: over an algebraically closed field in which
  the orders of the selected subgroups are invertible,
  inducing only the irreducible characters of the subgroups spans as much as inducing all their
  class functions, whence `TauCeti.ClassFunction.indCharacterSpan_eq_top` and
  `TauCeti.ClassFunction.indCharacterSpan_cyclic_eq_top`, with
  `TauCeti.ClassFunction.exists_sum_smul_ind_ofCharacter_cyclic` the explicit form.

## Implementation notes

Only the invertibility of `|G|` in `k` is assumed for the first form; no algebraic closure is
needed, because the duality argument runs on
`TauCeti.ClassFunction.characterPairing_nondegenerate` alone.  Algebraic closure enters only in the
refinement to induced characters, where completeness of the irreducible characters of the subgroup
is used.  That refinement needs no assumption on `|G|` at all, only invertibility of the orders of
the members of `𝒮`, so it takes that as an explicit hypothesis rather than an ambient instance; the
covering corollaries supply it from `TauCeti.isUnit_natCard_subgroup`.

The covering hypothesis is written out as `∀ x : G, ∃ S ∈ 𝒮, ∃ y : G, y * x * y⁻¹ ∈ S` rather than
bundled into a predicate: it is used once, and the cyclic instance discharges it with `y = 1`.

The coefficients produced here are elements of `k`, and the statements are about the `k`-vector
space of class functions, not about `TauCeti.virtualCharacters`; see the discussion above of what
separates this from Artin's induction theorem.

## References

This is the duality step of the "Artin's induction theorem" item of Layer 6 in
`TauCetiRoadmap/RepresentationTheory/InductionRestriction/README.md`, which asks for the
`ℤ`-membership of `|G| • χ` in the subgroup generated by cyclic-induced characters and, separately,
for the rational surjectivity of `⨁_{C cyclic} R(C) → R(G)`.  The second of those is deduced from
the results here in `TauCeti.RepresentationTheory.Induction.Artin`; the first is not proved.

* J.-P. Serre, *Linear Representations of Finite Groups*, Springer GTM 42 (1977), Section 9.2,
  Theorem 17, whose duality argument this follows.  Serre runs it on `ℚ ⊗ R(G)`, which is what
  makes his conclusion the rational one; here it runs on the class functions over `k`.
* C. W. Curtis, I. Reiner, *Methods of Representation Theory, Vol. I*, Wiley (1981), Section 15.
-/

public section

namespace TauCeti

namespace ClassFunction

universe u v

variable (k : Type u) (G : Type v) [Field k] [Group G] [Finite G]

/-! ### Class functions induced from a family of subgroups -/

/-- The set of class functions of `G` induced from the members of a family `𝒮` of subgroups. -/
def indSet (𝒮 : Set (Subgroup G)) : Set (ClassFunction k G) :=
  {f | ∃ S ∈ 𝒮, ∃ ψ : ClassFunction k S, ind S ψ = f}

/-- The submodule generated by `TauCeti.ClassFunction.indSet`. -/
noncomputable def indSpan (𝒮 : Set (Subgroup G)) : Submodule k (ClassFunction k G) :=
  Submodule.span k (indSet k G 𝒮)

/-- Membership in the generating set for `TauCeti.ClassFunction.indSpan`. -/
@[simp]
theorem mem_indSet {𝒮 : Set (Subgroup G)} {f : ClassFunction k G} :
    f ∈ indSet k G 𝒮 ↔ ∃ S ∈ 𝒮, ∃ ψ : ClassFunction k S, ind S ψ = f :=
  Iff.rfl

variable {k G}

/-- A class function induced from a member of `𝒮` lies in `TauCeti.ClassFunction.indSpan`, the
submodule these generate. -/
theorem ind_mem_indSpan {𝒮 : Set (Subgroup G)} {S : Subgroup G} (hS : S ∈ 𝒮)
    (ψ : ClassFunction k S) :
    ind S ψ ∈ indSpan k G 𝒮 :=
  Submodule.subset_span ⟨S, hS, ψ, rfl⟩

/-- The universal property of `TauCeti.ClassFunction.indSpan`: it is contained in a submodule
exactly when every class function induced from a member of `𝒮` is. -/
theorem indSpan_le_iff {𝒮 : Set (Subgroup G)} {p : Submodule k (ClassFunction k G)} :
    indSpan k G 𝒮 ≤ p ↔ ∀ S ∈ 𝒮, ∀ ψ : ClassFunction k S, ind S ψ ∈ p := by
  refine ⟨fun h S hS ψ => h (ind_mem_indSpan hS ψ), fun h => Submodule.span_le.mpr ?_⟩
  rintro - ⟨S, hS, ψ, rfl⟩
  exact h S hS ψ

/-- **A class function orthogonal to every induction from `𝒮` vanishes**, when `𝒮` covers `G` up to
conjugacy.  Frobenius reciprocity turns orthogonality to all of `Ind_S^G (ClassFunction k S)` into
orthogonality of the restriction of `h` to `S` against all class functions of `S`, so that
restriction is zero by nondegeneracy of the pairing on `S`.  Any conjugate of `x` lying in `S` then
evaluates `h` at `x`. -/
theorem eq_zero_of_characterPairing_indSpan_eq_zero [Invertible (Nat.card G : k)]
    {𝒮 : Set (Subgroup G)}
    (h𝒮 : ∀ x : G, ∃ S ∈ 𝒮, ∃ y : G, y * x * y⁻¹ ∈ S) {h : ClassFunction k G}
    (hh : ∀ f ∈ indSpan k G 𝒮,
      (@characterPairing k G _ _ (Fintype.ofFinite G)) f h = 0) :
    h = 0 := by
  classical
  let _ := Fintype.ofFinite G
  have hG : IsUnit (Nat.card G : k) := isUnit_of_invertible _
  refine Subtype.ext (funext fun x => ?_)
  obtain ⟨S, hS, y, hy⟩ := h𝒮 x
  have hres : comap S.subtype h = 0 := by
    let : Invertible (Nat.card S : k) := (isUnit_natCard_subgroup _ hG).invertible
    refine characterPairing_nondegenerate.2 _ fun ψ => ?_
    rw [← characterPairing_ind hG ψ h]
    exact hh _ (ind_mem_indSpan hS ψ)
  have hzero := congrArg (fun f : ClassFunction k S => f.1 ⟨y * x * y⁻¹, hy⟩) hres
  rw [← mem_iff.mp h.2 x y]
  simpa using hzero

/-- **Induction from a covering family of subgroups is surjective on class functions.**  If every
element of the finite group `G` is conjugate into a member of `𝒮`, and `|G|` is invertible in `k`,
then the class functions induced from the members of `𝒮` span all class functions of `G`.

`TauCeti.ClassFunction.indSpan_cyclic_eq_top` is the case of the cyclic subgroups; the family of
elementary subgroups, which Brauer's induction theorem uses, satisfies the same hypothesis. -/
theorem indSpan_eq_top [Invertible (Nat.card G : k)] {𝒮 : Set (Subgroup G)}
    (h𝒮 : ∀ x : G, ∃ S ∈ 𝒮, ∃ y : G, y * x * y⁻¹ ∈ S) :
    indSpan k G 𝒮 = ⊤ := by
  let := Fintype.ofFinite G
  have hrefl := (characterPairing_isSymm (k := k) (G := G)).isRefl
  have hbot : (characterPairing (k := k) (G := G)).orthogonal (indSpan k G 𝒮) = ⊥ :=
    (Submodule.eq_bot_iff _).mpr fun _ hh =>
      eq_zero_of_characterPairing_indSpan_eq_zero h𝒮 fun f hf =>
        LinearMap.BilinForm.mem_orthogonal_iff.mp hh f hf
  calc indSpan k G 𝒮
      = (characterPairing (k := k) (G := G)).orthogonal
          ((characterPairing (k := k) (G := G)).orthogonal (indSpan k G 𝒮)) :=
        (LinearMap.BilinForm.orthogonal_orthogonal characterPairing_nondegenerate hrefl _).symm
    _ = ⊤ := by rw [hbot, LinearMap.BilinForm.orthogonal_bot]

/-- **The class functions induced from the cyclic subgroups span.**  Over a field in which the order
of the finite group `G` is invertible, the class functions induced from the cyclic subgroups of `G`
span all class functions of `G`; equivalently, the induction map
`⨁_{C cyclic} ClassFunction k C → ClassFunction k G` is surjective.

The explicit finite-combination form is `TauCeti.ClassFunction.exists_sum_smul_ind_cyclic`, and
`TauCeti.ClassFunction.indCharacterSpan_cyclic_eq_top` refines the spanning set to induced
characters.

This is *not* Artin's induction theorem: the coefficients here are arbitrary elements of `k`, while
Artin's theorem is a statement about `TauCeti.virtualCharacters`, asserting that they may be taken
rational and that `|G| • χ` is an integral combination of induced characters.  The rational form is
deduced from the induced-character refinement below in
`TauCeti.RepresentationTheory.Induction.Artin`; the integral form remains open. -/
theorem indSpan_cyclic_eq_top [Invertible (Nat.card G : k)] :
    indSpan k G {S | IsCyclic S} = ⊤ :=
  indSpan_eq_top fun x =>
    ⟨Subgroup.zpowers x, Subgroup.isCyclic_zpowers x, 1, by simp⟩

/-- `TauCeti.ClassFunction.indSpan_cyclic_eq_top` written out: every class function of `G` is a
finite `k`-linear combination of class functions induced from cyclic subgroups. -/
theorem exists_sum_smul_ind_cyclic [Invertible (Nat.card G : k)] (f : ClassFunction k G) :
    ∃ (n : ℕ) (C : Fin n → Subgroup G) (_ : ∀ i, IsCyclic (C i))
      (ψ : ∀ i, ClassFunction k (C i)) (c : Fin n → k),
      ∑ i, c i • ind (C i) (ψ i) = f := by
  have hf : f ∈ indSpan k G {S | IsCyclic S} :=
    (indSpan_cyclic_eq_top (k := k) (G := G)).symm ▸ Submodule.mem_top
  obtain ⟨n, c, g, hg⟩ := Submodule.mem_span_set'.mp hf
  choose C hC ψ hψ using fun i => (g i).2
  exact ⟨n, C, hC, ψ, c, by simpa only [hψ] using hg⟩

/-! ### Characters induced from a family of subgroups -/

variable (k G)

/-- The set of characters induced from the irreducible characters of the members of a family `𝒮`
of subgroups of `G`. -/
def indCharacterSet (𝒮 : Set (Subgroup G)) : Set (ClassFunction k G) :=
  {f | ∃ S ∈ 𝒮, ∃ (n : ℕ) (ρ : Representation k S (Fin n → k)),
    ρ.IsIrreducible ∧ ind S (ofCharacter ρ) = f}

/-- The submodule of class functions of `G` spanned by the characters induced from the irreducible
characters of the members of a family `𝒮` of subgroups of `G`.

This is contained in `TauCeti.ClassFunction.indSpan`, and over an algebraically closed field in
which the orders of the selected subgroups are invertible the two agree
(`TauCeti.ClassFunction.indCharacterSpan_eq_indSpan`).

As in `TauCeti.ClassFunction.le_span_irreducibleCharacters`, the irreducibles are taken on the
coordinate spaces `Fin n → k`, which is where the Wedderburn presentation of the group algebra
produces them. -/
noncomputable def indCharacterSpan (𝒮 : Set (Subgroup G)) : Submodule k (ClassFunction k G) :=
  Submodule.span k (indCharacterSet k G 𝒮)

/-- Membership in the generating set for `TauCeti.ClassFunction.indCharacterSpan`. -/
@[simp]
theorem mem_indCharacterSet {𝒮 : Set (Subgroup G)} {f : ClassFunction k G} :
    f ∈ indCharacterSet k G 𝒮 ↔
      ∃ S ∈ 𝒮, ∃ (n : ℕ) (ρ : Representation k S (Fin n → k)),
        ρ.IsIrreducible ∧ ind S (ofCharacter ρ) = f :=
  Iff.rfl

variable {k G}

/-- A character induced from an irreducible character of a member of `𝒮` lies in
`TauCeti.ClassFunction.indCharacterSpan`, the submodule these generate. -/
theorem ind_ofCharacter_mem_indCharacterSpan {𝒮 : Set (Subgroup G)} {S : Subgroup G}
    (hS : S ∈ 𝒮) {n : ℕ} (ρ : Representation k S (Fin n → k)) (hρ : ρ.IsIrreducible) :
    ind S (ofCharacter ρ) ∈ indCharacterSpan k G 𝒮 :=
  Submodule.subset_span ⟨S, hS, n, ρ, hρ, rfl⟩

/-- The universal property of `TauCeti.ClassFunction.indCharacterSpan`: it is contained in a
submodule exactly when every character induced from an irreducible character of a member of `𝒮`
is. -/
theorem indCharacterSpan_le_iff {𝒮 : Set (Subgroup G)}
    {p : Submodule k (ClassFunction k G)} :
    indCharacterSpan k G 𝒮 ≤ p ↔ ∀ S ∈ 𝒮, ∀ (n : ℕ) (ρ : Representation k S (Fin n → k)),
      ρ.IsIrreducible → ind S (ofCharacter ρ) ∈ p := by
  refine ⟨fun h S hS n ρ hρ => h (ind_ofCharacter_mem_indCharacterSpan hS ρ hρ),
    fun h => Submodule.span_le.mpr ?_⟩
  rintro - ⟨S, hS, n, ρ, hρ, rfl⟩
  exact h S hS n ρ hρ

/-- A character is a class function, so inducing only the irreducible characters of the members of
`𝒮` spans no more than inducing all their class functions. -/
theorem indCharacterSpan_le_indSpan (𝒮 : Set (Subgroup G)) :
    indCharacterSpan k G 𝒮 ≤ indSpan k G 𝒮 :=
  indCharacterSpan_le_iff.mpr fun _ hS _ ρ _ => ind_mem_indSpan hS (ofCharacter ρ)

/-- Inducing an arbitrary class function of a subgroup gains nothing over inducing its irreducible
characters: over an algebraically closed field the latter already span the class functions of the
subgroup, and induction is linear.

Only the orders of the *selected* subgroups need be invertible in `k`; `|G|` itself is irrelevant
here, and the covering corollaries below supply the hypothesis from
`TauCeti.isUnit_natCard_subgroup`. -/
theorem indSpan_le_indCharacterSpan [IsAlgClosed k] {𝒮 : Set (Subgroup G)}
    (h𝒮 : ∀ S ∈ 𝒮, IsUnit (Nat.card S : k)) :
    indSpan k G 𝒮 ≤ indCharacterSpan k G 𝒮 := by
  refine indSpan_le_iff.mpr fun S hS ψ => ?_
  let : Invertible (Nat.card S : k) := (h𝒮 S hS).invertible
  let := Fintype.ofFinite (ConjClasses S)
  obtain ⟨d, ρ, b, hirr, hb⟩ := exists_basis_ofCharacter k S
  have hsum : ψ = ∑ D, b.repr ψ D • ofCharacter (ρ D) := by
    conv_lhs => rw [← b.sum_repr ψ]
    exact Finset.sum_congr rfl fun D _ => by rw [hb D]
  rw [hsum, map_sum]
  refine Submodule.sum_mem _ fun D _ => ?_
  rw [map_smul]
  exact Submodule.smul_mem _ _
    (ind_ofCharacter_mem_indCharacterSpan hS (ρ D) (hirr D))

/-- Over an algebraically closed field, inducing the irreducible characters of the members of `𝒮`
spans exactly as much as inducing all their class functions.  As in
`TauCeti.ClassFunction.indSpan_le_indCharacterSpan`, only the orders of the members of `𝒮`
need be invertible. -/
theorem indCharacterSpan_eq_indSpan [IsAlgClosed k] {𝒮 : Set (Subgroup G)}
    (h𝒮 : ∀ S ∈ 𝒮, IsUnit (Nat.card S : k)) :
    indCharacterSpan k G 𝒮 = indSpan k G 𝒮 :=
  le_antisymm (indCharacterSpan_le_indSpan 𝒮) (indSpan_le_indCharacterSpan h𝒮)

/-- **Induction of irreducible characters from a covering family of subgroups already spans the
class functions**, over an algebraically closed field in which `|G|` is invertible. -/
theorem indCharacterSpan_eq_top [IsAlgClosed k] [Invertible (Nat.card G : k)]
    {𝒮 : Set (Subgroup G)} (h𝒮 : ∀ x : G, ∃ S ∈ 𝒮, ∃ y : G, y * x * y⁻¹ ∈ S) :
    indCharacterSpan k G 𝒮 = ⊤ :=
  top_le_iff.mp ((indSpan_eq_top h𝒮).ge.trans
    (indSpan_le_indCharacterSpan fun S _ =>
      isUnit_natCard_subgroup S (isUnit_of_invertible _)))

/-- **The characters induced from the irreducible characters of the cyclic subgroups span.**  Over
an algebraically closed field in which the order of the finite group `G` is invertible, they span
all class functions of `G`.

In particular every character of `G` is a `k`-linear combination of characters induced from cyclic
subgroups; `TauCeti.ClassFunction.exists_sum_smul_ind_ofCharacter_cyclic` writes that combination
out. The coefficients are arbitrary elements of `k`. Artin's induction theorem asserts that they
may be taken rational, and
`TauCeti.ClassFunction.exists_sum_zsmul_ind_ofCharacter_eq_zsmul_cyclic` deduces that from this
statement by a lattice descent. -/
theorem indCharacterSpan_cyclic_eq_top [IsAlgClosed k] [Invertible (Nat.card G : k)] :
    indCharacterSpan k G {S | IsCyclic S} = ⊤ :=
  indCharacterSpan_eq_top fun x =>
    ⟨Subgroup.zpowers x, Subgroup.isCyclic_zpowers x, 1, by simp⟩

/-- `TauCeti.ClassFunction.indCharacterSpan_cyclic_eq_top` written out over an algebraically closed
field: every class function of `G` — in particular, by `TauCeti.ClassFunction.ofCharacter`, every
character of `G` — is a finite `k`-linear combination of characters induced from irreducible
characters of cyclic subgroups. -/
theorem exists_sum_smul_ind_ofCharacter_cyclic [IsAlgClosed k] [Invertible (Nat.card G : k)]
    (f : ClassFunction k G) :
    ∃ (n : ℕ) (C : Fin n → Subgroup G) (_ : ∀ i, IsCyclic (C i)) (d : Fin n → ℕ)
      (ρ : ∀ i, Representation k (C i) (Fin (d i) → k)) (_ : ∀ i, (ρ i).IsIrreducible)
      (c : Fin n → k),
      ∑ i, c i • ind (C i) (ofCharacter (ρ i)) = f := by
  have hf : f ∈ indCharacterSpan k G {S | IsCyclic S} :=
    (indCharacterSpan_cyclic_eq_top (k := k) (G := G)).symm ▸ Submodule.mem_top
  obtain ⟨n, c, g, hg⟩ := Submodule.mem_span_set'.mp hf
  choose C hC d ρ hρ hfg using fun i => (g i).2
  exact ⟨n, C, hC, d, ρ, hρ, c, by simpa only [hfg] using hg⟩

end ClassFunction

end TauCeti
