/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import Mathlib.RingTheory.Binomial
public import TauCeti.Algebra.Ring.Subgroup

/-!
# Products of generalized binomial coefficients

This file gives the linearization formula for the product of two generalized binomial
coefficients in a binomial ring. The formula reads

```text
(r choose m) (r choose n) =
  ∑ i + j = n, (m choose j) (m + i choose m) (r choose (m + i)).
```

The coefficients are natural numbers. Consequently the additive subgroup spanned by the
coefficients `(r choose n)` is already a subring. This integral form is the Cartan--Cartan
multiplication rule used when normal-ordering the generators of the Kostant integral form:
products of the generators `(h choose n)` remain integral linear combinations of generators of
the same kind.

The proof combines Mathlib's Chu--Vandermonde identity `Ring.add_choose_eq` with its shifted
factorization `Ring.choose_smul_choose`. No polynomial expansion or division by factorials is
needed.

## Main results

* `TauCeti.ringChoose_mul_ringChoose`: the product of two binomial coefficients in `r`, expanded
  as a natural-number linear combination of binomial coefficients in `r`.
* `TauCeti.ringChooseSpan`: the additive subgroup spanned by the binomial coefficients in one
  element.
* `TauCeti.mul_mem_ringChooseSpan`: that span is closed under multiplication.
* `TauCeti.toAddSubgroup_subringClosure_range_ringChoose`: the subring generated by the binomial
  coefficients in `r` has no additive elements beyond this span.

## References

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §26.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.
-/

public section

namespace TauCeti

open Finset

variable {R : Type*}

section Product

variable [Ring R] [BinomialRing R]

/-- The product of two generalized binomial coefficients, expanded as an integral linear
combination of generalized binomial coefficients in the same element.

The pair `(i, j)` runs over `i + j = n`. Thus the summand has binomial degree `m + i` and
coefficient `(m choose j) * (m + i choose m)`. Terms with `m < j` vanish automatically. -/
theorem ringChoose_mul_ringChoose (r : R) (m n : ℕ) :
    Ring.choose r m * Ring.choose r n =
      ∑ ij ∈ antidiagonal n,
        (Nat.choose m ij.2 * Nat.choose (m + ij.1) m) • Ring.choose r (m + ij.1) := by
  have hcomm : Commute (r - (m : R)) (m : R) :=
    (Nat.cast_commute m r).symm.sub_left (Commute.refl (m : R))
  calc
    Ring.choose r m * Ring.choose r n =
        Ring.choose r m * Ring.choose ((r - (m : R)) + (m : R)) n := by
      rw [sub_add_cancel]
    _ = Ring.choose r m *
        ∑ ij ∈ antidiagonal n,
          Ring.choose (r - (m : R)) ij.1 * Ring.choose (m : R) ij.2 := by
      rw [Ring.add_choose_eq n hcomm]
    _ = ∑ ij ∈ antidiagonal n,
        Ring.choose r m *
          (Ring.choose (r - (m : R)) ij.1 * Ring.choose (m : R) ij.2) := by
      rw [mul_sum]
    _ = ∑ ij ∈ antidiagonal n,
        (Nat.choose m ij.2 * Nat.choose (m + ij.1) m) •
          Ring.choose r (m + ij.1) := by
      apply sum_congr rfl
      intro ij _
      rw [Ring.choose_natCast, ← mul_assoc]
      rw [← (Nat.cast_commute (Nat.choose m ij.2)
        (Ring.choose r m * Ring.choose (r - (m : R)) ij.1)).eq]
      rw [← nsmul_eq_mul]
      have hproduct :
          Nat.choose (m + ij.1) m • Ring.choose r (m + ij.1) =
            Ring.choose r m * Ring.choose (r - (m : R)) ij.1 := by
        simpa using Ring.choose_smul_choose r (Nat.le_add_right m ij.1)
      rw [← hproduct, smul_smul]

end Product

/-! ## The integral span -/

section Span

variable [AddCommGroupWithOne R] [Pow R ℕ] [BinomialRing R]

/-- The additive subgroup spanned by all generalized binomial coefficients in `r`. -/
def ringChooseSpan (r : R) : AddSubgroup R :=
  AddSubgroup.closure (Set.range (Ring.choose r))

/-- The integral span is the additive closure of the generalized binomial coefficients. -/
theorem ringChooseSpan_def (r : R) :
    ringChooseSpan r = AddSubgroup.closure (Set.range (Ring.choose r)) :=
  (rfl)

/-- Every generalized binomial coefficient in `r` belongs to its integral span. -/
@[simp]
theorem ringChoose_mem_ringChooseSpan (r : R) (n : ℕ) :
    Ring.choose r n ∈ ringChooseSpan r :=
  AddSubgroup.subset_closure ⟨n, rfl⟩

/-- The integral span of the generalized binomial coefficients in `r` lies in an additive
subgroup exactly when that subgroup contains every such coefficient. -/
@[simp]
theorem ringChooseSpan_le_iff {A : AddSubgroup R} {r : R} :
    ringChooseSpan r ≤ A ↔ ∀ n, Ring.choose r n ∈ A :=
  ⟨fun h n => h (ringChoose_mem_ringChooseSpan r n),
    fun h => (AddSubgroup.closure_le _).2 (Set.range_subset_iff.2 h)⟩

end Span

section One

variable [NonAssocRing R] [Pow R ℕ] [NatPowAssoc R] [BinomialRing R]

/-- The integral span of the generalized binomial coefficients contains one. -/
@[simp]
theorem one_mem_ringChooseSpan (r : R) : 1 ∈ ringChooseSpan r := by
  rw [← Ring.choose_zero_right r]
  exact ringChoose_mem_ringChooseSpan r 0

end One

section Subring

variable [Ring R] [BinomialRing R]

/-- The integral span of the generalized binomial coefficients is closed under multiplication.

This is the algebraic content of `ringChoose_mul_ringChoose`: its natural-number coefficients act by
repeated addition, so every product of spanning generators remains in the same additive span. -/
theorem mul_mem_ringChooseSpan (r : R) {x y : R} (hx : x ∈ ringChooseSpan r)
    (hy : y ∈ ringChooseSpan r) : x * y ∈ ringChooseSpan r := by
  rw [ringChooseSpan_def] at hx hy ⊢
  refine AddSubgroup.mul_mem_closure_of_mul_mem ?_ hx hy
  rintro _ ⟨m, rfl⟩ _ ⟨n, rfl⟩
  rw [ringChoose_mul_ringChoose]
  have generator_mem (k : ℕ) :
      Ring.choose r k ∈ AddSubgroup.closure (Set.range (Ring.choose r)) :=
    AddSubgroup.subset_closure ⟨k, rfl⟩
  exact sum_mem fun ij _ => AddSubgroup.nsmul_mem _
    (generator_mem (m + ij.1)) _

/-- The subring generated by the generalized binomial coefficients in one element `r` is, as an
additive subgroup, exactly their integral span: no products or powers of these coefficients
escape the span they already generate additively. -/
@[simp]
theorem toAddSubgroup_subringClosure_range_ringChoose (r : R) :
    (Subring.closure (Set.range (Ring.choose r))).toAddSubgroup = ringChooseSpan r := by
  rw [ringChooseSpan_def]
  apply Subring.toAddSubgroup_closure_of_one_mem_of_mul_mem
  · rw [← ringChooseSpan_def]
    exact one_mem_ringChooseSpan r
  · rintro _ ⟨m, rfl⟩ _ ⟨n, rfl⟩
    rw [← ringChooseSpan_def]
    exact mul_mem_ringChooseSpan r
      (ringChoose_mem_ringChooseSpan r m) (ringChoose_mem_ringChooseSpan r n)

/-- Membership in the subring generated by the generalized binomial coefficients in `r` is
membership in their integral additive span. -/
@[simp]
theorem mem_subringClosure_range_ringChoose_iff {r x : R} :
    x ∈ Subring.closure (Set.range (Ring.choose r)) ↔ x ∈ ringChooseSpan r := by
  rw [← Subring.mem_toAddSubgroup, toAddSubgroup_subringClosure_range_ringChoose]

end Subring

end TauCeti

public section

/-!
# Identities for generalized binomial coefficients

In a binomial ring, Mathlib's `Ring.choose_neg` writes `(-r choose n)` as a sign times the
*multichoose* coefficient of `r`, which is `(r + n - 1 choose n)`. This file takes the last step
and expands that coefficient by the Chu--Vandermonde identity, so that `(-r choose n)` becomes an
integer combination of the coefficients `(r choose k)` for `k ≤ n`, with the ordinary binomial
coefficients of `n - 1` as its weights.

The consequence, `TauCeti.Ring.choose_neg_mem`, is the form a consumer uses: a subring containing
`(r choose k)` for every `k ≤ n` contains `(-r choose n)` as well. That is what makes the Cartan
generators of a Kostant integral form stable under the antipode of an enveloping algebra, since
the antipode negates each Cartan vector.

The file also records a weighted form of Pascal's identity.  Its two terms are exactly the
adjacent coefficients that arise when one more raising operator is moved through a rank-one
Kostant normal-ordering sum: the first keeps the summation index and the second increments it.
The identity combines them without division, which is the integral step needed in the induction.

## Main results

* `TauCeti.Ring.choose_neg_succ_eq_sum`: the expansion of `(-r choose (n + 1))` as a signed
  Chu--Vandermonde sum of the coefficients `(r choose k)`.
* `TauCeti.Ring.choose_neg_mem`: a subring containing the coefficients of `r` up to degree `n`
  contains the degree-`n` coefficient of `-r`.
* `TauCeti.Ring.closure_range_choose_neg`: the subring generated by the coefficients of `r` and
  the one generated by the coefficients of `-r` coincide.
* `TauCeti.Ring.mul_weighted_choose_add_mul_choose`: a scalar-weighted Pascal identity.

## References

* J. Elliott, *Binomial rings, integer-valued polynomials, and λ-rings*, J. Pure Appl. Algebra
  **207** (2006), 165–185.
* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §26.2, for the
  rank-one Kostant normal-ordering formula that consumes the weighted identity.
-/

namespace TauCeti.Ring

open Finset

/-! ## Weighted Pascal identities -/

section WeightedPascal

variable {R : Type*} [NonAssocRing R] [Pow R ℕ] [NatPowAssoc R] [BinomialRing R]

/-- A scalar-weighted form of Pascal's identity:

```text
c (r - 1 choose k + 1) + (r + c) (r - 1 choose k)
  = c (r choose k + 1) + (k + 1) (r choose k + 1).
```

No commutativity between `c` and `r` is needed: every occurrence of `c` is on the left. -/
@[simp]
theorem mul_weighted_choose_add_mul_choose (r c : R) (k : ℕ) :
    c * _root_.Ring.choose (r - 1) (k + 1) +
        (r + c) * _root_.Ring.choose (r - 1) k =
      c * _root_.Ring.choose r (k + 1) +
        (k + 1) • _root_.Ring.choose r (k + 1) := by
  have hmul :
      (k + 1) • _root_.Ring.choose r (k + 1) =
        r * _root_.Ring.choose (r - 1) k := by
    simpa [Nat.choose_one_right] using
      _root_.Ring.choose_smul_choose r (n := k + 1) (k := 1) (by omega)
  rw [add_mul, ← hmul]
  have hpascal : _root_.Ring.choose r (k + 1) =
      _root_.Ring.choose (r - 1) k + _root_.Ring.choose (r - 1) (k + 1) := by
    simpa only [sub_add_cancel] using _root_.Ring.choose_succ_succ (r - 1) k
  rw [hpascal]
  rw [mul_add]
  abel

end WeightedPascal

/-! ## Negating the argument -/

variable {R : Type*} [Ring R] [BinomialRing R]

/-- Negating the argument of a generalized binomial coefficient of positive degree expands, by
Chu--Vandermonde, into a signed sum of the coefficients of the original argument weighted by
ordinary binomial coefficients of `n`.

The degree is written as `n + 1` because the multichoose shift `r + n - 1` of
`Ring.choose_neg` is a natural-number translate of `r` only in positive degree. Degree zero is
`Ring.choose_zero_right` on both sides. -/
theorem choose_neg_succ_eq_sum (r : R) (n : ℕ) :
    _root_.Ring.choose (-r) (n + 1) = Int.negOnePow (n + 1) •
      ∑ ij ∈ antidiagonal (n + 1),
        _root_.Ring.choose r ij.1 * (n.choose ij.2 : R) := by
  rw [_root_.Ring.choose_neg]
  congr 1
  have hshift : r + ((n + 1 : ℕ) : R) - 1 = r + (n : R) := by push_cast; abel
  rw [hshift, _root_.Ring.add_choose_eq _ (Nat.cast_commute n r).symm]
  exact sum_congr rfl fun ij _ => by rw [_root_.Ring.choose_natCast]

/-- A subring containing the generalized binomial coefficients of `r` up to degree `n` contains
the degree-`n` coefficient of `-r`. -/
theorem choose_neg_mem {S : Subring R} {r : R} {n : ℕ}
    (hr : ∀ k ≤ n, _root_.Ring.choose r k ∈ S) :
    _root_.Ring.choose (-r) n ∈ S := by
  cases n with
  | zero => simp
  | succ n =>
    rw [choose_neg_succ_eq_sum, Units.smul_def]
    exact Subring.zsmul_mem _
      (sum_mem fun ij hij =>
        S.mul_mem (hr ij.1 (HasAntidiagonal.antidiagonal.fst_le hij)) (natCast_mem S _)) _

/-- The subring generated by the generalized binomial coefficients of an element does not see the
sign of that element. -/
@[simp]
theorem closure_range_choose_neg (r : R) :
    Subring.closure (Set.range (_root_.Ring.choose (-r))) =
      Subring.closure (Set.range (_root_.Ring.choose r)) := by
  refine le_antisymm (Subring.closure_le.mpr ?_) (Subring.closure_le.mpr ?_)
  · rintro _ ⟨n, rfl⟩
    exact choose_neg_mem (S := Subring.closure (Set.range (_root_.Ring.choose r)))
      fun k _ => Subring.subset_closure ⟨k, rfl⟩
  · rintro _ ⟨n, rfl⟩
    have hmem := choose_neg_mem (S := Subring.closure (Set.range (_root_.Ring.choose (-r))))
      (r := -r) (n := n) fun k _ => Subring.subset_closure ⟨k, rfl⟩
    rwa [neg_neg] at hmem

end TauCeti.Ring
